name: shyft
channels:
  - sigbjorn
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pyyaml
  - numpy=1.13
  - netcdf4 
  - gdal 
  - matplotlib 
  - requests 
  - nose 
  - coverage 
  - pip 
  - shapely 
  - pyproj 
  - jupyter 
  - pandas 
  - shyft 
  - scipy
  - bokeh
