var hierarchy =
[
    [ "shyft::api::a_region_environment", "structshyft_1_1api_1_1a__region__environment.html", null ],
    [ "shyft::time_series::accumulate_accessor< S, TA >", "classshyft_1_1time__series_1_1accumulate__accessor.html", null ],
    [ "shyft::time_series::accumulate_ts< TS, TA >", "structshyft_1_1time__series_1_1accumulate__ts.html", null ],
    [ "shyft::api::actual_evapotranspiration_cell_response_statistics< cell >", "structshyft_1_1api_1_1actual__evapotranspiration__cell__response__statistics.html", null ],
    [ "shyft::core::hbv_stack::all_response_collector", "structshyft_1_1core_1_1hbv__stack_1_1all__response__collector.html", null ],
    [ "shyft::core::pt_gs_k::all_response_collector", "structshyft_1_1core_1_1pt__gs__k_1_1all__response__collector.html", null ],
    [ "shyft::core::pt_hs_k::all_response_collector", "structshyft_1_1core_1_1pt__hs__k_1_1all__response__collector.html", null ],
    [ "shyft::core::pt_ss_k::all_response_collector", "structshyft_1_1core_1_1pt__ss__k_1_1all__response__collector.html", null ],
    [ "shyft::api::apoint_ts", "structshyft_1_1api_1_1apoint__ts.html", null ],
    [ "shyft::dtss::apoint_ts_frag", "structshyft_1_1dtss_1_1apoint__ts__frag.html", null ],
    [ "shyft::core::model_calibration::area_ts", "structshyft_1_1core_1_1model__calibration_1_1area__ts.html", null ],
    [ "shyft::time_series::average_accessor< S, TA >", "classshyft_1_1time__series_1_1average__accessor.html", null ],
    [ "shyft::time_series::average_ts< TS, TA >", "structshyft_1_1time__series_1_1average__ts.html", null ],
    [ "shyft::api::basic_cell_statistics< cell >", "structshyft_1_1api_1_1basic__cell__statistics.html", null ],
    [ "shyft::core::kalman::bias_predictor", "structshyft_1_1core_1_1kalman_1_1bias__predictor.html", null ],
    [ "shyft::time_series::bin_op< A, B, O, TA >", "structshyft_1_1time__series_1_1bin__op.html", null ],
    [ "shyft::time_series::bin_op< A, double, O, TA >", "structshyft_1_1time__series_1_1bin__op_3_01_a_00_01double_00_01_o_00_01_t_a_01_4.html", null ],
    [ "shyft::time_series::bin_op< double, B, O, TA >", "structshyft_1_1time__series_1_1bin__op_3_01double_00_01_b_00_01_o_00_01_t_a_01_4.html", null ],
    [ "shyft::core::time_zone::boost_tz_info", "structshyft_1_1core_1_1time__zone_1_1boost__tz__info.html", null ],
    [ "shyft::dtss::cache< ts_frag, ts_t >", "structshyft_1_1dtss_1_1cache.html", null ],
    [ "shyft::dtss::cache< apoint_ts_frag, apoint_ts >", "structshyft_1_1dtss_1_1cache.html", null ],
    [ "shyft::dtss::cache_stats", "structshyft_1_1dtss_1_1cache__stats.html", null ],
    [ "shyft::core::skaugen::calculator< P, S, R >", "classshyft_1_1core_1_1skaugen_1_1calculator.html", null ],
    [ "shyft::core::gamma_snow::calculator< P, S, R >", "classshyft_1_1core_1_1gamma__snow_1_1calculator.html", null ],
    [ "shyft::core::kirchner::calculator< AC, P >", "classshyft_1_1core_1_1kirchner_1_1calculator.html", null ],
    [ "shyft::core::hbv_snow::calculator< P, S >", "structshyft_1_1core_1_1hbv__snow_1_1calculator.html", null ],
    [ "shyft::core::hbv_soil::calculator< P >", "structshyft_1_1core_1_1hbv__soil_1_1calculator.html", null ],
    [ "shyft::core::precipitation_correction::calculator", "structshyft_1_1core_1_1precipitation__correction_1_1calculator.html", null ],
    [ "shyft::core::priestley_taylor::calculator", "structshyft_1_1core_1_1priestley__taylor_1_1calculator.html", null ],
    [ "shyft::core::hbv_tank::calculator< P >", "structshyft_1_1core_1_1hbv__tank_1_1calculator.html", null ],
    [ "shyft::core::calendar", "structshyft_1_1core_1_1calendar.html", null ],
    [ "shyft::core::cell< P, E, S, SC, RC >", "structshyft_1_1core_1_1cell.html", null ],
    [ "shyft::experimental::repository::cell_file_repository< C >", "classshyft_1_1experimental_1_1repository_1_1cell__file__repository.html", null ],
    [ "shyft::api::cell_state_id", "structshyft_1_1api_1_1cell__state__id.html", null ],
    [ "shyft::api::cell_state_with_id< CS >", "structshyft_1_1api_1_1cell__state__with__id.html", null ],
    [ "shyft::core::cell_statistics", "structshyft_1_1core_1_1cell__statistics.html", null ],
    [ "shyft::dtss::client", "structshyft_1_1dtss_1_1client.html", null ],
    [ "shyft::time_axis::combine_type< T_A, T_B, C >", "structshyft_1_1time__axis_1_1combine__type.html", null ],
    [ "shyft::time_axis::combine_type< fixed_dt, fixed_dt, void >", "structshyft_1_1time__axis_1_1combine__type_3_01fixed__dt_00_01fixed__dt_00_01void_01_4.html", null ],
    [ "shyft::time_axis::combine_type< T_A, T_B, typename enable_if< T_A::continuous::value &&T_B::continuous::value >::type >", "structshyft_1_1time__axis_1_1combine__type_3_01_t___a_00_01_t___b_00_01typename_01enable__if_3_086a4fbcb431e554b079aed359898683b.html", null ],
    [ "shyft::core::kirchner::composite_trapezoidal_average< S >", "classshyft_1_1core_1_1kirchner_1_1composite__trapezoidal__average.html", null ],
    [ "shyft::core::bayesian_kriging::const_parameter", "classshyft_1_1core_1_1bayesian__kriging_1_1const__parameter.html", null ],
    [ "shyft::time_series::constant_timeseries< TA >", "classshyft_1_1time__series_1_1constant__timeseries.html", null ],
    [ "shyft::time_axis::continuous< T >", "structshyft_1_1time__axis_1_1continuous.html", null ],
    [ "shyft::time_axis::continuous< false >", "structshyft_1_1time__axis_1_1continuous.html", [
      [ "shyft::time_axis::calendar_dt_p", "structshyft_1_1time__axis_1_1calendar__dt__p.html", null ],
      [ "shyft::time_axis::period_list", "structshyft_1_1time__axis_1_1period__list.html", null ]
    ] ],
    [ "shyft::time_axis::continuous< true >", "structshyft_1_1time__axis_1_1continuous_3_01true_01_4.html", [
      [ "shyft::time_axis::calendar_dt", "structshyft_1_1time__axis_1_1calendar__dt.html", null ],
      [ "shyft::time_axis::fixed_dt", "structshyft_1_1time__axis_1_1fixed__dt.html", null ],
      [ "shyft::time_axis::generic_dt", "structshyft_1_1time__axis_1_1generic__dt.html", null ],
      [ "shyft::time_axis::point_dt", "structshyft_1_1time__axis_1_1point__dt.html", null ]
    ] ],
    [ "shyft::time_series::convolve_w_ts< Ts >", "structshyft_1_1time__series_1_1convolve__w__ts.html", null ],
    [ "shyft::time_series::convolve_w_ts< apoint_ts >", "structshyft_1_1time__series_1_1convolve__w__ts.html", null ],
    [ "shyft::time_series::d_ref_t< T, P >", "structshyft_1_1time__series_1_1d__ref__t.html", null ],
    [ "shyft::time_series::d_ref_t< T, typename enable_if< is_shared_ptr< T >::value >::type >", "structshyft_1_1time__series_1_1d__ref__t_3_01_t_00_01typename_01enable__if_3_01is__shared__ptr_3ca87b6a9d8d7f88f64384654d655af5d.html", null ],
    [ "shyft::time_series::d_ref_t< T, typename enable_if<!is_shared_ptr< T >::value >::type >", "structshyft_1_1time__series_1_1d__ref__t_3_01_t_00_01typename_01enable__if_3_9is__shared__ptr_3_1f01fc20822a213214abfd64fb1aec7c.html", null ],
    [ "shyft::time_series::direct_accessor< S, TA >", "classshyft_1_1time__series_1_1direct__accessor.html", null ],
    [ "shyft::time_series::direct_accessor< constant_timeseries< TA >, TA >", "classshyft_1_1time__series_1_1direct__accessor_3_01constant__timeseries_3_01_t_a_01_4_00_01_t_a_01_4.html", null ],
    [ "shyft::time_series::direct_accessor< point_ts< TA >, TA >", "classshyft_1_1time__series_1_1direct__accessor_3_01point__ts_3_01_t_a_01_4_00_01_t_a_01_4.html", null ],
    [ "shyft::core::hbv_stack::discharge_collector", "structshyft_1_1core_1_1hbv__stack_1_1discharge__collector.html", null ],
    [ "shyft::core::pt_gs_k::discharge_collector", "structshyft_1_1core_1_1pt__gs__k_1_1discharge__collector.html", null ],
    [ "shyft::core::pt_hs_k::discharge_collector", "structshyft_1_1core_1_1pt__hs__k_1_1discharge__collector.html", null ],
    [ "shyft::core::pt_ss_k::discharge_collector", "structshyft_1_1core_1_1pt__ss__k_1_1discharge__collector.html", null ],
    [ "shyft::core::optimizer::dream", "classshyft_1_1core_1_1optimizer_1_1dream.html", null ],
    [ "shyft::experimental::dtm", "structshyft_1_1experimental_1_1dtm.html", null ],
    [ "shyft::core::environment< timeaxis, temperature_ts, precipitation_ts, radiation_ts, relhum_ts, windspeed_ts >", "structshyft_1_1core_1_1environment.html", null ],
    [ "exception", null, [
      [ "shyft::core::skaugen::mass_balance_error", "classshyft_1_1core_1_1skaugen_1_1mass__balance__error.html", null ]
    ] ],
    [ "shyft::core::kriging::covariance::exponential", "structshyft_1_1core_1_1kriging_1_1covariance_1_1exponential.html", null ],
    [ "false_type", null, [
      [ "shyft::core::model_calibration::detect_snow_sca< T, class >", "structshyft_1_1core_1_1model__calibration_1_1detect__snow__sca.html", null ],
      [ "shyft::core::model_calibration::detect_snow_swe< T, class >", "structshyft_1_1core_1_1model__calibration_1_1detect__snow__swe.html", null ]
    ] ],
    [ "false_type", null, [
      [ "shyft::time_series::needs_bind_dispatcher< T, typename >", "structshyft_1_1time__series_1_1needs__bind__dispatcher.html", null ]
    ] ],
    [ "shyft::core::kalman::filter", "structshyft_1_1core_1_1kalman_1_1filter.html", null ],
    [ "shyft::api::gamma_snow_cell_response_statistics< cell >", "structshyft_1_1api_1_1gamma__snow__cell__response__statistics.html", null ],
    [ "shyft::api::gamma_snow_cell_state_statistics< cell >", "structshyft_1_1api_1_1gamma__snow__cell__state__statistics.html", null ],
    [ "shyft::core::kriging::covariance::gaussian", "structshyft_1_1core_1_1kriging_1_1covariance_1_1gaussian.html", null ],
    [ "shyft::core::geo_cell_data", "structshyft_1_1core_1_1geo__cell__data.html", null ],
    [ "shyft::experimental::geo_cell_data_computer", "classshyft_1_1experimental_1_1geo__cell__data__computer.html", null ],
    [ "shyft::api::geo_cell_data_io", "structshyft_1_1api_1_1geo__cell__data__io.html", null ],
    [ "shyft::experimental::repository::geo_located_ts_file_repository", "classshyft_1_1experimental_1_1repository_1_1geo__located__ts__file__repository.html", null ],
    [ "shyft::core::geo_point", "structshyft_1_1core_1_1geo__point.html", null ],
    [ "shyft::core::geo_point_ts< T >", "structshyft_1_1core_1_1geo__point__ts.html", null ],
    [ "shyft::api::GeoPointSource", "structshyft_1_1api_1_1_geo_point_source.html", [
      [ "shyft::api::PrecipitationSource", "structshyft_1_1api_1_1_precipitation_source.html", null ],
      [ "shyft::api::RadiationSource", "structshyft_1_1api_1_1_radiation_source.html", null ],
      [ "shyft::api::RelHumSource", "structshyft_1_1api_1_1_rel_hum_source.html", null ],
      [ "shyft::api::TemperatureSource", "structshyft_1_1api_1_1_temperature_source.html", null ],
      [ "shyft::api::WindSpeedSource", "structshyft_1_1api_1_1_wind_speed_source.html", null ]
    ] ],
    [ "shyft::time_series::glacier_melt_ts< TS_A, TS_B >", "structshyft_1_1time__series_1_1glacier__melt__ts.html", null ],
    [ "shyft::time_series::glacier_melt_ts< std::shared_ptr< shyft::api::ipoint_ts > >", "structshyft_1_1time__series_1_1glacier__melt__ts.html", null ],
    [ "shyft::api::hbv_actual_evapotranspiration_cell_response_statistics< cell >", "structshyft_1_1api_1_1hbv__actual__evapotranspiration__cell__response__statistics.html", null ],
    [ "shyft::api::hbv_snow_cell_response_statistics< cell >", "structshyft_1_1api_1_1hbv__snow__cell__response__statistics.html", null ],
    [ "shyft::api::hbv_snow_cell_state_statistics< cell >", "structshyft_1_1api_1_1hbv__snow__cell__state__statistics.html", null ],
    [ "shyft::api::hbv_soil_cell_response_statistics< cell >", "structshyft_1_1api_1_1hbv__soil__cell__response__statistics.html", null ],
    [ "shyft::api::hbv_soil_cell_state_statistics< cell >", "structshyft_1_1api_1_1hbv__soil__cell__state__statistics.html", null ],
    [ "shyft::api::hbv_stack_state_io", "structshyft_1_1api_1_1hbv__stack__state__io.html", null ],
    [ "shyft::api::hbv_tank_cell_state_statistics< cell >", "structshyft_1_1api_1_1hbv__tank__cell__state__statistics.html", null ],
    [ "shyft::core::idw_compliant_geo_point_ts< GPTS, TSA, TA >", "classshyft_1_1core_1_1idw__compliant__geo__point__ts.html", null ],
    [ "shyft::core::inverse_distance::idw_timeaxis< TA >", "classshyft_1_1core_1_1inverse__distance_1_1idw__timeaxis.html", null ],
    [ "shyft::core::optimizer::ifx", "structshyft_1_1core_1_1optimizer_1_1ifx.html", [
      [ "shyft::core::model_calibration::dream_fx< M >", "structshyft_1_1core_1_1model__calibration_1_1dream__fx.html", null ],
      [ "shyft::core::model_calibration::sceua_fx< M >", "structshyft_1_1core_1_1model__calibration_1_1sceua__fx.html", null ]
    ] ],
    [ "shyft::core::interpolation_parameter", "structshyft_1_1core_1_1interpolation__parameter.html", null ],
    [ "shyft::api::ipoint_ts", "structshyft_1_1api_1_1ipoint__ts.html", [
      [ "shyft::api::abin_op_scalar_ts", "structshyft_1_1api_1_1abin__op__scalar__ts.html", null ],
      [ "shyft::api::abin_op_ts", "structshyft_1_1api_1_1abin__op__ts.html", null ],
      [ "shyft::api::abin_op_ts_scalar", "structshyft_1_1api_1_1abin__op__ts__scalar.html", null ],
      [ "shyft::api::abs_ts", "structshyft_1_1api_1_1abs__ts.html", null ],
      [ "shyft::api::accumulate_ts", "structshyft_1_1api_1_1accumulate__ts.html", null ],
      [ "shyft::api::aglacier_melt_ts", "structshyft_1_1api_1_1aglacier__melt__ts.html", null ],
      [ "shyft::api::aref_ts", "structshyft_1_1api_1_1aref__ts.html", null ],
      [ "shyft::api::average_ts", "structshyft_1_1api_1_1average__ts.html", null ],
      [ "shyft::api::convolve_w_ts", "structshyft_1_1api_1_1convolve__w__ts.html", null ],
      [ "shyft::api::extend_ts", "structshyft_1_1api_1_1extend__ts.html", null ],
      [ "shyft::api::gpoint_ts", "structshyft_1_1api_1_1gpoint__ts.html", null ],
      [ "shyft::api::integral_ts", "structshyft_1_1api_1_1integral__ts.html", null ],
      [ "shyft::api::krls_interpolation_ts", "structshyft_1_1api_1_1krls__interpolation__ts.html", null ],
      [ "shyft::api::periodic_ts", "structshyft_1_1api_1_1periodic__ts.html", null ],
      [ "shyft::api::rating_curve_ts", "structshyft_1_1api_1_1rating__curve__ts.html", null ],
      [ "shyft::api::time_shift_ts", "structshyft_1_1api_1_1time__shift__ts.html", null ]
    ] ],
    [ "shyft::time_series::is_shared_ptr< T >", "structshyft_1_1time__series_1_1is__shared__ptr.html", null ],
    [ "shyft::time_series::is_shared_ptr< shared_ptr< T > >", "structshyft_1_1time__series_1_1is__shared__ptr_3_01shared__ptr_3_01_t_01_4_01_4.html", null ],
    [ "shyft::time_series::is_ts< T >", "structshyft_1_1time__series_1_1is__ts.html", null ],
    [ "shyft::time_series::is_ts< average_ts< TS, TA > >", "structshyft_1_1time__series_1_1is__ts_3_01average__ts_3_01_t_s_00_01_t_a_01_4_01_4.html", null ],
    [ "shyft::time_series::is_ts< bin_op< A, B, O, TA > >", "structshyft_1_1time__series_1_1is__ts_3_01bin__op_3_01_a_00_01_b_00_01_o_00_01_t_a_01_4_01_4.html", null ],
    [ "shyft::time_series::is_ts< convolve_w_ts< TS > >", "structshyft_1_1time__series_1_1is__ts_3_01convolve__w__ts_3_01_t_s_01_4_01_4.html", null ],
    [ "shyft::time_series::is_ts< glacier_melt_ts< T > >", "structshyft_1_1time__series_1_1is__ts_3_01glacier__melt__ts_3_01_t_01_4_01_4.html", null ],
    [ "shyft::time_series::is_ts< point_ts< T > >", "structshyft_1_1time__series_1_1is__ts_3_01point__ts_3_01_t_01_4_01_4.html", null ],
    [ "shyft::time_series::is_ts< rating_curve_ts< TS > >", "structshyft_1_1time__series_1_1is__ts_3_01rating__curve__ts_3_01_t_s_01_4_01_4.html", null ],
    [ "shyft::time_series::is_ts< ref_ts< T > >", "structshyft_1_1time__series_1_1is__ts_3_01ref__ts_3_01_t_01_4_01_4.html", null ],
    [ "shyft::time_series::is_ts< shared_ptr< average_ts< TS, TA > > >", "structshyft_1_1time__series_1_1is__ts_3_01shared__ptr_3_01average__ts_3_01_t_s_00_01_t_a_01_4_01_4_01_4.html", null ],
    [ "shyft::time_series::is_ts< shared_ptr< convolve_w_ts< TS > > >", "structshyft_1_1time__series_1_1is__ts_3_01shared__ptr_3_01convolve__w__ts_3_01_t_s_01_4_01_4_01_4.html", null ],
    [ "shyft::time_series::is_ts< shared_ptr< glacier_melt_ts< T > > >", "structshyft_1_1time__series_1_1is__ts_3_01shared__ptr_3_01glacier__melt__ts_3_01_t_01_4_01_4_01_4.html", null ],
    [ "shyft::time_series::is_ts< shared_ptr< point_ts< T > > >", "structshyft_1_1time__series_1_1is__ts_3_01shared__ptr_3_01point__ts_3_01_t_01_4_01_4_01_4.html", null ],
    [ "shyft::time_series::is_ts< shared_ptr< ref_ts< T > > >", "structshyft_1_1time__series_1_1is__ts_3_01shared__ptr_3_01ref__ts_3_01_t_01_4_01_4_01_4.html", null ],
    [ "shyft::time_series::is_ts< shared_ptr< time_shift_ts< T > > >", "structshyft_1_1time__series_1_1is__ts_3_01shared__ptr_3_01time__shift__ts_3_01_t_01_4_01_4_01_4.html", null ],
    [ "shyft::time_series::is_ts< shared_ptr< uniform_sum_ts< T > > >", "structshyft_1_1time__series_1_1is__ts_3_01shared__ptr_3_01uniform__sum__ts_3_01_t_01_4_01_4_01_4.html", null ],
    [ "shyft::time_series::is_ts< time_shift_ts< T > >", "structshyft_1_1time__series_1_1is__ts_3_01time__shift__ts_3_01_t_01_4_01_4.html", null ],
    [ "shyft::time_series::is_ts< uniform_sum_ts< T > >", "structshyft_1_1time__series_1_1is__ts_3_01uniform__sum__ts_3_01_t_01_4_01_4.html", null ],
    [ "shyft::api::kirchner_cell_state_statistics< cell >", "structshyft_1_1api_1_1kirchner__cell__state__statistics.html", null ],
    [ "shyft::prediction::krls_rbf_predictor", "classshyft_1_1prediction_1_1krls__rbf__predictor.html", null ],
    [ "shyft::core::land_type_fractions", "structshyft_1_1core_1_1land__type__fractions.html", null ],
    [ "shyft::dtss::lru_cache< K, V, MAP >", "structshyft_1_1dtss_1_1lru__cache.html", null ],
    [ "shyft::dtss::lru_cache< string, value_type, map >", "structshyft_1_1dtss_1_1lru__cache.html", null ],
    [ "shyft::time_axis::merge_info", "structshyft_1_1time__axis_1_1merge__info.html", null ],
    [ "shyft::dtss::mini_frag< ts_frag >", "structshyft_1_1dtss_1_1mini__frag.html", null ],
    [ "shyft::core::routing::model< C >", "structshyft_1_1core_1_1routing_1_1model.html", null ],
    [ "shyft::time_series::needs_bind< T >", "structshyft_1_1time__series_1_1needs__bind.html", null ],
    [ "shyft::time_series::needs_bind< point_ts< Ta > >", "structshyft_1_1time__series_1_1needs__bind_3_01point__ts_3_01_ta_01_4_01_4.html", null ],
    [ "shyft::core::pt_ss_k::null_collector", "structshyft_1_1core_1_1pt__ss__k_1_1null__collector.html", null ],
    [ "shyft::core::hbv_stack::null_collector", "structshyft_1_1core_1_1hbv__stack_1_1null__collector.html", null ],
    [ "shyft::core::pt_gs_k::null_collector", "structshyft_1_1core_1_1pt__gs__k_1_1null__collector.html", null ],
    [ "shyft::core::pt_hs_k::null_collector", "structshyft_1_1core_1_1pt__hs__k_1_1null__collector.html", null ],
    [ "shyft::experimental::observation_location", "structshyft_1_1experimental_1_1observation__location.html", null ],
    [ "shyft::time_series::op_axis< L, R >", "structshyft_1_1time__series_1_1op__axis.html", null ],
    [ "shyft::time_series::op_axis< double, R >", "structshyft_1_1time__series_1_1op__axis_3_01double_00_01_r_01_4.html", null ],
    [ "shyft::time_series::op_axis< L, double >", "structshyft_1_1time__series_1_1op__axis_3_01_l_00_01double_01_4.html", null ],
    [ "shyft::time_series::op_max", "structshyft_1_1time__series_1_1op__max.html", null ],
    [ "shyft::time_series::op_min", "structshyft_1_1time__series_1_1op__min.html", null ],
    [ "shyft::core::model_calibration::optimizer< M, PA, PS >", "classshyft_1_1core_1_1model__calibration_1_1optimizer.html", null ],
    [ "shyft::core::pt_gs_k::parameter", "structshyft_1_1core_1_1pt__gs__k_1_1parameter.html", null ],
    [ "shyft::core::hbv_snow::parameter", "structshyft_1_1core_1_1hbv__snow_1_1parameter.html", null ],
    [ "shyft::core::skaugen::parameter", "structshyft_1_1core_1_1skaugen_1_1parameter.html", null ],
    [ "shyft::core::glacier_melt::parameter", "structshyft_1_1core_1_1glacier__melt_1_1parameter.html", null ],
    [ "shyft::core::bayesian_kriging::parameter", "classshyft_1_1core_1_1bayesian__kriging_1_1parameter.html", null ],
    [ "shyft::core::kirchner::parameter", "structshyft_1_1core_1_1kirchner_1_1parameter.html", null ],
    [ "shyft::core::hbv_actual_evapotranspiration::parameter", "structshyft_1_1core_1_1hbv__actual__evapotranspiration_1_1parameter.html", null ],
    [ "shyft::core::kalman::parameter", "structshyft_1_1core_1_1kalman_1_1parameter.html", null ],
    [ "shyft::core::hbv_soil::parameter", "structshyft_1_1core_1_1hbv__soil_1_1parameter.html", null ],
    [ "shyft::core::hbv_stack::parameter", "structshyft_1_1core_1_1hbv__stack_1_1parameter.html", null ],
    [ "shyft::core::actual_evapotranspiration::parameter", "structshyft_1_1core_1_1actual__evapotranspiration_1_1parameter.html", null ],
    [ "shyft::core::precipitation_correction::parameter", "structshyft_1_1core_1_1precipitation__correction_1_1parameter.html", null ],
    [ "shyft::core::priestley_taylor::parameter", "structshyft_1_1core_1_1priestley__taylor_1_1parameter.html", null ],
    [ "shyft::core::hbv_tank::parameter", "structshyft_1_1core_1_1hbv__tank_1_1parameter.html", null ],
    [ "shyft::core::pt_hs_k::parameter", "structshyft_1_1core_1_1pt__hs__k_1_1parameter.html", null ],
    [ "shyft::core::gamma_snow::parameter", "structshyft_1_1core_1_1gamma__snow_1_1parameter.html", null ],
    [ "shyft::core::inverse_distance::parameter", "structshyft_1_1core_1_1inverse__distance_1_1parameter.html", [
      [ "shyft::core::inverse_distance::precipitation_parameter", "structshyft_1_1core_1_1inverse__distance_1_1precipitation__parameter.html", null ],
      [ "shyft::core::inverse_distance::temperature_parameter", "structshyft_1_1core_1_1inverse__distance_1_1temperature__parameter.html", null ]
    ] ],
    [ "shyft::core::pt_ss_k::parameter", "structshyft_1_1core_1_1pt__ss__k_1_1parameter.html", null ],
    [ "shyft::time_series::periodic_ts< TA >", "structshyft_1_1time__series_1_1periodic__ts.html", null ],
    [ "shyft::time_series::periodic_ts< gta_t >", "structshyft_1_1time__series_1_1periodic__ts.html", null ],
    [ "shyft::time_series::point", "structshyft_1_1time__series_1_1point.html", null ],
    [ "shyft::time_series::point_ts< TA >", "structshyft_1_1time__series_1_1point__ts.html", null ],
    [ "shyft::time_series::point_ts< gta_t >", "structshyft_1_1time__series_1_1point__ts.html", null ],
    [ "shyft::time_series::point_ts< time_axis::fixed_dt >", "structshyft_1_1time__series_1_1point__ts.html", null ],
    [ "shyft::core::inverse_distance::precipitation_model< S, D, P, G >", "structshyft_1_1core_1_1inverse__distance_1_1precipitation__model.html", null ],
    [ "shyft::api::priestley_taylor_cell_response_statistics< cell >", "structshyft_1_1api_1_1priestley__taylor__cell__response__statistics.html", null ],
    [ "shyft::time_series::profile_accessor< TA >", "structshyft_1_1time__series_1_1profile__accessor.html", null ],
    [ "shyft::time_series::profile_accessor< gta_t >", "structshyft_1_1time__series_1_1profile__accessor.html", null ],
    [ "shyft::time_series::profile_description", "structshyft_1_1time__series_1_1profile__description.html", null ],
    [ "shyft::api::pt_gs_k_state_io", "structshyft_1_1api_1_1pt__gs__k__state__io.html", null ],
    [ "shyft::api::pt_hs_k_state_io", "structshyft_1_1api_1_1pt__hs__k__state__io.html", null ],
    [ "shyft::api::pt_ss_k_state_io", "structshyft_1_1api_1_1pt__ss__k__state__io.html", null ],
    [ "shyft::core::inverse_distance::radiation_model< S, D, P, G >", "structshyft_1_1core_1_1inverse__distance_1_1radiation__model.html", null ],
    [ "shyft::time_series::rating_curve_function", "classshyft_1_1time__series_1_1rating__curve__function.html", null ],
    [ "shyft::time_series::rating_curve_parameters", "classshyft_1_1time__series_1_1rating__curve__parameters.html", null ],
    [ "shyft::time_series::rating_curve_segment", "classshyft_1_1time__series_1_1rating__curve__segment.html", null ],
    [ "shyft::time_series::rating_curve_ts< TS >", "classshyft_1_1time__series_1_1rating__curve__ts.html", null ],
    [ "shyft::time_series::rating_curve_ts< apoint_ts >", "classshyft_1_1time__series_1_1rating__curve__ts.html", null ],
    [ "shyft::time_series::ref_ts< TS >", "structshyft_1_1time__series_1_1ref__ts.html", null ],
    [ "shyft::core::region_environment< PS, TS, RS, HS, WS >", "structshyft_1_1core_1_1region__environment.html", null ],
    [ "shyft::experimental::region_grid", "classshyft_1_1experimental_1_1region__grid.html", null ],
    [ "shyft::core::region_model< C, RE >", "classshyft_1_1core_1_1region__model.html", null ],
    [ "shyft::experimental::orchestration::region_orchestrator", "classshyft_1_1experimental_1_1orchestration_1_1region__orchestrator.html", null ],
    [ "shyft::core::inverse_distance::rel_hum_model< S, D, P, G >", "structshyft_1_1core_1_1inverse__distance_1_1rel__hum__model.html", null ],
    [ "shyft::core::actual_evapotranspiration::response", "structshyft_1_1core_1_1actual__evapotranspiration_1_1response.html", null ],
    [ "shyft::core::priestley_taylor::response", "structshyft_1_1core_1_1priestley__taylor_1_1response.html", null ],
    [ "shyft::core::skaugen::response", "structshyft_1_1core_1_1skaugen_1_1response.html", null ],
    [ "shyft::core::hbv_actual_evapotranspiration::response", "structshyft_1_1core_1_1hbv__actual__evapotranspiration_1_1response.html", null ],
    [ "shyft::core::kirchner::response", "structshyft_1_1core_1_1kirchner_1_1response.html", null ],
    [ "shyft::core::hbv_stack::response", "structshyft_1_1core_1_1hbv__stack_1_1response.html", null ],
    [ "shyft::core::hbv_snow::response", "structshyft_1_1core_1_1hbv__snow_1_1response.html", null ],
    [ "shyft::core::gamma_snow::response", "structshyft_1_1core_1_1gamma__snow_1_1response.html", null ],
    [ "shyft::core::hbv_soil::response", "structshyft_1_1core_1_1hbv__soil_1_1response.html", null ],
    [ "shyft::core::pt_gs_k::response", "structshyft_1_1core_1_1pt__gs__k_1_1response.html", null ],
    [ "shyft::core::pt_hs_k::response", "structshyft_1_1core_1_1pt__hs__k_1_1response.html", null ],
    [ "shyft::core::hbv_tank::response", "structshyft_1_1core_1_1hbv__tank_1_1response.html", null ],
    [ "shyft::core::pt_ss_k::response", "structshyft_1_1core_1_1pt__ss__k_1_1response.html", null ],
    [ "shyft::core::routing::river", "structshyft_1_1core_1_1routing_1_1river.html", null ],
    [ "shyft::core::routing::river_network", "structshyft_1_1core_1_1routing_1_1river__network.html", null ],
    [ "shyft::core::routing_info", "structshyft_1_1core_1_1routing__info.html", null ],
    [ "shyft::core::inverse_distance::radiation_model< S, D, P, G >::scale_computer", "structshyft_1_1core_1_1inverse__distance_1_1radiation__model_1_1scale__computer.html", null ],
    [ "shyft::core::inverse_distance::wind_speed_model< S, D, P, G >::scale_computer", "structshyft_1_1core_1_1inverse__distance_1_1wind__speed__model_1_1scale__computer.html", null ],
    [ "shyft::core::inverse_distance::precipitation_model< S, D, P, G >::scale_computer", "structshyft_1_1core_1_1inverse__distance_1_1precipitation__model_1_1scale__computer.html", null ],
    [ "shyft::core::inverse_distance::rel_hum_model< S, D, P, G >::scale_computer", "structshyft_1_1core_1_1inverse__distance_1_1rel__hum__model_1_1scale__computer.html", null ],
    [ "shyft::core::optimizer::sceua", "classshyft_1_1core_1_1optimizer_1_1sceua.html", null ],
    [ "server_iostream", null, [
      [ "shyft::dtss::server", "structshyft_1_1dtss_1_1server.html", null ]
    ] ],
    [ "shyft::api::skaugen_cell_response_statistics< cell >", "structshyft_1_1api_1_1skaugen__cell__response__statistics.html", null ],
    [ "shyft::api::skaugen_cell_state_statistics< cell >", "structshyft_1_1api_1_1skaugen__cell__state__statistics.html", null ],
    [ "shyft::core::optimizer::sort_by_value_asc< vec >", "structshyft_1_1core_1_1optimizer_1_1sort__by__value__asc.html", null ],
    [ "shyft::core::hbv_soil::state", "structshyft_1_1core_1_1hbv__soil_1_1state.html", null ],
    [ "shyft::core::skaugen::state", "structshyft_1_1core_1_1skaugen_1_1state.html", null ],
    [ "shyft::core::pt_hs_k::state", "structshyft_1_1core_1_1pt__hs__k_1_1state.html", null ],
    [ "shyft::core::hbv_tank::state", "structshyft_1_1core_1_1hbv__tank_1_1state.html", null ],
    [ "shyft::core::hbv_snow::state", "structshyft_1_1core_1_1hbv__snow_1_1state.html", null ],
    [ "shyft::core::kirchner::state", "structshyft_1_1core_1_1kirchner_1_1state.html", null ],
    [ "shyft::core::kalman::state", "structshyft_1_1core_1_1kalman_1_1state.html", null ],
    [ "shyft::core::hbv_stack::state", "structshyft_1_1core_1_1hbv__stack_1_1state.html", null ],
    [ "shyft::core::gamma_snow::state", "structshyft_1_1core_1_1gamma__snow_1_1state.html", null ],
    [ "shyft::core::pt_gs_k::state", "structshyft_1_1core_1_1pt__gs__k_1_1state.html", null ],
    [ "shyft::core::pt_ss_k::state", "structshyft_1_1core_1_1pt__ss__k_1_1state.html", null ],
    [ "shyft::core::hbv_stack::state_collector", "structshyft_1_1core_1_1hbv__stack_1_1state__collector.html", null ],
    [ "shyft::core::pt_hs_k::state_collector", "structshyft_1_1core_1_1pt__hs__k_1_1state__collector.html", null ],
    [ "shyft::core::pt_ss_k::state_collector", "structshyft_1_1core_1_1pt__ss__k_1_1state__collector.html", null ],
    [ "shyft::core::pt_gs_k::state_collector", "structshyft_1_1core_1_1pt__gs__k_1_1state__collector.html", null ],
    [ "shyft::experimental::repository::state_file_repository< S >", "classshyft_1_1experimental_1_1repository_1_1state__file__repository.html", null ],
    [ "shyft::experimental::repository::state_info", "structshyft_1_1experimental_1_1repository_1_1state__info.html", null ],
    [ "shyft::api::state_io_handler< C >", "structshyft_1_1api_1_1state__io__handler.html", null ],
    [ "shyft::time_series::statistics< Ts, Ta, typename >", "structshyft_1_1time__series_1_1statistics.html", null ],
    [ "shyft::core::skaugen::statistics", "structshyft_1_1core_1_1skaugen_1_1statistics.html", null ],
    [ "shyft::core::model_calibration::target_specification< PS >", "structshyft_1_1core_1_1model__calibration_1_1target__specification.html", null ],
    [ "shyft::core::inverse_distance::temperature_gradient_scale_computer::temp_point", "structshyft_1_1core_1_1inverse__distance_1_1temperature__gradient__scale__computer_1_1temp__point.html", null ],
    [ "shyft::core::inverse_distance::temperature_default_gradient_scale_computer", "structshyft_1_1core_1_1inverse__distance_1_1temperature__default__gradient__scale__computer.html", null ],
    [ "shyft::core::inverse_distance::temperature_gradient_scale_computer", "structshyft_1_1core_1_1inverse__distance_1_1temperature__gradient__scale__computer.html", null ],
    [ "shyft::core::inverse_distance::temperature_model< S, D, P, G, SC >", "structshyft_1_1core_1_1inverse__distance_1_1temperature__model.html", null ],
    [ "shyft::time_axis::time_axis_map< TA1, TA2 >", "structshyft_1_1time__axis_1_1time__axis__map.html", null ],
    [ "shyft::time_axis::time_axis_map< time_axis::fixed_dt, time_axis::fixed_dt >", "structshyft_1_1time__axis_1_1time__axis__map_3_01time__axis_1_1fixed__dt_00_01time__axis_1_1fixed__dt_01_4.html", null ],
    [ "shyft::time_series::time_shift_ts< Ts >", "structshyft_1_1time__series_1_1time__shift__ts.html", null ],
    [ "shyft::core::kirchner::trapezoidal_average< S >", "classshyft_1_1core_1_1kirchner_1_1trapezoidal__average.html", null ],
    [ "true_type", null, [
      [ "shyft::core::model_calibration::detect_snow_sca< T, decltype(T::snow_sca, void())>", "structshyft_1_1core_1_1model__calibration_1_1detect__snow__sca_3_01_t_00_01decltype_07_t_1_1snow__sca_00_01void_07_08_08_4.html", null ],
      [ "shyft::core::model_calibration::detect_snow_swe< T, decltype(T::snow_swe, void())>", "structshyft_1_1core_1_1model__calibration_1_1detect__snow__swe_3_01_t_00_01decltype_07_t_1_1snow__swe_00_01void_07_08_08_4.html", null ],
      [ "shyft::time_series::needs_bind_dispatcher< T, std::enable_if_t< std::is_same< decltype(std::declval< T >().needs_bind()), bool >::value > >", "structshyft_1_1time__series_1_1needs__bind__dispatcher_3_01_t_00_01std_1_1enable__if__t_3_01std_4983f16b5680b7076c7efc11dcf4b88a.html", null ]
    ] ],
    [ "shyft::api::ts_bind_info", "structshyft_1_1api_1_1ts__bind__info.html", null ],
    [ "shyft::dtss::ts_db", "structshyft_1_1dtss_1_1ts__db.html", null ],
    [ "shyft::dtss::ts_db_header", "structshyft_1_1dtss_1_1ts__db__header.html", null ],
    [ "shyft::dtss::ts_info", "structshyft_1_1dtss_1_1ts__info.html", null ],
    [ "shyft::time_series::ts_src< TA >", "structshyft_1_1time__series_1_1ts__src.html", null ],
    [ "shyft::core::model_calibration::ts_transform", "structshyft_1_1core_1_1model__calibration_1_1ts__transform.html", null ],
    [ "shyft::api::TsFactory", "structshyft_1_1api_1_1_ts_factory.html", null ],
    [ "shyft::core::time_zone::tz_info< tz >", "structshyft_1_1core_1_1time__zone_1_1tz__info.html", null ],
    [ "shyft::core::time_zone::tz_info< tz_table >", "structshyft_1_1core_1_1time__zone_1_1tz__info_3_01tz__table_01_4.html", null ],
    [ "shyft::core::time_zone::tz_info_database", "structshyft_1_1core_1_1time__zone_1_1tz__info__database.html", null ],
    [ "shyft::core::time_zone::tz_region_def", "structshyft_1_1core_1_1time__zone_1_1tz__region__def.html", null ],
    [ "shyft::core::time_zone::tz_table", "structshyft_1_1core_1_1time__zone_1_1tz__table.html", null ],
    [ "shyft::core::routing::uhg_parameter", "structshyft_1_1core_1_1routing_1_1uhg__parameter.html", null ],
    [ "shyft::time_series::uniform_sum_ts< T >", "structshyft_1_1time__series_1_1uniform__sum__ts.html", null ],
    [ "shyft::core::utcperiod", "structshyft_1_1core_1_1utcperiod.html", null ],
    [ "shyft::core::inverse_distance::wind_speed_model< S, D, P, G >", "structshyft_1_1core_1_1inverse__distance_1_1wind__speed__model.html", null ],
    [ "shyft::experimental::wkt_reader", "classshyft_1_1experimental_1_1wkt__reader.html", null ],
    [ "shyft::qm::wvo_accessor< tsa_t >", "structshyft_1_1qm_1_1wvo__accessor.html", null ],
    [ "shyft::core::YMDhms", "structshyft_1_1core_1_1_y_m_dhms.html", null ],
    [ "shyft::core::YWdhms", "structshyft_1_1core_1_1_y_wdhms.html", null ],
    [ "vector", null, [
      [ "shyft::api::ats_vector", "structshyft_1_1api_1_1ats__vector.html", null ]
    ] ]
];