shyft::core::model_calibration::optimizer
typedef dlib::matrix<double, 0, 1> shyft::core::model_calibration::optimizer< M, PA, PS >::column_vector
dlib optimizer enjoys dlib matrix types.
typedef PS shyft::core::model_calibration::optimizer< M, PA, PS >::target_time_series_t
target_time_series_t. could that be of same type as model calc, always, or is it supplied from outside?
typedef target_specification<PS> shyft::core::model_calibration::optimizer< M, PA, PS >::target_specification_t
describes how to calculate the goal function, maybe better 'retemplate' on this
typedef M shyft::core::model_calibration::optimizer< M, PA, PS >::region_model_t
obvious and Ok template, the region_model, and there is just a few things that we need from this template.
typedef M::state_t shyft::core::model_calibration::optimizer< M, PA, PS >::state_t
typedef M::parameter_t shyft::core::model_calibration::optimizer< M, PA, PS >::parameter_t
typedef M::cell_t shyft::core::model_calibration::optimizer< M, PA, PS >::cell_t
typedef cell_t::response_collector_t shyft::core::model_calibration::optimizer< M, PA, PS >::response_collector_t
PA shyft::core::model_calibration::optimizer< M, PA, PS >::parameter_lower_bound
current setting of parameter lower bound
Referenced by shyft::core::model_calibration::optimizer< M, PA, PS >::active_parameter, shyft::core::model_calibration::optimizer< M, PA, PS >::set_target_specification, shyft::core::model_calibration::optimizer< M, PA, PS >::prepare_optimize, shyft::core::model_calibration::optimizer< M, PA, PS >::set_parameter_ranges.
PA shyft::core::model_calibration::optimizer< M, PA, PS >::parameter_upper_bound
current setting of parameter upper bound
Referenced by shyft::core::model_calibration::optimizer< M, PA, PS >::active_parameter, shyft::core::model_calibration::optimizer< M, PA, PS >::set_target_specification, shyft::core::model_calibration::optimizer< M, PA, PS >::prepare_optimize, shyft::core::model_calibration::optimizer< M, PA, PS >::set_parameter_ranges.
PA& shyft::core::model_calibration::optimizer< M, PA, PS >::parameter_accessor
a reference to the model parameters in the target model, all cells share this!
region_model_t& shyft::core::model_calibration::optimizer< M, PA, PS >::model
a reference to the region model that we optimize
Referenced by shyft::core::model_calibration::optimizer< M, PA, PS >::establish_initial_state_from_model, shyft::core::model_calibration::optimizer< M, PA, PS >::prepare_optimize, shyft::core::model_calibration::optimizer< M, PA, PS >::auto_initial_state_check, shyft::core::model_calibration::optimizer< M, PA, PS >::get_initial_state, shyft::core::model_calibration::optimizer< M, PA, PS >::reset_states.
vector<target_specification_t> shyft::core::model_calibration::optimizer< M, PA, PS >::targets
list of targets ts& catchments indexes to be optimized, used to calculate goal function
Referenced by shyft::core::model_calibration::optimizer< M, PA, PS >::set_target_specification, shyft::core::model_calibration::optimizer< M, PA, PS >::prepare_optimize.
vector<double> shyft::core::model_calibration::optimizer< M, PA, PS >::p_expanded
vector<double> shyft::core::model_calibration::optimizer< M, PA, PS >::p_min
vector<double> shyft::core::model_calibration::optimizer< M, PA, PS >::p_max
int shyft::core::model_calibration::optimizer< M, PA, PS >::print_progress_level
size_t shyft::core::model_calibration::optimizer< M, PA, PS >::n_catchments
optimized counted number of model.catchments available
const double shyft::core::model_calibration::optimizer< M, PA, PS >::activate_limit
friend class calibration_test
bool shyft::core::model_calibration::optimizer< M, PA, PS >::active_parameter(size_t i) const
References shyft::core::model_calibration::optimizer< M, PA, PS >::parameter_upper_bound, shyft::core::model_calibration::optimizer< M, PA, PS >::parameter_lower_bound.
shyft::core::model_calibration::optimizer< M, PA, PS >::optimizer(region_model_t &model, const vector< target_specification_t > &targetsA, const vector< double > &p_min, const vector< double > &p_max)
construct an opt model for ptgsk, use p_min=p_max to disable optimization for a parameter
model reference to the model to be optimized, the model should be initialized, i.e. the interpolation step done. vector<target_specification_t> specifies how to calculate the goal-function, shyft::core::model_calibration::target_specification p_min minimum values for the parameters to be optimized p_max maximum values for the parameters to be optimized
References shyft::core::model_calibration::optimizer< M, PA, PS >::set_parameter_ranges.
shyft::core::model_calibration::optimizer< M, PA, PS >::optimizer(region_model_t &model)
Create an optimizer based on the supplied model, kept as a reference(!) To optimize, first call set_target_specification(), then call any of optimize_xxx(...)
void shyft::core::model_calibration::optimizer< M, PA, PS >::set_target_specification(const vector< target_specification_t > &targetsA, const PA &param_lower_bound, const PA &param_upper_bound)
Set all parameters that matters for the calibration. The lower and upper bounds determines which parameters are subject to calibration. If lower and upper bound are equal, the parameter is untouched during calibration (regardless value) targetsA specifies the goal function description param_lower_bound specifies the lower bound of the parameter set param_upper_bound specifies the upper bound of the parameter set
References shyft::core::model_calibration::optimizer< M, PA, PS >::targets, shyft::core::model_calibration::optimizer< M, PA, PS >::parameter_lower_bound, shyft::core::model_calibration::optimizer< M, PA, PS >::parameter_upper_bound.
void shyft::core::model_calibration::optimizer< M, PA, PS >::establish_initial_state_from_model()
copy the model current state into internal store of the calibration class
References shyft::core::model_calibration::optimizer< M, PA, PS >::model.
Referenced by shyft::core::model_calibration::optimizer< M, PA, PS >::auto_initial_state_check.
void shyft::core::model_calibration::optimizer< M, PA, PS >::prepare_optimize()
prepare the optimization process by looking at the current state of the supplied parameters. Ensures : the model have a global parameter-setthe collection of SCA/SWE is turned on if requestedthe catchment-filter is set according to target-specification request
References shyft::core::model_calibration::optimizer< M, PA, PS >::parameter_lower_bound, shyft::core::model_calibration::optimizer< M, PA, PS >::parameter_upper_bound, shyft::core::model_calibration::optimizer< M, PA, PS >::model, shyft::core::model_calibration::optimizer< M, PA, PS >::targets, shyft::core::model_calibration::DISCHARGE, shyft::core::model_calibration::optimizer< M, PA, PS >::auto_initial_state_check.
Referenced by shyft::core::model_calibration::optimizer< M, PA, PS >::optimize, shyft::core::model_calibration::optimizer< M, PA, PS >::optimize_dream, shyft::core::model_calibration::optimizer< M, PA, PS >::optimize_sceua.
void shyft::core::model_calibration::optimizer< M, PA, PS >::auto_initial_state_check()
References shyft::core::model_calibration::optimizer< M, PA, PS >::model, shyft::core::model_calibration::optimizer< M, PA, PS >::establish_initial_state_from_model.
Referenced by shyft::core::model_calibration::optimizer< M, PA, PS >::prepare_optimize, shyft::core::model_calibration::optimizer< M, PA, PS >::get_initial_state.
state_t shyft::core::model_calibration::optimizer< M, PA, PS >::get_initial_state(size_t idx)
returns the initial state for the i'th cell
References shyft::core::model_calibration::optimizer< M, PA, PS >::auto_initial_state_check, shyft::core::model_calibration::optimizer< M, PA, PS >::model.
vector<double> shyft::core::model_calibration::optimizer< M, PA, PS >::optimize(vector< double > p, size_t max_n_evaluations=1500, double tr_start=0.1, double tr_stop=1.0e-5)
Call to optimize model, starting with p parameter set, using p_min..p_max as boundaries. where p is the full parameter vector. the p_min,p_max specified in constructor is used to reduce the parameterspace for the optimizer down to a minimum number to facilitate fast run.
p contains the starting point for the parameters max_n_evaluations stop after n calls of the objective functions, i.e. simulations. tr_start is the trust region start , default 0.1, ref bobyqa tr_stop is the trust region stop, default 1e-5, ref bobyqa the optimized parameter vector
References shyft::core::model_calibration::optimizer< M, PA, PS >::prepare_optimize, shyft::core::model_calibration::min_bobyqa.
Referenced by shyft::core::model_calibration::optimizer< M, PA, PS >::optimize.
PA shyft::core::model_calibration::optimizer< M, PA, PS >::optimize(const PA &p, size_t max_n_evaluations=1500, double tr_start=0.1, double tr_stop=1.0e-5)
optimize using minbobyqa, using p as starting parameters, return new optimized parameters
References shyft::core::model_calibration::optimizer< M, PA, PS >::optimize.
vector<double> shyft::core::model_calibration::optimizer< M, PA, PS >::optimize_dream(vector< double > p, size_t max_n_evaluations=1500)
Call to optimize model, using DREAM alg., find p, using p_min..p_max as boundaries. where p is the full parameter vector. the p_min,p_max specified in constructor is used to reduce the parameterspace for the optimizer down to a minimum number to facilitate fast run.
p is used as start point (not really, DREAM use random, but we should be able to pass u and q.... max_n_evaluations stop after n calls of the objective functions, i.e. simulations. the optimized parameter vector
References shyft::core::model_calibration::optimizer< M, PA, PS >::prepare_optimize.
Referenced by shyft::core::model_calibration::optimizer< M, PA, PS >::optimize_dream.
PA shyft::core::model_calibration::optimizer< M, PA, PS >::optimize_dream(const PA &p, size_t max_n_evaluations=1500)
optimize using the dream algorithm, returning the new optimized parameter set
References shyft::core::model_calibration::optimizer< M, PA, PS >::optimize_dream.
vector<double> shyft::core::model_calibration::optimizer< M, PA, PS >::optimize_sceua(vector< double > p, size_t max_n_evaluations=1500, double x_eps=0.0001, double y_eps=1.0e-5)
Call to optimize model, using SCE UA, using p as startpoint, find p, using p_min..p_max as boundaries. where p is the full parameter vector. the p_min,p_max specified in constructor is used to reduce the parameterspace for the optimizer down to a minimum number to facilitate fast run.
p is used as start point and is updated with the found optimal points max_n_evaluations stop after n calls of the objective functions, i.e. simulations. x_eps is stop condition when all changes in x's are within this range y_eps is stop condition, and search is stopped when goal function does not improve anymore within this range the optimized parameter vector
References shyft::core::model_calibration::optimizer< M, PA, PS >::prepare_optimize, shyft::core::model_calibration::min_sceua.
Referenced by shyft::core::model_calibration::optimizer< M, PA, PS >::optimize_sceua.
PA shyft::core::model_calibration::optimizer< M, PA, PS >::optimize_sceua(const PA &p, size_t max_n_evaluations=1500, double x_eps=0.0001, double y_eps=1.0e-5)
optimize using the dream algorithm, returning the new optimized parameter set
References shyft::core::model_calibration::optimizer< M, PA, PS >::optimize_sceua.
void shyft::core::model_calibration::optimizer< M, PA, PS >::reset_states()
reset the state of the model to the initial state before starting the run/optimize
References shyft::core::model_calibration::optimizer< M, PA, PS >::model.
void shyft::core::model_calibration::optimizer< M, PA, PS >::set_parameter_ranges(const vector< double > &p_min, const vector< double > &p_max)
set the parameter ranges, set min=max=wanted parameter value for those not subject to change during optimization
References shyft::core::model_calibration::optimizer< M, PA, PS >::parameter_lower_bound, shyft::core::model_calibration::optimizer< M, PA, PS >::parameter_upper_bound.
Referenced by shyft::core::model_calibration::optimizer< M, PA, PS >::optimizer.
void shyft::core::model_calibration::optimizer< M, PA, PS >::set_verbose_level(int level)
double shyft::core::model_calibration::optimizer< M, PA, PS >::calculate_goal_function(std::vector< double > full_vector_of_parameters)
calculate the goal_function as used by minbobyqa, using the full set of parameters vectors (as passed to optimize()) and also ensures that the shyft state/cell/catchment result is consistent with the passed parameters passed
full_vector_of_parameters contains all parameters that will be applied to the run. the goal-function, weigthed nash_sutcliffe sum
Referenced by shyft::core::model_calibration::optimizer< M, PA, PS >::calculate_goal_function.
double shyft::core::model_calibration::optimizer< M, PA, PS >::calculate_goal_function(const PA &p)
compute the goal function with the specified parameter set
References shyft::core::model_calibration::optimizer< M, PA, PS >::calculate_goal_function.
double shyft::core::model_calibration::optimizer< M, PA, PS >::operator()(const column_vector &p_s)
called by bobyqua:
References shyft::core::pt_hs_k::run, shyft::core::model_calibration::optimizer< M, PA, PS >::from_scaled.
double shyft::core::model_calibration::optimizer< M, PA, PS >::operator()(const vector< double > &p_s)
References shyft::core::pt_hs_k::run, shyft::core::model_calibration::optimizer< M, PA, PS >::from_scaled.
vector<double> shyft::core::model_calibration::optimizer< M, PA, PS >::to_scaled(const vector< double > &rp) const
called by bobyqua:reduced parameter space p
vector<double> shyft::core::model_calibration::optimizer< M, PA, PS >::from_scaled(column_vector p_s) const
called by bobyqua: reduced parameter space p
Referenced by shyft::core::model_calibration::optimizer< M, PA, PS >::operator().
vector<double> shyft::core::model_calibration::optimizer< M, PA, PS >::from_scaled(vector< double > p_s) const
called by bobyqua: reduced parameter space p
bool shyft::core::model_calibration::optimizer< M, PA, PS >::is_active_parameter(size_t i) const
vector<double> shyft::core::model_calibration::optimizer< M, PA, PS >::reduce_p_vector(const vector< double > &fp) const
vector<double> shyft::core::model_calibration::optimizer< M, PA, PS >::expand_p_vector(const vector< double > &rp) const
vector<double> shyft::core::model_calibration::optimizer< M, PA, PS >::p_vector(const PA &p) const
PA shyft::core::model_calibration::optimizer< M, PA, PS >::vector_p(const vector< double > &v) const
pts_t shyft::core::model_calibration::optimizer< M, PA, PS >::compute_discharge_sum(const target_specification_t &t, vector< pts_t > &catchment_d) const
vector<area_ts> shyft::core::model_calibration::optimizer< M, PA, PS >::extract_area_ts_property(property_ts_function &&tsf) const
extracts vector of area_ts for all calculated catchments using the given property function tsf that should have signature pts_t (const cell& c)
that this function sum together contributions at cell-level. TODO: Avoid duplicate code, - use average_catchment_feature(*model.cells, catchment_index, []() return c.rc.snow_sca) but it returns a shared_ptr..
pts_t shyft::core::model_calibration::optimizer< M, PA, PS >::compute_weighted_area_ts_average(const target_specification_t &t, const vector< area_ts > &ats) const
returns the area weighted sum of vector<area_ts> according to t.catchment_indexes
enable_if_tx<detect_snow_sca<rc_t>::value, pts_t> shyft::core::model_calibration::optimizer< M, PA, PS >::compute_sca_sum(const target_specification_t &t, vector< area_ts > &catchment_sca) const
enable_if_tx<!detect_snow_sca<rc_t>::value, pts_t> shyft::core::model_calibration::optimizer< M, PA, PS >::compute_sca_sum(const target_specification_t &t, vector< area_ts > &catchment_d) const
enable_if_tx<detect_snow_swe<rc_t>::value, pts_t> shyft::core::model_calibration::optimizer< M, PA, PS >::compute_swe_sum(const target_specification_t &t, vector< area_ts > &catchment_swe) const
enable_if_tx<!detect_snow_swe<rc_t>::value, pts_t> shyft::core::model_calibration::optimizer< M, PA, PS >::compute_swe_sum(const target_specification_t &t, vector< area_ts > &catchment_d) const
double shyft::core::model_calibration::optimizer< M, PA, PS >::run(const vector< double > &rp)
from operator(), called by min_bobyqa, for each iteration, so p is bobyqa parameter vector notice that the function returns the value of the goal function, as specified by the target specification. The flexibility is rather large: It's a set of target-specifications, weighted, where each of them can be a KG or NS, for a specified period/resolution. E.g. we can specify targets that apply to specific catchments, and specified periods/resolutions.