shyft::timeseries::average_accessor
const size_t shyft::timeseries::average_accessor< S, TA >::npos
size_t shyft::timeseries::average_accessor< S, TA >::last_idx
size_t shyft::timeseries::average_accessor< S, TA >::q_idx
double shyft::timeseries::average_accessor< S, TA >::q_value
const TA& shyft::timeseries::average_accessor< S, TA >::time_axis
const S& shyft::timeseries::average_accessor< S, TA >::source
std::shared_ptr<S> shyft::timeseries::average_accessor< S, TA >::source_ref
shyft::timeseries::average_accessor< S, TA >::average_accessor(const S &source, const TA &time_axis)
shyft::timeseries::average_accessor< S, TA >::average_accessor(std::shared_ptr< S > source, const TA &time_axis)
size_t shyft::timeseries::average_accessor< S, TA >::get_last_index() const
double shyft::timeseries::average_accessor< S, TA >::value(const size_t i) const
References shyft::timeseries::average_value, shyft::timeseries::POINT_INSTANT_VALUE.
Referenced by shyft::core::kalman::bias_predictor::update_with_forecast, shyft::core::model_calibration::ts_transform::to_average.
size_t shyft::timeseries::average_accessor< S, TA >::size() const
Referenced by shyft::core::model_calibration::ts_transform::to_average.