shyft::experimental::region_grid
point_xy shyft::experimental::region_grid::p0
2d geo point of "upper left corner"
size_t shyft::experimental::region_grid::nx
number of cells in x direction
size_t shyft::experimental::region_grid::ny
number of cells in y direction
double shyft::experimental::region_grid::dx
distance in meters for the x-side of the cell
double shyft::experimental::region_grid::dy
distance in meters for the y-side of the cell
vector<double> shyft::experimental::region_grid::dtmz
< vector containing all the elevations for the cells, computed index cell(i,j) is i*ny+j
shyft::experimental::region_grid::region_grid(point_xy p0, size_t nx, size_t ny, double dx=1000, double dy=1000)
int shyft::experimental::region_grid::set_dtm(const vector< dtm > &dtminfo)
Referenced by shyft::experimental::repository::cell_file_repository< C >::read.
box shyft::experimental::region_grid::cell_box(size_t i, size_t j) const
return the bounding box of a cell(i,j)
Referenced by shyft::experimental::geo_cell_data_computer::catchment_geo_cell_data.
point_xy shyft::experimental::region_grid::cell_midpoint(size_t i, size_t j)
calculate and return the midpoint of the cell(i,j)
double shyft::experimental::region_grid::dtm_z(size_t i, size_t j) const
return the digital terrain model z coordinate for cell(i,j)
dtm z elevation, or 0.0 if the supplied (i,j) are outside bound
Referenced by shyft::experimental::geo_cell_data_computer::catchment_geo_cell_data.
size_t shyft::experimental::region_grid::n_x() const
returns number of cells in the x direction
Referenced by shyft::experimental::geo_cell_data_computer::catchment_geo_cell_data.
size_t shyft::experimental::region_grid::n_y() const
returns number of cells in the y direction
Referenced by shyft::experimental::geo_cell_data_computer::catchment_geo_cell_data.
size_t shyft::experimental::region_grid::n_cells() const
returns total number of cells, n_x()*n_y()
Referenced by shyft::experimental::geo_cell_data_computer::catchment_geo_cell_data, shyft::experimental::repository::cell_file_repository< C >::read.