shyft::api::apoint_ts
typedef gta_t shyft::api::apoint_ts::ta_t
this is the generic time-axis type for apoint_ts, needed by timeseries namespace templates
std::shared_ptr<ipoint_ts> shyft::api::apoint_ts::ts
a ref to the real implementation, could be a concrete point ts, or an expression
friend struct average_ts
friend struct time_shift_ts
friend struct accumulate_ts
shyft::api::apoint_ts::apoint_ts(const time_axis::fixed_dt &ta, double fill_value, point_interpretation_policy point_fx=POINT_INSTANT_VALUE)
shyft::api::apoint_ts::apoint_ts(const time_axis::fixed_dt &ta, const std::vector< double > &values, point_interpretation_policy point_fx=POINT_INSTANT_VALUE)
shyft::api::apoint_ts::apoint_ts(const time_axis::point_dt &ta, double fill_value, point_interpretation_policy point_fx=POINT_INSTANT_VALUE)
shyft::api::apoint_ts::apoint_ts(const time_axis::point_dt &ta, const std::vector< double > &values, point_interpretation_policy point_fx=POINT_INSTANT_VALUE)
shyft::api::apoint_ts::apoint_ts(const rts_t &rts)
shyft::api::apoint_ts::apoint_ts(const vector< double > &pattern, utctimespan dt, const time_axis::generic_dt &ta)
shyft::api::apoint_ts::apoint_ts(const vector< double > &pattern, utctimespan dt, utctime pattern_t0, const time_axis::generic_dt &ta)
shyft::api::apoint_ts::apoint_ts(const gta_t &ta, double fill_value, point_interpretation_policy point_fx=POINT_INSTANT_VALUE)
shyft::api::apoint_ts::apoint_ts(const gta_t &ta, const std::vector< double > &values, point_interpretation_policy point_fx=POINT_INSTANT_VALUE)
shyft::api::apoint_ts::apoint_ts(const gta_t &ta, std::vector< double > &&values, point_interpretation_policy point_fx=POINT_INSTANT_VALUE)
shyft::api::apoint_ts::apoint_ts(gta_t &&ta, std::vector< double > &&values, point_interpretation_policy point_fx=POINT_INSTANT_VALUE)
shyft::api::apoint_ts::apoint_ts(gta_t &&ta, double fill_value, point_interpretation_policy point_fx=POINT_INSTANT_VALUE)
shyft::api::apoint_ts::apoint_ts(const std::shared_ptr< ipoint_ts > &c)
shyft::api::apoint_ts::apoint_ts()
Referenced by partition_by.
shyft::api::apoint_ts::apoint_ts(const apoint_ts &c)
shyft::api::apoint_ts::apoint_ts(apoint_ts &&c)
apoint_ts& shyft::api::apoint_ts::operator=(const apoint_ts &c)
apoint_ts& shyft::api::apoint_ts::operator=(apoint_ts &&c)
bool shyft::api::apoint_ts::operator==(const apoint_ts &other) const
Easy to compare for equality, but tricky if performance needed.
point_interpretation_policy shyft::api::apoint_ts::point_interpretation() const
Referenced by shyft::api::abin_op_ts::abin_op_ts, shyft::api::abin_op_scalar_ts::abin_op_scalar_ts, shyft::api::abin_op_ts_scalar::abin_op_ts_scalar.
void shyft::api::apoint_ts::set_point_interpretation(point_interpretation_policy point_interpretation)
const gta_t& shyft::api::apoint_ts::time_axis() const
Referenced by shyft::api::abin_op_ts::abin_op_ts, shyft::api::abin_op_scalar_ts::abin_op_scalar_ts, shyft::api::abin_op_ts_scalar::abin_op_ts_scalar.
utcperiod shyft::api::apoint_ts::total_period() const
size_t shyft::api::apoint_ts::index_of(utctime t) const
Returns period that covers points, given.
size_t shyft::api::apoint_ts::size() const
utctime shyft::api::apoint_ts::time(size_t i) const
number of points that descr. y=f(t) on t ::= period
double shyft::api::apoint_ts::value(size_t i) const
get the i'th time point
double shyft::api::apoint_ts::operator()(utctime t) const
get the i'th value
std::vector<double> shyft::api::apoint_ts::values() const
apoint_ts shyft::api::apoint_ts::average(const gta_t &ta) const
References shyft::api::average.
apoint_ts shyft::api::apoint_ts::accumulate(const gta_t &ta) const
References shyft::api::accumulate.
apoint_ts shyft::api::apoint_ts::time_shift(utctimespan dt) const
References shyft::api::time_shift.
apoint_ts shyft::api::apoint_ts::max(double a) const
References shyft::api::max.
apoint_ts shyft::api::apoint_ts::min(double a) const
References shyft::api::min.
apoint_ts shyft::api::apoint_ts::max(const apoint_ts &other) const
References shyft::api::max.
apoint_ts shyft::api::apoint_ts::min(const apoint_ts &other) const
References shyft::api::min.
std::vector< apoint_ts > shyft::api::apoint_ts::partition_by(const calendar &cal, utctime t, utctimespan partition_interval, size_t n_partitions, utctime common_t0) const
References apoint_ts.
point shyft::api::apoint_ts::get(size_t i) const
void shyft::api::apoint_ts::set(size_t i, double x)
References shyft::api::gpoint_ts::set.
void shyft::api::apoint_ts::fill(double x)
References shyft::api::gpoint_ts::fill.
void shyft::api::apoint_ts::scale_by(double x)
References shyft::api::gpoint_ts::scale_by.
apoint_ts shyft::api::apoint_ts::max(const apoint_ts &a, const apoint_ts &b)
References shyft::api::max.
apoint_ts shyft::api::apoint_ts::min(const apoint_ts &a, const apoint_ts &b)
References shyft::api::min.