shyft::core::kirchner::calculator
typedef double shyft::core::kirchner::calculator< AC, P >::state_type
typedef boost::numeric::odeint::result_of::make_dense_output< boost::numeric::odeint::runge_kutta_dopri5<state_type> >::type shyft::core::kirchner::calculator< AC, P >::dense_stepper_type
typedef std::pair<dense_stepper_type::time_type, dense_stepper_type::time_type> shyft::core::kirchner::calculator< AC, P >::interval_type
dense_stepper_type shyft::core::kirchner::calculator< AC, P >::dense_stepper
AC<dense_stepper_type> shyft::core::kirchner::calculator< AC, P >::average_computer
const P shyft::core::kirchner::calculator< AC, P >::param
double shyft::core::kirchner::calculator< AC, P >::g(double ln_q) const
Sensitivity function g(q)
The sensitivity function expresses the sensitivity of discharge to changes in the storage. As the changes is the storage can be expressed as a (pure) function of q, it can be estimated from observational data (p, e, and q).
double shyft::core::kirchner::calculator< AC, P >::log_transform_f(double ln_q, double p, double e) const
Log transform of equation 18 in Kirchner, aka equation 19.
When solving the Kirchner model, the log transform formulation is desireable due to numercial instabilities of the original formulation, $\frac{dQ}{dt} = g(Q)(P-E-Q)$.
shyft::core::kirchner::calculator< AC, P >::calculator(const P &param)
shyft::core::kirchner::calculator< AC, P >::calculator(double abs_err, double rel_err, const P &param)
void shyft::core::kirchner::calculator< AC, P >::step(shyft::timeseries::utctime T0, shyft::timeseries::utctime T1, double &q, double &q_avg, double p, double e)
step Kirchner model forward from time t0 to time t1
If the supplied q (state) is less than min_q(0.00001, it represents mm water..), it is forced to min_q to ensure numerical stability
References shyft::core::deltahours.
Referenced by shyft::core::pt_gs_k::run_pt_gs_k, shyft::core::pt_hs_k::run, shyft::core::pt_ss_k::run.