shyft::core::time_zone::tz_table
int shyft::core::time_zone::tz_table::start_year
string shyft::core::time_zone::tz_table::tz_name
vector<utcperiod> shyft::core::time_zone::tz_table::dst
vector<utctimespan> shyft::core::time_zone::tz_table::dt
shyft::core::time_zone::tz_table::tz_table(const Tz &tz, int start_year=1905, size_t n_years=200)
construct a tz_table using a information from provided Tz adapter
Tz a type that provids dst_start(year),dst_end(year), dst_offset(year) tz const ref to provide tz information that will be used to construct a table driven interpretation start_year default 1905 (limit of posix time is 1901) for which the dst table is constructed n_years default 200 giving range from 1905 to 2105 with dst info.
shyft::core::time_zone::tz_table::tz_table(utctimespan dt)
construct a simple dst infotable with no dst, just tz-offset suitable for non-dst time-zones and data-exchange.
dt of type utctimespan, positive for tz east of GMT
References shyft::core::deltahours.
bool shyft::core::time_zone::tz_table::is_dst() const
string shyft::core::time_zone::tz_table::name() const
Referenced by shyft::core::time_zone::tz_info< tz_table >::name.
utctime shyft::core::time_zone::tz_table::dst_start(int year) const
References shyft::core::no_utctime.
utctime shyft::core::time_zone::tz_table::dst_end(int year) const
References shyft::core::no_utctime.
utctimespan shyft::core::time_zone::tz_table::dst_offset(utctime t) const
References shyft::core::calendar::utc_year.
Referenced by shyft::core::time_zone::tz_info< tz_table >::utc_offset, shyft::core::time_zone::tz_info< tz_table >::is_dst.