shyft::experimental::wkt_reader
vector<string> shyft::experimental::wkt_reader::reported_errors
contains accumulated errors after calls to read_xxx
Referenced by shyft::experimental::repository::cell_file_repository< C >::read, shyft::experimental::repository::geo_located_ts_file_repository::read.
void shyft::experimental::wkt_reader::report_error(string report_tag, int line_no, string msg)
internally used to collect errors, using report_tag to easy locate errors in files|file-types
vector<dtm> shyft::experimental::wkt_reader::read_dtm(string report_tag, string s)
given string s containing txt formatted as dtm(box(point(),point()),z) , convert it to a vector<dtm> dtm
Referenced by shyft::experimental::repository::cell_file_repository< C >::read.
multi_polygon_ shyft::experimental::wkt_reader::read(string report_tag, string s)
Given string s with wkt formatted multi_polygons, convert the lines into a multi_polygon.
supports ! as comment in the format
References shyft::core::is_valid.
Referenced by shyft::experimental::repository::cell_file_repository< C >::read.
multi_point_ shyft::experimental::wkt_reader::read_points(string report_tag, string s)
given string s formatted with wkt point structures, read from the string into a multipoint
Referenced by shyft::experimental::repository::cell_file_repository< C >::read.
map<int,multi_polygon_> shyft::experimental::wkt_reader::read_catchment_map(string report_tag, string s)
given string formatted as id:wkt multipolygon, read and convert the string to a map<id,multi_polygon_>
References shyft::core::is_valid.
Referenced by shyft::experimental::repository::cell_file_repository< C >::read.
map<int,observation_location> shyft::experimental::wkt_reader::read_geo_point_map(string report_tag, string s)
given string s formatted as id:name:POINT(x,y,z), convert it to a map<id,observation_location> used to ensure that locations (x,y,z) associated with observation time-series have consistent location info
References shyft::experimental::observation_location::name, shyft::experimental::observation_location::point, shyft::core::geo_point::x, shyft::core::geo_point::y, shyft::core::geo_point::z.
Referenced by shyft::experimental::repository::geo_located_ts_file_repository::read.
geo_xts_t shyft::experimental::wkt_reader::read_geo_xts_t(string report_tag, function< ec::geo_point(int)> to_geo_point, const string &s)
given string formatted as 'geo-id-located ts', read it and convert it to a geo_xts_t used to read time-series for nea-nidelv and similar cases
References shyft::core::geo_point_ts< T >::location, shyft::core::calendar::time, shyft::core::max_utctime, shyft::core::geo_point_ts< T >::ts.
Referenced by shyft::experimental::io::load_from_directory.