shyft
const double shyft::nan
Referenced by shyft::api::abin_op_ts::value_at, shyft::api::percentiles, shyft::api::abin_op_ts::value, shyft::api::extend_ts::value_at, shyft::api::extend_ts::value, shyft::core::environment< timeaxis, temperature_ts, precipitation_ts, radiation_ts, relhum_ts, windspeed_ts >::init, shyft::core::ts_init, shyft::dtss::ts_db::find, shyft::prediction::krls_rbf_predictor::mse_ts, shyft::time_series::accumulate_value, shyft::time_series::average_value, shyft::time_series::point_ts< time_axis::fixed_dt >::operator(), shyft::time_series::average_ts< TS, TA >::operator(), shyft::time_series::profile_description::operator(), shyft::time_series::glacier_melt_ts< std::shared_ptr< shyft::api::ipoint_ts > >::value, shyft::time_series::glacier_melt_ts< std::shared_ptr< shyft::api::ipoint_ts > >::operator(), shyft::time_series::convolve_w_ts< apoint_ts >::value, shyft::time_series::uniform_sum_ts< T >::value, shyft::time_series::bin_op< A, B, O, TA >::operator(), shyft::time_series::bin_op< A, B, O, TA >::value, shyft::time_series::rating_curve_function::flow, shyft::time_series::rating_curve_parameters::flow, shyft::time_series::average_accessor< S, TA >::value, shyft::time_series::accumulate_accessor< S, TA >::value, shyft::api::average_ts::value, shyft::api::average_ts::value_at, shyft::api::integral_ts::value, shyft::api::integral_ts::value_at, shyft::api::accumulate_ts::value, shyft::api::accumulate_ts::value_at, shyft::time_series::nash_sutcliffe, shyft::qm::quantile_mapping, shyft::time_series::extract_statistics.
const double shyft::mmh_to_m3s_scale_factor
Referenced by mmh_to_m3s.
double shyft::mmh_to_m3s(double mm_pr_hour, double area_m2)
convert [mm/h] over an area_m^2 to [m^3/s] units
References mmh_to_m3s_scale_factor.
Referenced by shyft::core::hbv_stack::run_hbv_stack, shyft::core::hbv_stack::all_response_collector::collect, shyft::core::hbv_stack::discharge_collector::collect, shyft::core::pt_gs_k::run_pt_gs_k, shyft::core::pt_gs_k::all_response_collector::collect, shyft::core::pt_gs_k::discharge_collector::collect, shyft::core::pt_gs_k::state_collector::collect, shyft::core::pt_hs_k::run, shyft::core::pt_hs_k::all_response_collector::collect, shyft::core::pt_hs_k::discharge_collector::collect, shyft::core::pt_hs_k::state_collector::collect, shyft::core::pt_ss_k::run, shyft::core::pt_ss_k::all_response_collector::collect, shyft::core::pt_ss_k::discharge_collector::collect, shyft::core::pt_ss_k::state_collector::collect.
double shyft::m3s_to_mmh(double m3s, double area_m2)
convert [m^3/s] to [mm/h] over area_m^2
Referenced by shyft::core::hbv_stack::run_hbv_stack, shyft::core::pt_gs_k::run_pt_gs_k, shyft::core::pt_hs_k::run, shyft::core::pt_ss_k::run.