shyft::core
typedef shyft::time_series::point_ts< shyft::time_axis::fixed_dt > shyft::core::pts_t
typedef constant_timeseries<time_axis::fixed_dt> shyft::core::cts_t
typedef time_axis::fixed_dt shyft::core::timeaxis_t
typedef environment<timeaxis_t, pts_t, pts_t, pts_t, cts_t, cts_t> shyft::core::environment_const_rhum_and_wind_t
environment type with all properties as general time_series
typedef environment<timeaxis_t, pts_t, pts_t, pts_t, pts_t, pts_t> shyft::core::environment_t
utility function to create an instance of a environment based on function (auto-template by arguments)
typedef long shyft::core::utctime
utctime basic types for time handling we use linear time, i.e. time is just a number on the timeaxis, utc. Timeaxis zero is at 1970-01-01 00:00:00 (unix time). resolution is 1 second, integer. also define min max and no_utctime
The advantage with the definition is that it is well defined and commonly known in all platforms Also considered: moving to std::chrono, would enable a strict time arithmetic regime, of little advantage in this context, and at the cost of compile time (also consider the python/api part).
typedef long shyft::core::utctimespan
time_t is typedef'd as a __time64_t, which is an __int64., happens to be equal to EnkiTime
const double shyft::core::default_radiation_slope_factor
int shyft::core::mq[12][12]
const utctime shyft::core::max_utctime
max_utctime represent the maximum utctime
Referenced by shyft::dtss::ts_db::find, shyft::experimental::wkt_reader::read_geo_xts_t, shyft::time_axis::fixed_dt::full_range, shyft::core::calendar::to_string, shyft::core::calendar::time, shyft::core::calendar::calendar_units, shyft::core::calendar::calendar_week_units, shyft::core::calendar::day_of_week, shyft::core::calendar::day_of_year, shyft::core::calendar::month, shyft::core::calendar::quarter, shyft::core::calendar::trim.
const utctime shyft::core::min_utctime
max 64bit int
min_utctime represent the minimum utctime (equal to -max_utctime)
Referenced by shyft::dtss::ts_db::find, shyft::time_axis::fixed_dt::total_period, shyft::time_axis::fixed_dt::full_range, shyft::time_axis::calendar_dt::total_period, shyft::time_axis::point_dt::total_period, shyft::time_axis::period_list::total_period, shyft::core::calendar::to_string, shyft::core::calendar::time, shyft::core::calendar::calendar_units, shyft::core::calendar::calendar_week_units, shyft::core::calendar::day_of_week, shyft::core::calendar::day_of_year, shyft::core::calendar::month, shyft::core::calendar::quarter, shyft::core::calendar::trim.
const utctime shyft::core::no_utctime
min 64bit int
no_utctime represents 'NaN' time, null time, not valid time
Referenced by shyft::dtss::ts_db::find, shyft::time_axis::point_dt::point_dt, shyft::api::ats_vector::max, shyft::core::calendar::to_string, shyft::core::calendar::time, shyft::core::calendar::calendar_units, shyft::core::calendar::calendar_week_units, shyft::core::calendar::day_of_week, shyft::core::calendar::day_of_year, shyft::core::calendar::month, shyft::core::calendar::quarter, shyft::core::calendar::trim, shyft::core::calendar::diff_units, is_valid, shyft::core::time_zone::tz_table::dst_start, shyft::core::time_zone::tz_table::dst_end.
environment<timeaxis, temperature_ts, precipitation_ts, radiation_ts, relhum_ts, windspeed_ts> shyft::core::create_cell_environment(temperature_ts temp, precipitation_ts prec, radiation_ts rad, relhum_ts rhum, windspeed_ts ws)
void shyft::core::ts_init(pts_t &ts, time_axis::fixed_dt const &ta, int start_step, int n_steps, ts_point_fx fx_policy)
Utility function used to initialize a pts_t in the core, typically making space, fill a ts prior to a run to ensure values are zero
References shyft::nan, shyft::time_series::point_ts< TA >::ta, shyft::time_axis::fixed_dt::size, shyft::time_series::point_ts< TA >::fill_range.
Referenced by shyft::core::hbv_stack::all_response_collector::initialize, shyft::core::hbv_stack::discharge_collector::initialize, shyft::core::hbv_stack::state_collector::initialize, shyft::core::pt_gs_k::all_response_collector::initialize, shyft::core::pt_gs_k::discharge_collector::initialize, shyft::core::pt_gs_k::state_collector::initialize, shyft::core::pt_hs_k::all_response_collector::initialize, shyft::core::pt_hs_k::discharge_collector::initialize, shyft::core::pt_hs_k::state_collector::initialize, shyft::core::pt_ss_k::all_response_collector::initialize, shyft::core::pt_ss_k::discharge_collector::initialize, shyft::core::pt_ss_k::state_collector::initialize.
std::ostream& shyft::core::operator<<(std::ostream &os, const utcperiod &p)
References shyft::core::utcperiod::to_string.
static int shyft::core::day_of_week_idx(YMDhms const &c)
static int shyft::core::iso_week_day(YMDhms const &c)
static unsigned long shyft::core::trim_day_number_to_week(unsigned long jdn)
static C& shyft::core::fill_in_hms_from_t(utctime t, C &r)
utctimespan shyft::core::deltahours(int n)
utctimespan is typdedef'd as a utctime (thus __int64)
deltahours n number of hours utctimespan representing number of hours specified
Referenced by shyft::dtss::ts_db::find, shyft::core::kalman::filter::fold_to_daily_observation, shyft::core::kalman::bias_predictor::compute_running_bias, shyft::core::kirchner::calculator< AC, P >::step, shyft::time_series::forecast_merge, shyft::core::calendar::to_string, shyft::core::time_zone::tz_table::tz_table.
utctimespan shyft::core::deltaminutes(int n)
deltaminutes
n number of minutes utctimespan representing number of minutes specified
Referenced by shyft::core::calendar::to_string.
utctime shyft::core::utctime_now()
Nonvalid.
utctimeNow, utctime_now() current systemclock utctime
bool shyft::core::is_valid(utctime t)
References no_utctime.
Referenced by shyft::api::quantile_map_forecast, shyft::experimental::wkt_reader::read, shyft::experimental::wkt_reader::read_catchment_map, shyft::qm::quantile_mapping, shyft::core::utcperiod::contains, shyft::core::YMDhms::YMDhms, shyft::core::YWdhms::YWdhms.
bool shyft::core::is_valid(const utcperiod &p)
References shyft::core::utcperiod::valid.
utcperiod shyft::core::intersection(const utcperiod &a, const utcperiod &b)
References shyft::time_series::max, shyft::core::utcperiod::start, shyft::time_series::min, shyft::core::utcperiod::end, shyft::core::utcperiod::utcperiod.
Referenced by shyft::experimental::geo_cell_data_computer::catchment_geo_cell_data, shyft::time_axis::combine.