shyft::time_axis
bool shyft::time_axis::equivalent_time_axis(const A &a, const B &b)
generic test if two different time-axis types resembles the same conceptual time-axisGiven time-axis are of differnt types (point, versus period versus fixed_dt etc.) just compare and see if they produces the same number of periods, and that each period is equal.
Referenced by shyft::time_axis::generic_dt::operator==.
bool shyft::time_axis::equivalent_time_axis(const A &a, const A &b)
Specialization of the equivalent_time_axis given that they are of the same type. In this case we forward the comparison to the type it self relying on the fact that the time_axis it self knows how to fastest figure out if it's equal.
fixed_dt shyft::time_axis::time_shift(const fixed_dt &src, utctimespan dt)
create a new time-shifted dt time-axis
References shyft::time_axis::fixed_dt::t, shyft::time_axis::fixed_dt::dt, shyft::time_axis::fixed_dt::n.
Referenced by time_shift, shyft::time_series::time_shift_ts< Ts >::do_bind, shyft::api::time_shift_ts::local_do_bind.
calendar_dt shyft::time_axis::time_shift(const calendar_dt &src, utctimespan dt)
create a new time-shifted dt time-axis
References shyft::time_axis::calendar_dt::t.
point_dt shyft::time_axis::time_shift(const point_dt &src, utctimespan dt)
create a new time-shifted dt time-axis
References shyft::time_axis::point_dt::t, shyft::time_axis::point_dt::t_end.
generic_dt shyft::time_axis::time_shift(const generic_dt &src, utctimespan dt)
create a new time-shifted dt time-axis
References shyft::time_axis::generic_dt::gt, shyft::time_axis::generic_dt::FIXED, time_shift, shyft::time_axis::generic_dt::f, shyft::time_axis::generic_dt::CALENDAR, shyft::time_axis::generic_dt::c, shyft::time_axis::generic_dt::p.
generic_dt shyft::time_axis::extend(const fixed_dt &a, const fixed_dt &b, const utctime split_at)
Extend time-axis a with time-axis b.
Values are only added after time-axis a, never inside. a Time-axis to extend. b Time-axis to extend. split_at Time-point to split between a and b. If at a interval boundary in a the interval is not included. If inside a interval in a the interval is included. If at a interval boundary in b the interval is included. If inside a interval in b the interval is not included.
References shyft::time_axis::fixed_dt::total_period, shyft::time_axis::fixed_dt::size, shyft::time_axis::fixed_dt::null_range, shyft::time_axis::fixed_dt::index_of, shyft::core::utcperiod::start, shyft::time_axis::fixed_dt::period, shyft::time_axis::fixed_dt::dt, shyft::time_series::min, shyft::time_series::max, shyft::core::utcperiod::end, shyft::time_axis::point_dt::null_range.
Referenced by extend, shyft::api::extend_ts::local_do_bind.
generic_dt shyft::time_axis::extend(const calendar_dt &a, const calendar_dt &b, const utctime split_at)
References shyft::time_axis::calendar_dt::total_period, shyft::time_axis::calendar_dt::size, shyft::time_axis::calendar_dt::null_range, shyft::time_axis::calendar_dt::index_of, shyft::core::utcperiod::start, shyft::time_axis::calendar_dt::period, shyft::time_axis::calendar_dt::get_calendar, shyft::time_axis::calendar_dt::dt, shyft::core::utcperiod::end, shyft::time_axis::calendar_dt::cal, shyft::time_axis::point_dt::null_range.
auto shyft::time_axis::extend(const TA &a, const TB &b, const utctime split_at) -> typename std::enable_if< TA::continuous::value &&TB::continuous::value, generic_dt >::type
References shyft::core::utcperiod::start, shyft::time_axis::point_dt::null_range, shyft::core::utcperiod::end, extend.
generic_dt shyft::time_axis::extend(const generic_dt &a, const generic_dt &b, const utctime split_at)
References shyft::time_axis::generic_dt::gt, shyft::time_axis::generic_dt::FIXED, extend, shyft::time_axis::generic_dt::f, shyft::time_axis::generic_dt::CALENDAR, shyft::time_axis::generic_dt::c, shyft::time_axis::generic_dt::p.
fixed_dt shyft::time_axis::combine(const fixed_dt &a, const fixed_dt &b)
fast&efficient combine for two fixed_dt time-axis
References shyft::time_axis::fixed_dt::total_period, shyft::core::utcperiod::overlaps, shyft::time_axis::fixed_dt::size, shyft::time_axis::fixed_dt::null_range, shyft::time_axis::fixed_dt::dt, shyft::time_axis::fixed_dt::t, shyft::time_axis::fixed_dt::n, shyft::time_series::max, shyft::core::utcperiod::start, shyft::time_series::min, shyft::core::utcperiod::end.
Referenced by combine, shyft::time_series::bin_op< A, B, O, TA >::do_bind, shyft::api::abin_op_ts::local_do_bind.
generic_dt shyft::time_axis::combine(const TA &a, const TB &b, typename enable_if< TA::continuous::value &&TB::continuous::value >::type *x=0)
combine continuous (time-axis,time-axis) template for combining any continuous time-axis with another continuous time-axis
this could have potentially linear cost of n-points
References shyft::core::utcperiod::overlaps, shyft::time_axis::point_dt::null_range, shyft::time_series::max, shyft::core::utcperiod::start, shyft::time_series::min, shyft::core::utcperiod::end, shyft::time_axis::point_dt::t, shyft::time_axis::point_dt::t_end.
generic_dt shyft::time_axis::combine(const generic_dt &a, const generic_dt &b)
ensure generic_dt optimizes fixed-interval cases
References shyft::time_axis::generic_dt::gt, shyft::time_axis::generic_dt::FIXED, combine, shyft::time_axis::generic_dt::f, shyft::time_axis::generic_dt::CALENDAR, shyft::time_axis::generic_dt::c, shyft::time_axis::generic_dt::POINT, shyft::time_axis::generic_dt::p.
period_list shyft::time_axis::combine(const TA &a, const TB &b, typename enable_if< !TA::continuous::value||!TB::continuous::value >::type *x=0)
TODO write the combine sparse time-axis algorithm for calendar_p_dt and period-list. period_list+period_list -> period_list.
References shyft::core::utcperiod::overlaps, shyft::time_axis::period_list::null_range, shyft::time_axis::period_list::convert, shyft::time_series::max, shyft::core::utcperiod::start, shyft::time_series::min, shyft::core::utcperiod::end, shyft::time_axis::period_list::p, shyft::core::intersection, shyft::core::utcperiod::timespan, shyft::core::utcperiod::contains.
size_t shyft::time_axis::ta_index_of(TA const &ta, utctime t, size_t ix_hint)
Referenced by shyft::time_axis::time_axis_map< TA1, TA2 >::src_index.
size_t shyft::time_axis::ta_index_of(time_axis::point_dt const &ta, utctime t, size_t ix_hint)
References shyft::time_axis::point_dt::index_of.
size_t shyft::time_axis::ta_index_of(time_axis::generic_dt const &ta, utctime t, size_t ix_hint)
References shyft::time_axis::generic_dt::index_of.
auto shyft::time_axis::make_time_axis_map(TA1 const &src, TA2 const &m)
auto-deduce a time-axis transform adapted to the time-axis that we have
Referenced by shyft::time_series::extract_statistics.
bool shyft::time_axis::continuous_merge(const utcperiod &a, const utcperiod &b)
returns true if the period a and be union can be one continuous period
References shyft::core::utcperiod::end, shyft::core::utcperiod::start.
Referenced by can_merge, compute_merge_info.
bool shyft::time_axis::equal_calendars(const shared_ptr< calendar > &a, const shared_ptr< calendar > &b)
return true if a calendars are reference equal or have same name
Referenced by can_merge.
bool shyft::time_axis::can_merge(const fixed_dt &a, const fixed_dt &b)
return true if fixed time-axis a and b can be merged into one time-axis
References shyft::time_axis::fixed_dt::dt, shyft::time_axis::fixed_dt::n, continuous_merge, shyft::time_axis::fixed_dt::total_period.
Referenced by can_merge, merge, shyft::time_series::merge.
bool shyft::time_axis::can_merge(const calendar_dt &a, const calendar_dt &b)
return true if calendar time-axis a and b can be merged into one time-axis
References shyft::time_axis::calendar_dt::dt, shyft::time_axis::calendar_dt::n, equal_calendars, shyft::time_axis::calendar_dt::cal, continuous_merge, shyft::time_axis::calendar_dt::total_period.
bool shyft::time_axis::can_merge(const point_dt &a, const point_dt &b)
return true if point time-axis a and b can be merged into one time-axis
References continuous_merge, shyft::time_axis::point_dt::total_period.
bool shyft::time_axis::can_merge(const generic_dt &a, const generic_dt &b)
return true if generic time-axis a and b can be merged into one time-axis
References shyft::time_axis::generic_dt::gt, shyft::time_axis::generic_dt::FIXED, can_merge, shyft::time_axis::generic_dt::f, shyft::time_axis::generic_dt::CALENDAR, shyft::time_axis::generic_dt::c, shyft::time_axis::generic_dt::POINT, shyft::time_axis::generic_dt::p.
merge_info shyft::time_axis::compute_merge_info(const TA &a, const TA &b)
computes the merge-info for two time-axisto enable easy and consistent time-series merge operations.
References continuous_merge, shyft::time_axis::merge_info::b_n, shyft::time_axis::merge_info::a_i, shyft::time_axis::merge_info::a_n, shyft::time_axis::merge_info::t_end.
Referenced by merge, shyft::time_series::merge.
fixed_dt shyft::time_axis::merge(const fixed_dt &a, const fixed_dt &b, const merge_info &m)
merge time-axis a and b into one. require a.dt equal to b.dt and that the two axis covers a contiguous period
References shyft::time_axis::fixed_dt::total_period, shyft::time_series::min, shyft::time_series::max, shyft::time_axis::fixed_dt::start, shyft::time_axis::fixed_dt::dt, shyft::time_axis::fixed_dt::size, shyft::time_axis::merge_info::size.
Referenced by shyft::dtss::apoint_ts_frag::merge, merge, shyft::time_series::merge.
calendar_dt shyft::time_axis::merge(const calendar_dt &a, const calendar_dt &b, const merge_info &m)
merge time-axis a and b into one. require a.dt equal to b.dt, and same calendar (tz-id) and that the two axis covers a contiguous period
References shyft::time_axis::calendar_dt::total_period, shyft::time_series::min, shyft::time_series::max, shyft::time_axis::calendar_dt::cal, shyft::time_axis::calendar_dt::dt, shyft::time_axis::calendar_dt::size, shyft::time_axis::merge_info::size.
vector<T> shyft::time_axis::merge(const vector< T > &a, const vector< T > &b, const merge_info &m)
merge value-vector from two time-series a and b using merge_info
References shyft::time_axis::merge_info::size, shyft::time_axis::merge_info::b_n, shyft::time_axis::merge_info::a_n, shyft::time_axis::merge_info::a_i.
point_dt shyft::time_axis::merge(const point_dt &a, const point_dt &b, const merge_info &m)
merge time-axis a and b into one using merge_info. require a validated merg_info for a and b a new point_dt where the points are all points of a, plus points of b not covered by a
References merge, shyft::time_axis::point_dt::t, shyft::time_axis::merge_info::t_end.
generic_dt shyft::time_axis::merge(const generic_dt &a, const generic_dt &b, const merge_info &m)
References shyft::time_axis::generic_dt::gt, shyft::time_axis::generic_dt::FIXED, merge, shyft::time_axis::generic_dt::f, compute_merge_info, shyft::time_axis::generic_dt::CALENDAR, shyft::time_axis::generic_dt::c, shyft::time_axis::generic_dt::POINT.
TA shyft::time_axis::merge(const TA &a, const TA &b)
simple template that merges two equally typed time-seriesthe merged time-series, or throws if not compatible
References can_merge, merge, compute_merge_info, x_serialize_export_key.