shyft::timeseries
point_interpretation_policy
the point value represents the value at the specific time (or centered around that time),typically linear accessor
typedef shyft::time_axis::fixed_dt shyft::timeseries::timeaxis
typedef time_axis::point_dt shyft::timeseries::point_timeaxis
typedef point_interpretation_policy shyft::timeseries::fx_policy_t
const double shyft::timeseries::EPS
Referenced by operator==.
bool shyft::timeseries::operator==(const point &a, const point &b)
point a and b are considered equal if same time t and value-diff less than EPS
References shyft::timeseries::point::t, shyft::timeseries::point::v, EPS.
point_interpretation_policy shyft::timeseries::result_policy(point_interpretation_policy a, point_interpretation_policy b)
References POINT_INSTANT_VALUE, POINT_AVERAGE_VALUE.
Referenced by shyft::timeseries::bin_op< A, B, O, TA >::bin_op, shyft::api::abin_op_ts::abin_op_ts.
const U& shyft::timeseries::d_ref(const std::shared_ptr< U > &p)
d_ref function to d_ref object or shared_ptr
The T d_ref(T) template to return a ref or const ref to T, if T is shared_ptr<T> or just T
Referenced by shyft::timeseries::average_ts< TS, TA >::value, shyft::timeseries::accumulate_ts< TS, TA >::value, shyft::timeseries::accumulate_ts< TS, TA >::operator(), shyft::timeseries::bin_op< A, B, O, TA >::bin_op, shyft::timeseries::bin_op< A, B, O, TA >::operator(), shyft::timeseries::bin_op< double, B, O, TA >::bin_op, shyft::timeseries::bin_op< double, B, O, TA >::operator(), shyft::timeseries::bin_op< double, B, O, TA >::value, shyft::timeseries::bin_op< A, double, O, TA >::bin_op, shyft::timeseries::bin_op< A, double, O, TA >::operator(), shyft::timeseries::bin_op< A, double, O, TA >::value.
const U& shyft::timeseries::d_ref(const U &u)
d_ref_t template to rip out T of shared_ptr<T> or T if T specified
time_shift_ts<typename std::decay<Ts>::type > shyft::timeseries::time_shift(Ts &&ts, utctimespan dt)
time_shift function, to ease syntax and usability
auto shyft::timeseries::operator+(const A &lhs, const B &rhs)
auto shyft::timeseries::operator-(const A &lhs, const B &rhs)
auto shyft::timeseries::operator-(const A &lhs)
unary minus implemented as -1.0* ts
auto shyft::timeseries::operator*(const A &lhs, const B &rhs)
auto shyft::timeseries::operator/(const A &lhs, const B &rhs)
auto shyft::timeseries::max(const A &lhs, const B &rhs)
Referenced by shyft::core::optimizer::dream::find_max, shyft::core::gamma_snow::calculator< P, S, R >::step, shyft::core::land_type_fractions::land_type_fractions, shyft::core::hbv_tank::calculator< P >::step, shyft::core::skaugen::calculator< P, S, R >::step, shyft::time_axis::combine, shyft::timeseries::op_max::operator(), accumulate_value, shyft::core::intersection.
auto shyft::timeseries::min(const A &lhs, const B &rhs)
Referenced by shyft::core::gamma_snow::calculator< P, S, R >::step, shyft::core::grf::distance_sort_order, shyft::core::grf::calculate_local_weights_data, shyft::core::hbv_snow::calculator< P, S >::update_state, shyft::core::hbv_tank::calculator< P >::step, shyft::core::inverse_distance::run_interpolation, shyft::core::kalman::state::make_covariance, shyft::core::skaugen::calculator< P, S, R >::step, shyft::time_axis::combine, shyft::timeseries::op_min::operator(), hint_based_search, accumulate_value, shyft::core::intersection.
size_t shyft::timeseries::hint_based_search(const S &source, const utcperiod &p, size_t i)
hint_based search to eliminate binary-search in irregular time-point series.
utilizing the fact that most access are periods, sequential, so the average_xxx functions can utilize this, and keep the returned index as a hint for the next request for average_xxx value. S a point ts source, must have .get(i) ->point, and .size(), and .index_of(t)->size_t source a point ts source as described above p utcperiod for which we search a start point <= p.start i the start-of-search hint, could be -1, then ts.index_of(p.start) is used to figure out the ix. lowerbound index or npos if not found We should specialize this for sources with computed time-axis to improve speed
References shyft::core::utcperiod::start, min.
Referenced by accumulate_value.
double shyft::timeseries::accumulate_value(const S &source, const utcperiod &p, size_t &last_idx, utctimespan &tsum, bool linear=true)
accumulate_value provides a projection/interpretation of the values of a pointsource on to a time-axis as provided. This includes interpolation and true average, linear between points and nan-handling semantics. In addition the Accessor allows fast sequential access to these values using clever caching of the last position used in the underlying point source. The time axis and point source can be of any type as listed above as long as the basic type requirement as described below are satisfied.
S point source, must provide: .size() const -> number of points in the source.index_of(utctime tx) const -> return lower bound index or -1 for the supplied tx.get(size_t i) const -> return the i'th point (t,v) source of type S p the period [start,end) on time-axis, the range where we will accumulate/integrate the f(t) last_idx in/out position of the last time point used on the source, updated after each call. tsum out, the sum of time under non-nan areas of the curve double, the area under the non-nan areas of the curve, specified by tsum ref-parameter
References shyft::nan, hint_based_search, shyft::timeseries::point::v, shyft::timeseries::point::t, shyft::core::utcperiod::end, max, shyft::core::utcperiod::start, min, shyft::core::utcperiod::timespan.
Referenced by shyft::timeseries::accumulate_ts< TS, TA >::value, shyft::timeseries::accumulate_ts< TS, TA >::operator(), average_value, shyft::timeseries::accumulate_accessor< S, TA >::value, shyft::api::accumulate_ts::value, shyft::api::accumulate_ts::value_at.
double shyft::timeseries::average_value(const S &source, const utcperiod &p, size_t &last_idx, bool linear=true)
average_value provides a projection/interpretation of the values of a pointsource on to a time-axis as provided. This includes interpolation and true average, linear between points and nan-handling semantics. In addition the Accessor allows fast sequential access to these values using clever caching of the last position used in the underlying point source. The time axis and point source can be of any type as listed above as long as the basic type requirement as described below are satisfied.
S point source, must provide: .size() const -> number of points in the source.index_of(utctime tx) const -> return lower bound index or -1 for the supplied tx.get(size_t i) const -> return the i'th point (t,v) source of type S p the period [start,end) on time-axis last_idx in/out position of the last time point used on the source, updated after each call. double, the value at the as true average of the specified period
References accumulate_value, shyft::nan.
Referenced by shyft::timeseries::average_ts< TS, TA >::value, shyft::timeseries::profile_accessor< gta_t >::value, shyft::timeseries::average_accessor< S, TA >::value, shyft::api::average_ts::value, shyft::api::average_ts::values.
double shyft::timeseries::l2_norm(A &ts)
Discrete l2 norm of input time series treated as a vector: (sqrt(sum(x_i)))
only used for debug/printout during calibration A the accessor type that implement: -#: .size() number of elements the accessor can provide -#: .value(i) value of the i'th element in the accessor
double shyft::timeseries::nash_sutcliffe_goal_function(const TSA1 &observed_ts, const TSA2 &model_ts)
Nash Sutcliffe model effiency coefficient based goal function http://en.wikipedia.org/wiki/NashE2%80%93Sutcliffe_model_efficiency_coefficient.
throws runtime exception if supplied arguments differs in .size() or .size()==0 if obs. is a constant, we get 1/0 TSA1 a ts accessor for the observed ts ( support .size() and double .value(i)) TSA2 a ts accessor for the observed ts ( support .size() and double .value(i)) observed_ts contains the observed values for the model model_ts contains the (simulated) model output values 1- E, given E=n.s, i.e. 0 is best performance > 0 .. +oo is less good performance.
Referenced by shyft::api::nash_sutcliffe.
double shyft::timeseries::kling_gupta_goal_function(const TSA1 &observed_ts, const TSA2 &model_ts, double s_r, double s_a, double s_b)
KLING-GUPTA Journal of Hydrology 377 (2009) 8091, page 83, formula (10), where shorthands are a=alpha, b=betha, q =sigma, u=my, s=simulated, o=observed
running_stat_calculator template class like dlib::running_scalar_covariance<double> that supports .add(x), hten mean_x|_y stddev_x|_y,correlation TSA1 time-series accessor that supports .size(), .value(i) TSA2 time-series accessor that supports .size(), .value(i) observed_ts the time-series that is the target, observed true value model_ts the time-series that is the model simulated/calculated ts s_r the kling gupta scale r factor (weight the correlation of goal function) s_a the kling gupta scale a factor (weight the relative average of the goal function) s_b the kling gupta scale b factor (weight the relative standard deviation of the goal function) EDs= 1-KGEs, that have a minimum at zero
vector<double> shyft::timeseries::calculate_percentiles_excel_method_full_sort(vector< double > &samples, const vector< int > &percentiles)
http://en.wikipedia.org/wiki/Percentile NIST definitions, we use R7, R and excel seems more natural.. http://www.itl.nist.gov/div898/handbook/prc/section2/prc262.htm calculate percentile using full sort.. works nice for a larger set of percentiles.
Referenced by calculate_percentiles.
std::vector< point_ts<ta_t> > shyft::timeseries::calculate_percentiles(const ta_t &ta, const std::vector< ts_t > &ts_list, const std::vector< int > &percentiles, size_t min_t_steps=1000)
calculate specified percentiles for supplied list of time-series over the specified time-axis
Percentiles for a set of timeseries, over a time-axis we would like to : percentiles_timeseries = calculate_percentiles(ts-id-list,time-axis,percentiles={0,25,50,100}) done like this 1..m ts-id, time-axis( start,dt, n), read 1..m ts into memory percentiles specified is np result is percentiles_timeseries accessor "accumulate" on time-axis to dt, using stair-case or linear between points create result vector[1..n] (the time-axis dimension) where each element is vector[1..np] (for each timestep, we get the percentiles for each timestep_i in timeaxis for each tsa_i: accessors(timeaxis,ts) samplevector[timestep_i].emplace_back( tsa_i(time_step_i) ) percentiles_timeseries[timestep_i]= calculate_percentiles(..)percentiles_timeseries
References shyft::api::percentiles, calculate_percentiles_excel_method_full_sort.
Referenced by shyft::api::percentiles.
std::vector<rts_t> shyft::timeseries::partition_by(const ts_t &ts, const calendar &cal, utctime t, utctimespan dt, size_t n, utctime t0, time_shift_func &&make_time_shift_fx)
partition_by convert a time-series into a vector of time-shifted partitions of ts with a common time-reference
The partitions are simply specified by calendar, delta_t (could be symbolic, like YEAR:MONTH:DAY) and n. To make yearly partitions, just pass calendar::YEAR as dt. The t-parameter set the start-time point in the source-time-series, like 1930.09.01 The t0-parameter set the common start-time of the new partitionsThe typical usage will be to use this function to partition years into a vector with e.g. 80 years, where we can do statistics, percentiles to compare and see the different effects of yearly season variations. Note that the function is more general, allowing any periodic partition, like daily, weekly, monthly etc. to study any pattern or statistics that might be periodic by the partition pattern.For exposure to python, additional preparation of the partitions could be useful like .average( timeaxis(t0,deltahours(1),365*24)) to make all with an equal-sized time-axis rts_t return type time-series, equal to the return-type of the time_shift_func() time_shift_func a callable type, that accepts ts_t and utctimespan as input and return rts_t ts_t time-series type that goes into the partition algorithm ts of type ts_t cal specifies the calendar to be used for possible calendar and time-zone semantic operations t specifies the time-point to start, e.g. 1930.09.01 dt specifies the calendar-semantic length of the partitions, e.g. calendar::YEAR|MONTH|DAY|WEEK n number of partitions, e.g. if you would have 80 yearly partitions, set n=80 t0 the common time-reference for the partitions, e.g. 2016.09.01 for 80 yearly partitions 1930.09.01 to 2010.09.01 make_time_shift_fx a callable that accepts const ts_t& and utctimespan and returns a time-shifted ts of type rts_t the partition vector, std::vector<rts_t> of size n, where each partition ts have its start-value at t0 t0 must align with multiple delta-t from t, e.g. if t is 1930.09.1, then t0 must have a pattern like YYYY.09.01 runtime_error if t0 is not aligned with t, see note above.
References shyft::core::calendar::diff_units, shyft::core::calendar::add.