shyft::core::actual_evapotranspiration
double shyft::core::actual_evapotranspiration::calculate_step(const double water_level, const double potential_evapotranspiration, const double scale_factor, const double snow_fraction, const utctime dt)
actual_evapotranspiration calculates actual evapotranspiration based on supplied parameters
water_level potential_evapotranspiration scale_factor typically 1.5 snow_fraction 0..1 - only snow free areas have evapotranspiration in this model dt delta_t currently not used in computation calculated actual evapotranspiration
Referenced by shyft::core::pt_gs_k::run_pt_gs_k, shyft::core::pt_hs_k::run, shyft::core::pt_ss_k::run.