shyft::api
extend_ts_fill_policy
Fill any gap between the time-axes with NaN.
extend_ts_split_policy
Split at the last value of the lhs ts.
iop_t
typedef shyft::time_series::point_ts<time_axis::fixed_dt> shyft::api::result_ts_t
typedef std::shared_ptr<result_ts_t> shyft::api::result_ts_t_
typedef shyft::core::hbv_stack::state shyft::api::hbv_stack_state_t
typedef shyft::core::pt_gs_k::state shyft::api::pt_gs_k_state_t
typedef shyft::core::pt_hs_k::state_t shyft::api::pt_hs_k_state_t
typedef shyft::core::pt_ss_k::state_t shyft::api::pt_ss_k_state_t
typedef shyft::time_axis::generic_dt shyft::api::gta_t
generic time-axis
time-series math to be exposed to pythonThis provide functionality likea = TsFactory.create_ts(..) b = TsFactory.create_ts(..) c = a + 3*b d = max(c,0.0)implementation strategyprovide a type apoint_ts, that always appears as a time-series.It could however represent either a point_ts<time_axis:generic_dt> or an expression like a abin_op_ts( lhs,op,rhs)Then we provide operators: apoint_ts bin_op a_point_ts and double bin_op a_points_tsUsing the time_axis library and concept directly. This time-axis is generic, but currently only dense-types fixed_dt (fastest) calendar_dt( quite fast, but with calendar semantics) point_dt ( a point at start of each interval, plus the end point of the last interval, could give performance hits in some scenarios)
typedef shyft::time_series::point_ts<gta_t> shyft::api::gts_t
typedef shyft::time_series::point_ts<time_axis::fixed_dt> shyft::api::rts_t
typedef vector<apoint_ts> shyft::api::ats_vec
ats_vector represents a list of time-series, support math-operations.
Supports handling and math operations for vectors of time-series. Especially convinient in python due to compact notation and speed.
std::vector< char > shyft::api::serialize_to_bytes(const std::shared_ptr< std::vector< CS >> &states)
References serialize_to_bytes.
Referenced by shyft::api::cell_state_with_id< CS >::cell_state_with_id.
template std::vector< char > shyft::api::serialize_to_bytes(const std::shared_ptr< std::vector< cell_state_with_id< shyft::core::hbv_stack::state >>> &states)
template std::vector< char > shyft::api::serialize_to_bytes(const std::shared_ptr< std::vector< cell_state_with_id< shyft::core::pt_gs_k::state >>> &states)
template std::vector< char > shyft::api::serialize_to_bytes(const std::shared_ptr< std::vector< cell_state_with_id< shyft::core::pt_ss_k::state >>> &states)
template std::vector< char > shyft::api::serialize_to_bytes(const std::shared_ptr< std::vector< cell_state_with_id< shyft::core::pt_hs_k::state >>> &states)
Referenced by serialize_to_bytes.
void shyft::api::deserialize_from_bytes(const std::vector< char > &bytes, std::shared_ptr< std::vector< CS >> &states)
References deserialize_from_bytes.
Referenced by shyft::api::cell_state_with_id< CS >::cell_state_with_id.
template void shyft::api::deserialize_from_bytes(const std::vector< char > &bytes, std::shared_ptr< std::vector< cell_state_with_id< shyft::core::hbv_stack::state >>> &states)
template void shyft::api::deserialize_from_bytes(const std::vector< char > &bytes, std::shared_ptr< std::vector< cell_state_with_id< shyft::core::pt_gs_k::state >>> &states)
template void shyft::api::deserialize_from_bytes(const std::vector< char > &bytes, std::shared_ptr< std::vector< cell_state_with_id< shyft::core::pt_hs_k::state >>> &states)
template void shyft::api::deserialize_from_bytes(const std::vector< char > &bytes, std::shared_ptr< std::vector< cell_state_with_id< shyft::core::pt_ss_k::state >>> &states)
Referenced by deserialize_from_bytes.
cell_state_id shyft::api::cell_state_id_of(const shyft::core::geo_cell_data &c_geo)
create the cell_state_id based on specified cell.geo part
References shyft::api::cell_state_id::cell_state_id, shyft::core::geo_cell_data::catchment_id, shyft::core::geo_cell_data::mid_point, shyft::core::geo_point::x, shyft::core::geo_point::y, shyft::core::geo_cell_data::area.
Referenced by shyft::api::state_io_handler< C >::apply_state.
static double shyft::api::do_op(double a, iop_t op, double b)
apoint_ts shyft::api::average(const apoint_ts &ts, const gta_t &ta)
Referenced by shyft::api::apoint_ts::average, shyft::api::apoint_ts::values, shyft::api::abin_op_ts_scalar::do_bind.
apoint_ts shyft::api::average(apoint_ts &&ts, const gta_t &ta)
apoint_ts shyft::api::integral(const apoint_ts &ts, const gta_t &ta)
Referenced by shyft::api::apoint_ts::integral, shyft::api::apoint_ts::values, shyft::api::abin_op_ts_scalar::do_bind.
apoint_ts shyft::api::integral(apoint_ts &&ts, const gta_t &ta)
apoint_ts shyft::api::accumulate(const apoint_ts &ts, const gta_t &ta)
Referenced by shyft::api::apoint_ts::accumulate, shyft::api::apoint_ts::values, shyft::api::accumulate_ts::values, shyft::api::abin_op_ts_scalar::do_bind.
apoint_ts shyft::api::accumulate(apoint_ts &&ts, const gta_t &ta)
apoint_ts shyft::api::create_periodic_pattern_ts(const vector< double > &pattern, utctimespan dt, utctime pattern_t0, const gta_t &ta)
Referenced by shyft::api::abin_op_ts_scalar::do_bind.
apoint_ts shyft::api::operator+(const apoint_ts &lhs, const apoint_ts &rhs)
References OP_ADD.
Referenced by shyft::api::abin_op_ts_scalar::do_bind, shyft::api::ats_vector::max.
apoint_ts shyft::api::operator+(const apoint_ts &lhs, double rhs)
References OP_ADD.
apoint_ts shyft::api::operator+(double lhs, const apoint_ts &rhs)
References OP_ADD.
apoint_ts shyft::api::operator-(const apoint_ts &lhs, const apoint_ts &rhs)
References OP_SUB.
Referenced by shyft::api::abin_op_ts_scalar::do_bind, shyft::api::ats_vector::max.
apoint_ts shyft::api::operator-(const apoint_ts &lhs, double rhs)
References OP_SUB.
apoint_ts shyft::api::operator-(double lhs, const apoint_ts &rhs)
References OP_SUB.
apoint_ts shyft::api::operator-(const apoint_ts &rhs)
References OP_MUL.
apoint_ts shyft::api::operator/(const apoint_ts &lhs, const apoint_ts &rhs)
References OP_DIV.
Referenced by shyft::api::abin_op_ts_scalar::do_bind, shyft::api::ats_vector::max.
apoint_ts shyft::api::operator/(const apoint_ts &lhs, double rhs)
References OP_DIV.
apoint_ts shyft::api::operator/(double lhs, const apoint_ts &rhs)
References OP_DIV.
apoint_ts shyft::api::operator*(const apoint_ts &lhs, const apoint_ts &rhs)
References OP_MUL.
Referenced by shyft::api::abin_op_ts_scalar::do_bind, shyft::api::ats_vector::max.
apoint_ts shyft::api::operator*(const apoint_ts &lhs, double rhs)
References OP_MUL.
apoint_ts shyft::api::operator*(double lhs, const apoint_ts &rhs)
References OP_MUL.
apoint_ts shyft::api::max(const apoint_ts &lhs, const apoint_ts &rhs)
References OP_MAX.
Referenced by shyft::api::apoint_ts::max, shyft::api::apoint_ts::values, shyft::api::abin_op_ts_scalar::do_bind, shyft::api::ats_vector::max.
apoint_ts shyft::api::max(const apoint_ts &lhs, double rhs)
References OP_MAX.
apoint_ts shyft::api::max(double lhs, const apoint_ts &rhs)
References OP_MAX.
apoint_ts shyft::api::min(const apoint_ts &lhs, const apoint_ts &rhs)
References OP_MIN.
Referenced by shyft::api::apoint_ts::min, shyft::api::apoint_ts::values, shyft::api::abin_op_ts_scalar::do_bind, shyft::api::ats_vector::max.
apoint_ts shyft::api::min(const apoint_ts &lhs, double rhs)
References OP_MIN.
apoint_ts shyft::api::min(double lhs, const apoint_ts &rhs)
percentiles, need to include several forms of time_axis for python
References OP_MIN.
static vector<double> shyft::api::ts_op_ts_values(const vector< double > &l, iop_t op, const vector< double > &r)
static void shyft::api::lhs_in_place_ts_op_ts_values(vector< double > &l, iop_t op, const vector< double > &r)
static void shyft::api::rhs_in_place_ts_op_ts_values(const vector< double > &l, iop_t op, vector< double > &r)
static const vector<double>* shyft::api::terminal_values(const shared_ptr< ipoint_ts > &ts)
static const vector<double>* shyft::api::terminal_values(const apoint_ts &ats)
static std::vector<double> shyft::api::make_interval(FX &&fx, const TA &ta, const TS &ts, const ATA &avg_ta)
make_interval templateHelp creating implementation of interval type of results (average/integral value) at highest possible speed
double shyft::api::integral_value(const S &source, const utcperiod &p, size_t &last_idx, bool linear)
static void shyft::api::find_ts_bind_info(const std::shared_ptr< shyft::api::ipoint_ts > &its, std::vector< ts_bind_info > &r)
recursive function to dig out bind_info
static bool shyft::api::all_same_generic_time_axis_type(const TSV &tsv)
std::vector< apoint_ts > shyft::api::percentiles(const std::vector< apoint_ts > &tsv1, const gta_t &ta, const vector< int > &percentile_list)
References shyft::time_axis::generic_dt::FIXED, shyft::time_series::calculate_percentiles, shyft::time_series::POINT_AVERAGE_VALUE, shyft::time_axis::generic_dt::CALENDAR, shyft::time_axis::generic_dt::POINT, shyft::nan.
Referenced by percentiles, shyft::dtss::server::do_evaluate_percentiles, shyft::api::abin_op_ts_scalar::do_bind, shyft::api::ats_vector::percentiles_f, shyft::time_series::calculate_percentiles.
std::vector< apoint_ts > shyft::api::percentiles(const std::vector< apoint_ts > &ts_list, const time_axis::fixed_dt &ta, const vector< int > &percentiles)
time_shift i.e. same ts values, but time-axis is time-axis + dt
References percentiles.
apoint_ts shyft::api::time_shift(const apoint_ts &ts, utctimespan dt)
References shyft::api::apoint_ts::apoint_ts.
Referenced by shyft::api::apoint_ts::time_shift, shyft::api::apoint_ts::values, shyft::api::abin_op_ts_scalar::do_bind.
double shyft::api::nash_sutcliffe(const apoint_ts &observation_ts, const apoint_ts &model_ts, const gta_t &ta)
References shyft::time_series::nash_sutcliffe_goal_function.
Referenced by shyft::api::abin_op_ts_scalar::do_bind, shyft::api::ats_vector::max.
double shyft::api::kling_gupta(const apoint_ts &observation_ts, const apoint_ts &model_ts, const gta_t &ta, double s_r, double s_a, double s_b)
Referenced by shyft::api::abin_op_ts_scalar::do_bind.
apoint_ts shyft::api::create_glacier_melt_ts_m3s(const apoint_ts &temp, const apoint_ts &sca_m2, double glacier_area_m2, double dtf)
References shyft::api::apoint_ts::apoint_ts.
Referenced by shyft::api::abin_op_ts_scalar::do_bind.
ats_vector shyft::api::operator*(ats_vector const &a, double b)
References shyft::api::ats_vector::reserve.
ats_vector shyft::api::operator*(double a, ats_vector const &b)
ats_vector shyft::api::operator*(ats_vector const &a, ats_vector const &b)
References shyft::api::ats_vector::reserve.
ats_vector shyft::api::operator*(ats_vector::value_type const &a, ats_vector const &b)
References shyft::api::ats_vector::reserve.
ats_vector shyft::api::operator*(ats_vector const &b, ats_vector::value_type const &a)
ats_vector shyft::api::operator/(ats_vector const &a, double b)
ats_vector shyft::api::operator/(double a, ats_vector const &b)
References shyft::api::ats_vector::reserve.
ats_vector shyft::api::operator/(ats_vector const &a, ats_vector const &b)
References shyft::api::ats_vector::reserve.
ats_vector shyft::api::operator/(ats_vector::value_type const &a, ats_vector const &b)
References shyft::api::ats_vector::reserve.
ats_vector shyft::api::operator/(ats_vector const &b, ats_vector::value_type const &a)
References shyft::api::ats_vector::reserve.
ats_vector shyft::api::operator+(ats_vector const &a, double b)
References shyft::api::ats_vector::reserve.
ats_vector shyft::api::operator+(double a, ats_vector const &b)
ats_vector shyft::api::operator+(ats_vector const &a, ats_vector const &b)
References shyft::api::ats_vector::reserve.
ats_vector shyft::api::operator+(ats_vector::value_type const &a, ats_vector const &b)
References shyft::api::ats_vector::reserve.
ats_vector shyft::api::operator+(ats_vector const &b, ats_vector::value_type const &a)
ats_vector shyft::api::operator-(const ats_vector &a)
References shyft::api::ats_vector::reserve.
ats_vector shyft::api::operator-(ats_vector const &a, double b)
References shyft::api::ats_vector::reserve.
ats_vector shyft::api::operator-(double a, ats_vector const &b)
References shyft::api::ats_vector::reserve.
ats_vector shyft::api::operator-(ats_vector const &a, ats_vector const &b)
References shyft::api::ats_vector::reserve.
ats_vector shyft::api::operator-(ats_vector::value_type const &a, ats_vector const &b)
References shyft::api::ats_vector::reserve.
ats_vector shyft::api::operator-(ats_vector const &b, ats_vector::value_type const &a)
References shyft::api::ats_vector::reserve.
ats_vector shyft::api::min(ats_vector const &a, double b)
References shyft::api::ats_vector::min.
ats_vector shyft::api::min(double b, ats_vector const &a)
References shyft::api::ats_vector::min.
ats_vector shyft::api::min(ats_vector const &a, apoint_ts const &b)
References shyft::api::ats_vector::min.
ats_vector shyft::api::min(apoint_ts const &b, ats_vector const &a)
References shyft::api::ats_vector::min.
ats_vector shyft::api::min(ats_vector const &a, ats_vector const &b)
References shyft::api::ats_vector::min.
Referenced by shyft::api::abin_op_scalar_ts::values, shyft::api::abin_op_ts_scalar::values.
ats_vector shyft::api::max(ats_vector const &a, double b)
References shyft::api::ats_vector::max.
ats_vector shyft::api::max(double b, ats_vector const &a)
References shyft::api::ats_vector::max.
ats_vector shyft::api::max(ats_vector const &a, apoint_ts const &b)
References shyft::api::ats_vector::max.
ats_vector shyft::api::max(apoint_ts const &b, ats_vector const &a)
References shyft::api::ats_vector::max.
ats_vector shyft::api::max(ats_vector const &a, ats_vector const &b)
References shyft::api::ats_vector::max.
Referenced by shyft::api::abin_op_scalar_ts::values, shyft::api::abin_op_ts_scalar::values.
ats_vector shyft::api::quantile_map_forecast(vector< ats_vector > const &forecast_sets, vector< double > const &set_weights, ats_vector const &historical_data, gta_t const &time_axis, utctime interpolation_start, utctime interpolation_end, bool interpolated_quantiles)
shyft::qm::quantile_map_forecast
References shyft::time_axis::generic_dt::size, shyft::core::is_valid, shyft::time_axis::generic_dt::total_period, shyft::core::utcperiod::contains, shyft::core::calendar::to_string, shyft::api::apoint_ts::time_axis.
Referenced by shyft::api::ats_vector::max.
apoint_ts shyft::api::extend(const apoint_ts &lhs_ts, const apoint_ts &rhs_ts, extend_ts_split_policy split_policy, extend_ts_fill_policy fill_policy, utctime split_at, double fill_value)
References shyft::api::apoint_ts::apoint_ts.
Referenced by shyft::api::apoint_ts::extend, shyft::api::apoint_ts::values, shyft::api::abin_op_ts_scalar::do_bind.
std::vector<Ts> shyft::api::deflate_ts_vector(TsV const &tsv1)
Given a vector of expressions, deflate(evaluate) the expressions and return the equivalent concrete point-time-series of the expressions in the preferred destination type Ts Useful for the dtss, evaluates the expressions in parallell