shyft::core::pt_hs_k
typedef parameter shyft::core::pt_hs_k::parameter_t
typedef state shyft::core::pt_hs_k::state_t
typedef response shyft::core::pt_hs_k::response_t
typedef shared_ptr<parameter_t> shyft::core::pt_hs_k::parameter_t_
typedef shared_ptr<state_t> shyft::core::pt_hs_k::state_t_
typedef shared_ptr<response_t> shyft::core::pt_hs_k::response_t_
typedef cell<parameter_t, environment_t, state_t, state_collector, all_response_collector> shyft::core::pt_hs_k::cell_complete_response_t
typedef cell<parameter_t, environment_t, state_t, null_collector, discharge_collector> shyft::core::pt_hs_k::cell_discharge_response_t
void shyft::core::pt_hs_k::run(const GEOCELLDATA &geo_cell_data, const P &parameter, const T &time_axis, int start_step, int n_steps, const T_TS &temp, const P_TS &prec, const WS_TS &wind_speed, const RH_TS &rel_hum, const RAD_TS &rad, S &state, SC &state_collector, RC &response_collector)
References shyft::core::precipitation_correction::calculator::calc, shyft::core::hbv_snow::calculator< P, S >::step, shyft::core::utcperiod::start, shyft::core::utcperiod::end, shyft::core::glacier_melt::step, shyft::core::priestley_taylor::calculator::potential_evapotranspiration, shyft::core::calendar::HOUR, shyft::core::actual_evapotranspiration::calculate_step, shyft::time_series::max, shyft::core::utcperiod::timespan, shyft::core::kirchner::calculator< AC, P >::step, shyft::m3s_to_mmh, shyft::mmh_to_m3s, x_serialize_export_key.
Referenced by shyft::core::model_calibration::optimizer< M, PA, PS >::calculate_goal_function, shyft::core::model_calibration::optimizer< M, PA, PS >::operator(), shyft::core::model_calibration::optimizer< M, PA, PS >::from_scaled.