shyft::core::glacier_melt
double shyft::core::glacier_melt::step(const double dtf, const double t, const double snow_covered_area_m2, const double glacier_area_m2)
Glacier Melt model dtf degree timestep factor [mm/day/deg.C]; lit. values for Norway: 5.5 - 6.4 in Hock, R. (2003), J. Hydrol., 282, 104-115. t temperature [deg.C] snow_covered_area_m2 of the glacier, in unit [m2] if glacier_area_m2 the area of the glacier, in unit [m2] glacier_melt in [m3/s]
Referenced by shyft::core::hbv_stack::run_hbv_stack, shyft::core::pt_gs_k::run_pt_gs_k, shyft::core::pt_hs_k::run, shyft::core::pt_ss_k::run, shyft::timeseries::glacier_melt_ts< std::shared_ptr< shyft::api::ipoint_ts > >::value.