shyft::experimental::io
static fs::path shyft::experimental::io::test_root_dir()
in a clever way, figure out the root directory for tests so that we can use relative paths for the remaining names
string shyft::experimental::io::test_path(string rel_path, bool report)
given a relative path, compute the working (abs) path to the file, print out error if not exists
'slurp' a file into a memory string string
Referenced by load_from_directory, shyft::experimental::repository::cell_file_repository< C >::read, shyft::experimental::repository::geo_located_ts_file_repository::read.
std::string shyft::experimental::io::slurp(const std::string &path)
Referenced by load_from_directory, shyft::experimental::repository::cell_file_repository< C >::read, shyft::experimental::repository::geo_located_ts_file_repository::read.
vector< string > shyft::experimental::io::find(const string subdir, const string &suffix)
given a subdir, search for all files with matching suffix in that directory, return back list of paths
Referenced by shyft::api::state_io_handler< C >::extract_state, shyft::api::state_io_handler< C >::apply_state, shyft::dtss::server::do_find_ts, load_from_directory, shyft::core::region_model< C, RE >::get_catchment_feeding_to_river.
shared_ptr< vector< geo_xts_t > > shyft::experimental::io::load_from_directory(wkt_reader &wkt_io, function< ec::geo_point(int)> id_to_geo_point, const string &subdir, const string &suffix)
given a wkt_reader (to help convert fro string to geo_xts_t), a lambda to convert from geo_id to geo_point, a subdir and a suffix, read all files matching and provide them back as a shared pointer to a vector of geo_xts_t
References find, shyft::experimental::wkt_reader::read_geo_xts_t, slurp, test_path.
Referenced by shyft::experimental::repository::geo_located_ts_file_repository::read.