shyft::core::grf
arma::mat::fixed<2, 2> shyft::core::grf::anisotropy_mapping(double anisotropy_ratio, double anisotropy_direction)
References M_PI.
Referenced by calculate_anisotropy_distances.
void shyft::core::grf::calculate_anisotropy_distances(const SP &source_begin, const SP &source_end, double anisotropy_ratio, double anisotropy_direction, arma::mat &anisotropy_distances)
Calculate the (symmetric) anisotropy distance matrix for stationsOnly compute upper half of matrix for speed.
References anisotropy_mapping, shyft::core::geo_point::x.
Referenced by run_interpolation.
void shyft::core::grf::calculate_anisotropy_distances(const SP &source_begin, const SP &source_end, const D &destination_begin, const D &destination_end, double anisotropy_ratio, double anisotropy_direction, arma::mat &anisotropy_distances)
References anisotropy_mapping, shyft::core::geo_point::x.
void shyft::core::grf::distance_sort_order(const arma::mat &distances, size_t sort_length, arma::umat &sort_order)
References shyft::timeseries::min.
void shyft::core::grf::calculate_gibbs_weights(const arma::mat &cov, const std::vector< unsigned int > &sub_inds, arma::mat &krig_weights)
Simple krig method to calculate gibbs weights for the sub set of indices given by sub_set.For an excellent introduction to kriging interpolation, see http://people.ku.edu/~gbohling/cpe940/Kriging.pdf This method assumes that the trend component of the random field is known and constant mean, m(u) = m, see pages 7 and 8 in the reference.
References shyft::core::bayesian_kriging::utils::cov.
Referenced by gibbs_sampler, run_interpolation.
void shyft::core::grf::calculate_gibbs_estimates(const std::vector< unsigned int > &sub_inds, const std::vector< double > &data, const arma::mat &weights, const arma::mat &cov, const double sill, std::vector< double > &mu, std::vector< double > &var)
Calculate krig estimates and variances for all stations.
At each point, the estimate is given by z_j = k_j + sum_i!=j k_i*z_i and k_j = mu(1-sum_i!=j k_i. See Analyzing Environmental Data by Walter W. Piegorsch,A. John Bailer, page 305.
Referenced by gibbs_sampler.
void shyft::core::grf::calculate_local_weights_data(const arma::mat &station_covariances, size_t max_neighbours, bool simple_kriging, D &dest)
Destination D must provide const arma::uvec& source_sort_order() const: sort order of distances to valid sources const arma::vec& source_covariances() const: covariances for valid sources void set_weights(const arma::vec& weights, const arma::uvec& indices): Set the weights for the stations given in indices
References shyft::timeseries::min.
Referenced by run_interpolation.
static void shyft::core::grf::gamma_transform(const std::vector< double > &x, const std::vector< double > &m, const std::vector< double > &cv, const std::vector< double > &p0, std::vector< double > &res)
static void shyft::core::grf::inv_gamma_transform(const std::vector< double > &x, const std::vector< double > &m, const std::vector< double > &cv, const std::vector< double > &p0, std::vector< double > &res)
static double shyft::core::grf::subset_mean(const std::vector< double > &values, const std::vector< unsigned int > indices)
Calculate mean of values restriced to indices.
static double shyft::core::grf::mean(const std::vector< double > &values)
Calculate mean of values.
static double shyft::core::grf::subset_var(const std::vector< double > &values, const std::vector< unsigned int > &indices)
Calculate variance of values restricted to indices.
static double shyft::core::grf::variance(const std::vector< double > &values)
Calculate variance of all values.
void shyft::core::grf::gibbs_sampler(size_t num_iter, size_t num_var_update, arma::mat &weights, arma::mat &covariances, arma::mat &distances, std::vector< unsigned int > &zero_inds, std::vector< double > &max_zero_transformed_precipitation, P &semi_var, std::vector< double > &transformed_precipitation)
References calculate_gibbs_estimates, calculate_gibbs_weights.
void shyft::core::grf::conditional_random_field_simulation(size_t num_realizations, const P &parameter, const D &destination_begin, const D &destination_end, const SV &semi_var, std::vector< double > &gauss_field)
void shyft::core::grf::run_interpolation(S source_begin, S source_end, D destination_begin, D destination_end, const T &time_axis, const P &parameter)
Gaussian Random Field Interpolation.
References calculate_anisotropy_distances, calculate_gibbs_weights, calculate_local_weights_data, shyft::experimental::io::find.