shyft::core::bayesian_kriging::utils
double shyft::core::bayesian_kriging::utils::scaled_dist(const GP &p1, const GP &p2, const P &param)
Scaled distance between points.
Multiply elevation distance with a scale factor and compute the corresponding difference between the points p1 and p2. P Parameter that supplies: P.zscale() const GP Parameter GeoPoint, that should have the zscaled_distance(GP p1,GPp2 ,double zscale) method defined p1 first point p2 second point 'param' the parameter containing zscale used scaled distance.
Referenced by build_covariance_matrices.
double shyft::core::bayesian_kriging::utils::zero_dist_cov(const P &parameter)
Referenced by build_covariance_matrices.
void shyft::core::bayesian_kriging::utils::cov(const TP &dists, TP &cov, const P &parameter)
Referenced by build_covariance_matrices, shyft::core::grf::calculate_gibbs_weights.
void shyft::core::bayesian_kriging::utils::build_covariance_matrices(S source_begin, S source_end, D destination_begin, D destination_end, const P &parameter, arma::mat &K, arma::mat &k)
Build the covariance matrices from sources and destinations.
The Bayesian Temperature Kriging algorithm needs source-source and source-destination covariance matrices. Define $p_1 = (x_1, y_1, z_1)$ and $p_2 = (x_2, y_2, z_2)$, two 3D points for the source/destination. Furthermore, define $d=\sqrt{(x_1-x_2)^2 + (y_1-y_2)^2 + (l(z_1-z_2))^2}$, where $l$ is a height scaling factor. Then, \[ cov(p_1, p_2) = (s-n)e^{-\frac{d}{r}} \] where $s$ is the sill, $n$ is the nugget and $r$ is the range of the semivariogram. S Source (location) Type that implements: S.mid_point() const > 3D point, GeoPoint, specifies the location D Destination (location/area) Type that implements: D.mid_point() const > 3D point, GeoPoint, specifies the locationD.set_temperature() > 3D point, arma::vec3, specifies the location P Parameters for the algorithm, that supplies: parameter.sill() const > Sill value of the semivariogramparameter.nug() const > Nugget value of the semivariogramparameter.range() const > Range of the semivariogramP.zscale() const > Height scaling factor source_begin source_end is specifying the range for the input sources destination_begin destination_end is specifying the range for the target of the interpolation parameter contains the parameter for the function K Symmetric, positive semi-definite source-source covariance matrix k source-destination covariance matrix
References scaled_dist, cov, zero_dist_cov.
Referenced by shyft::core::bayesian_kriging::btk_interpolation.
void shyft::core::bayesian_kriging::utils::build_elevation_matrices(S source_begin, S source_end, D destination_begin, D destination_end, arma::mat &F, arma::mat &f)
Build the elevation matrices from sources and destinations.
Build the elevation matrices needed by the Bayesian Temperature Kriging algorithm. S Source (location) Type that implements: S.mid_point() const > 3D point,GeoPoint, specifies the location D Destination (location/area) Type that implements: D.mid_point() const > 3D point, GeoPoint, specifies the location source_begin source_end is specifying the range for the input sources destination_begin destination_end is specifying the range for the target of the interpolation F Matrix $ F\in{} \mathcal{R}^{n,2} $, where $n$ is the number of sources. f Matrix $ F\in{} \mathcal{R}^{2,m} $, where $m$ is the number of destinations.
Referenced by shyft::core::bayesian_kriging::btk_interpolation.