shyft::core::geo_point
double shyft::core::geo_point::x
Referenced by shyft::api::geo_cell_data_io::push_to_vector, shyft::api::cell_state_id_of, shyft::experimental::wkt_reader::read_geo_point_map, distance2, distance_measure, zscaled_distance, zscaled_distance2, xy_distance, xy_distance2, difference, shyft::core::inverse_distance::temperature_gradient_scale_computer::p_mat.
double shyft::core::geo_point::y
Referenced by shyft::api::geo_cell_data_io::push_to_vector, shyft::api::cell_state_id_of, shyft::experimental::wkt_reader::read_geo_point_map, distance2, distance_measure, zscaled_distance, zscaled_distance2, xy_distance, xy_distance2, difference, shyft::core::inverse_distance::temperature_gradient_scale_computer::p_mat.
double shyft::core::geo_point::z
Referenced by shyft::api::geo_cell_data_io::push_to_vector, shyft::experimental::wkt_reader::read_geo_point_map, distance2, distance_measure, zscaled_distance, zscaled_distance2, z_distance2, difference, shyft::core::inverse_distance::temperature_gradient_scale_computer::p_mat.
shyft::core::geo_point::geo_point()
Referenced by difference.
shyft::core::geo_point::geo_point(double x, double y=0.0, double z=0.0)
bool shyft::core::geo_point::operator==(const geo_point &o) const
References distance2.
shyft::core::geo_point::x_serialize_decl()
Referenced by difference.
static double shyft::core::geo_point::distance2(const geo_point &a, const geo_point &b)
Squared eucledian distance.
the 3D distance^2 between supplied arguments a and b
References x, y, z.
Referenced by operator==.
static double shyft::core::geo_point::distance_measure(const geo_point &a, const geo_point &b, double p, double zscale)
Distance measure on the form sum(abs(a.x - b.x)^p + abs(a.y - b.y)^p + (zscale * abs(a.z - b.z))^p)
the 3D distance measure between supplied arguments a and b, by using an optional z scale factor
References x, y, z.
static double shyft::core::geo_point::zscaled_distance(const geo_point &a, const geo_point &b, double zscale)
Z scaled, non-eucledian distance between points a and b.
sqrt( (a.x - b.x)*(a.x - b.x) + (a.y - b.y)*(a.y - b.y) + (a.z - b.z)*(a.z - b.z)*zscale*zscale)
References x, y, z.
static double shyft::core::geo_point::zscaled_distance2(const geo_point &a, const geo_point &b, double zscale)
Z scaled, non-eucledian distance between points a and b.
(a.x - b.x)*(a.x - b.x) + (a.y - b.y)*(a.y - b.y) + (a.z - b.z)*(a.z - b.z)*zscale*zscale
References x, y, z.
static double shyft::core::geo_point::xy_distance(const geo_point &a, const geo_point &b)
Euclidian distance between points a and b, first projected onto x-y plane.
return sqrt((a.x - b.x)*(a.x - b.x) + (a.y - b.y)*(a.y - b.y))
References x, y.
static double shyft::core::geo_point::xy_distance2(const geo_point &a, const geo_point &b)
Euclidian distance^2 between points a and b, first projected onto x-y plane.
return (a.x - b.x)*(a.x - b.x) + (a.y - b.y)*(a.y - b.y)
References x, y.
static double shyft::core::geo_point::z_distance2(const geo_point &a, const geo_point &b)
References z.
static geo_point shyft::core::geo_point::difference(const geo_point &a, const geo_point &b)
Difference between points a and b, i.e. a - b. Should perhaps return a GeoDifference instead for mathematical correctness.
GeoPoint(a.x - b.x, a.y - b.y, a.z - b.z)
References geo_point, x, y, z, x_serialize_decl, x_serialize_export_key.