shyft::core::calendar
const utctimespan shyft::core::calendar::YEAR
const utctimespan shyft::core::calendar::QUARTER
const utctimespan shyft::core::calendar::MONTH
const utctimespan shyft::core::calendar::WEEK
const utctimespan shyft::core::calendar::DAY
Referenced by shyft::core::gamma_snow::calculator< P, S, R >::step, shyft::core::kalman::bias_predictor::compute_running_bias, time.
const utctimespan shyft::core::calendar::HOUR_3
const utctimespan shyft::core::calendar::HOUR
Referenced by shyft::core::gamma_snow::calculator< P, S, R >::step, shyft::core::hbv_stack::run_hbv_stack, shyft::core::pt_gs_k::run_pt_gs_k, shyft::core::pt_hs_k::run, shyft::core::pt_ss_k::run, time.
const utctimespan shyft::core::calendar::MINUTE
const utctimespan shyft::core::calendar::SECOND
const int shyft::core::calendar::UnixDay
Calc::julian_day_number(ymd(1970,01,01));.
const utctime shyft::core::calendar::UnixSecond
Calc::julian_day_number(ymd(1970,01,01));.
Referenced by time.
time_zone::tz_info_t_ shyft::core::calendar::tz_info
Referenced by operator=.
static unsigned long shyft::core::calendar::day_number(const YMDhms &ymd)
References shyft::core::YMDhms::month, shyft::core::YMDhms::year, shyft::core::YMDhms::day.
static YMDhms shyft::core::calendar::from_day_number(unsigned long dayNumber)
static int shyft::core::calendar::day_number(utctime t)
static utctimespan shyft::core::calendar::seconds(int h, int m, int s)
vector< string > shyft::core::calendar::region_id_list()
get list of available time zone region
References shyft::core::time_zone::n_tzdef.
static int shyft::core::calendar::utc_year(utctime t)
returns utc_year of t
for internal dst calculations only
References shyft::core::YMDhms::YEAR_MAX, shyft::core::YMDhms::YEAR_MIN, shyft::core::utcperiod::to_string.
Referenced by shyft::core::time_zone::tz_table::dst_offset.
time_zone::tz_info_t_ shyft::core::calendar::get_tz_info() const
returns tz_info (helper for boost python really)
shyft::core::calendar::calendar(utctimespan tz=0)
construct a timezone with standard offset, no dst, name= UTC+01 etc.
shyft::core::calendar::calendar(time_zone::tz_info_t_ tz_info)
construct a timezone from tz_info shared ptr provided from typically time_zone db
shyft::core::calendar::calendar(calendar const &o)
shyft::core::calendar::calendar(calendar &&o)
calendar& shyft::core::calendar::operator=(calendar const &o)
References tz_info.
calendar& shyft::core::calendar::operator=(calendar &&o)
shyft::core::calendar::calendar(std::string region_id)
construct a timezone based on region id uses internal tz_info_database to lookup the name.
region_id like Europe/Oslo, time_zone::tz_info_database
References shyft::core::time_zone::n_tzdef.
utctime shyft::core::calendar::time(YMDhms c) const
construct utctime from calendar coordinates YMDhms
If the YMDhms is invalid, runtime_error is thrown. Currently just trivial checks is done. c YMDhms that has to be valid calendar coordinates. special values of YMDhms, like max,min,null is mapped to corresponding utctime concepts. YMDhms utctime
References shyft::core::YMDhms::is_null, shyft::core::no_utctime, shyft::core::YMDhms::max, shyft::core::max_utctime, shyft::core::YMDhms::min, shyft::core::min_utctime, shyft::core::YMDhms::is_valid_coordinates, shyft::core::YMDhms::hour, shyft::core::YMDhms::minute, shyft::core::YMDhms::second.
Referenced by shyft::experimental::wkt_reader::read_geo_xts_t.
utctime shyft::core::calendar::time(YWdhms c) const
short hand for calendar::time(YMDhms)
References shyft::core::YWdhms::is_null, shyft::core::no_utctime, shyft::core::YWdhms::max, shyft::core::max_utctime, shyft::core::YWdhms::min, shyft::core::min_utctime, shyft::core::YWdhms::is_valid_coordinates, shyft::core::YWdhms::iso_year, shyft::core::YWdhms::iso_week, shyft::core::YWdhms::week_day, shyft::core::YWdhms::hour, shyft::core::YWdhms::minute, shyft::core::YWdhms::second, UnixSecond, DAY, HOUR.
utctime shyft::core::calendar::time(int Y, int M=1, int D=1, int h=0, int m=0, int s=0) const
utctime shyft::core::calendar::time_from_week(int Y, int W=1, int wd=1, int h=0, int m=0, int s=0) const
YMDhms shyft::core::calendar::calendar_units(utctime t) const
return the calendar units of t taking timezone and dst into account
Special utctime values, no_utctime max_utctime, min_utctime are mapped to corresponding YMDhms special values. YMDhms calendar units YMDhms
References shyft::core::no_utctime, shyft::core::max_utctime, shyft::core::YMDhms::max, shyft::core::min_utctime, shyft::core::YMDhms::min, shyft::core::YMDhms::year, shyft::core::YMDhms::month, shyft::core::YMDhms::day.
YWdhms shyft::core::calendar::calendar_week_units(utctime t) const
return the calendar iso week units of t taking timezone and dst into account
Special utctime values, no_utctime max_utctime, min_utctime are mapped to corresponding YWdhms special values. YWdhms calendar iso week units YWdhmsreturns 0=sunday, 1= monday ... 6=sat.
References shyft::core::no_utctime, shyft::core::max_utctime, shyft::core::YWdhms::max, shyft::core::min_utctime, shyft::core::YWdhms::min, shyft::core::YWdhms::week_day, shyft::core::YMDhms::month, shyft::core::YMDhms::day, shyft::core::YWdhms::iso_year, shyft::core::YMDhms::year, shyft::core::YWdhms::iso_week.
int shyft::core::calendar::day_of_week(utctime t) const
returns day_of year, 1..365..
References shyft::core::no_utctime, shyft::core::min_utctime, shyft::core::max_utctime.
size_t shyft::core::calendar::day_of_year(utctime t) const
returns the month of t, 1..12, -1 of not valid time
References shyft::core::no_utctime, shyft::core::max_utctime, shyft::core::min_utctime.
Referenced by shyft::core::bayesian_kriging::parameter::temperature_gradient, shyft::core::gamma_snow::parameter::is_snow_season, shyft::core::gamma_snow::parameter::is_start_melt_season.
int shyft::core::calendar::month(utctime t) const
returns quarter of t, 1..4, -1 no valid time
month to quarter for the trim function
References shyft::core::no_utctime, shyft::core::max_utctime, shyft::core::min_utctime.
Referenced by shyft::core::gamma_snow::parameter::is_snow_season.
int shyft::core::calendar::quarter(utctime t) const
returns a readable iso standard string
References shyft::core::no_utctime, shyft::core::max_utctime, shyft::core::min_utctime.
string shyft::core::calendar::to_string(utctime t) const
returns a readable period with time as for calendar::to_string
References shyft::core::no_utctime, shyft::core::min_utctime, shyft::core::max_utctime, shyft::core::deltahours, shyft::core::deltaminutes.
Referenced by shyft::api::quantile_map_forecast, shyft::core::utcperiod::to_string.
string shyft::core::calendar::to_string(utcperiod p) const
References shyft::core::utcperiod::valid, shyft::core::utcperiod::start, shyft::core::utcperiod::end, shyft::core::YMDhms::month, shyft::core::YMDhms::year, shyft::core::YMDhms::day.
utctime shyft::core::calendar::trim(utctime t, utctimespan deltaT) const
round down (floor) to nearest utctime with deltaT resolution.
If delta T is calendar::DAY,WEEK,MONTH,YEAR it do a time-zone semantically correct rounding. if delta T is any other number, e.g. minute/hour, the result is similar to integer truncation at the level of delta T. t utctime to be trimmed deltaT utctimespan specifying the resolution, use calendar::DAY,WEEK,MONTH,YEAR specify calendar specific resolutions a trimmed utctime
References shyft::core::no_utctime, shyft::core::min_utctime, shyft::core::max_utctime, shyft::core::YMDhms::month, shyft::core::YMDhms::day, shyft::core::YMDhms::hour, shyft::core::YMDhms::minute, shyft::core::YMDhms::second, shyft::core::YMDhms::year.
Referenced by shyft::core::kalman::bias_predictor::compute_running_bias.
utctime shyft::core::calendar::add(utctime t, utctimespan deltaT, long n) const
calendar semantic add
conceptually this is similar to t + deltaT*n but with deltaT equal to calendar::DAY,WEEK,MONTH,YEAR and/or with dst enabled time-zone the variation of length due to dst or month/year length is taken into account e.g. add one day, and calendar have dst, could give 23,24 or 25 hours due to dst. similar for week or any other time steps.calendar::diff_units DST -if the calendar include dst, following rules applies: transition hour 1st hour after dst has changedif t and resulting t have different utc-offsets, the result is adjusted dst adjustment with the difference. t utctime to add n deltaT from deltaT that can be any, but with calendar::DAY,WEEK,MONTH,YEAR calendar semantics applies n number of delta T to add, can be negative new calculated utctime
References shyft::core::YMDhms::year, shyft::core::YMDhms::month.
Referenced by shyft::time_series::partition_by.
utctimespan shyft::core::calendar::diff_units(utctime t1, utctime t2, utctimespan deltaT, utctimespan &remainder) const
calculate the distance t1..t2 in specified units
The function takes calendar semantics when deltaT is calendar::DAY,WEEK,MONTH,YEAR, and in addition also dst. e.g. the diff_units of calendar::DAY over summer->winter shift is 1, remainder is 0, even if the number of hours during those days are 23 and 25 summer and winter transition respectivelycalendar::add (t2-t1)/deltaT, and remainder, where deltaT could be calendar units DAY,WEEK,MONTH,YEARdiff_units discarding remainder, diff_units
References shyft::core::no_utctime.
Referenced by shyft::time_series::partition_by.
utctimespan shyft::core::calendar::diff_units(utctime t1, utctime t2, utctimespan deltaT) const
References shyft::core::utcperiod::x_serialize_decl.
shyft::core::calendar::x_serialize_decl()