shyft::time_axis::fixed_dt
utctime shyft::time_axis::fixed_dt::t
Referenced by shyft::dtss::ts_db::find, operator==, shyft::time_axis::time_shift, shyft::time_axis::period_list::null_range, shyft::time_axis::combine, shyft::time_axis::time_axis_map< time_axis::fixed_dt, time_axis::fixed_dt >::src_index.
utctimespan shyft::time_axis::fixed_dt::dt
Referenced by shyft::dtss::ts_db::find, operator==, shyft::time_axis::time_shift, shyft::time_axis::period_list::null_range, shyft::time_axis::extend, shyft::time_axis::combine, shyft::time_axis::time_axis_map< time_axis::fixed_dt, time_axis::fixed_dt >::src_index, shyft::time_axis::can_merge, shyft::time_axis::merge.
size_t shyft::time_axis::fixed_dt::n
Referenced by shyft::dtss::ts_db::find, operator==, shyft::time_axis::time_shift, shyft::time_axis::combine, shyft::time_axis::time_axis_map< time_axis::fixed_dt, time_axis::fixed_dt >::src_index, shyft::time_axis::can_merge.
shyft::time_axis::fixed_dt::fixed_dt(utctime start=no_utctime, utctimespan deltat=0, size_t n_periods=0)
utctimespan shyft::time_axis::fixed_dt::delta() const
Referenced by shyft::core::hbv_stack::discharge_collector::initialize, shyft::core::hbv_stack::state_collector::initialize, shyft::core::pt_gs_k::discharge_collector::initialize, shyft::core::pt_gs_k::state_collector::initialize, shyft::core::pt_hs_k::discharge_collector::initialize, shyft::core::pt_hs_k::state_collector::initialize, shyft::core::pt_ss_k::discharge_collector::initialize, shyft::core::pt_ss_k::state_collector::initialize, shyft::core::routing::model< C >::cell_output_m3s, shyft::core::routing::model< C >::output_m3s.
utctime shyft::time_axis::fixed_dt::start() const
Referenced by shyft::core::hbv_stack::discharge_collector::initialize, shyft::core::hbv_stack::state_collector::initialize, shyft::core::pt_gs_k::discharge_collector::initialize, shyft::core::pt_gs_k::state_collector::initialize, shyft::core::pt_hs_k::discharge_collector::initialize, shyft::core::pt_hs_k::state_collector::initialize, shyft::core::pt_ss_k::discharge_collector::initialize, shyft::core::pt_ss_k::state_collector::initialize, shyft::time_axis::merge.
size_t shyft::time_axis::fixed_dt::size() const
Referenced by shyft::core::ts_init, shyft::core::routing::model< C >::upstream_inflow, shyft::time_axis::generic_dt::size, shyft::time_axis::extend, shyft::time_axis::combine, shyft::time_axis::merge.
bool shyft::time_axis::fixed_dt::operator==(const fixed_dt &other) const
References t, dt, n.
bool shyft::time_axis::fixed_dt::operator!=(const fixed_dt &other) const
References shyft::time_series::operator==.
utcperiod shyft::time_axis::fixed_dt::total_period() const
References shyft::core::min_utctime.
Referenced by shyft::time_axis::generic_dt::total_period, shyft::time_axis::extend, shyft::time_axis::combine, shyft::time_axis::can_merge, shyft::time_axis::merge.
utctime shyft::time_axis::fixed_dt::time(size_t i) const
Referenced by shyft::time_axis::generic_dt::time.
utcperiod shyft::time_axis::fixed_dt::period(size_t i) const
Referenced by shyft::time_axis::generic_dt::period, shyft::time_axis::extend.
size_t shyft::time_axis::fixed_dt::index_of(utctime tx) const
Referenced by shyft::time_axis::generic_dt::index_of, shyft::time_axis::extend.
size_t shyft::time_axis::fixed_dt::open_range_index_of(utctime tx, size_t ix_hint=std::string::npos) const
Referenced by shyft::time_axis::generic_dt::open_range_index_of.
shyft::time_axis::fixed_dt::x_serialize_decl()
static fixed_dt shyft::time_axis::fixed_dt::full_range()
References shyft::core::min_utctime, shyft::core::max_utctime.
static fixed_dt shyft::time_axis::fixed_dt::null_range()
References x_serialize_decl.
Referenced by shyft::time_axis::extend, shyft::time_axis::combine.