shyft::timeseries::profile_description
utctime shyft::timeseries::profile_description::t0
Referenced by shyft::timeseries::profile_accessor< gta_t >::map_index, shyft::timeseries::profile_accessor< gta_t >::section_index, shyft::timeseries::profile_accessor< gta_t >::value, shyft::timeseries::profile_accessor< gta_t >::get.
utctimespan shyft::timeseries::profile_description::dt
Referenced by shyft::timeseries::profile_accessor< gta_t >::map_index, shyft::timeseries::profile_accessor< gta_t >::value, shyft::timeseries::profile_accessor< gta_t >::get.
std::vector<double> shyft::timeseries::profile_description::profile
shyft::timeseries::profile_description::profile_description(utctime t0, utctimespan dt, const std::vector< double > &profile)
shyft::timeseries::profile_description::profile_description()
size_t shyft::timeseries::profile_description::size() const
Referenced by shyft::timeseries::profile_accessor< gta_t >::map_index, shyft::timeseries::profile_accessor< gta_t >::value, shyft::timeseries::profile_accessor< gta_t >::size, shyft::timeseries::profile_accessor< gta_t >::get, shyft::timeseries::profile_accessor< gta_t >::index_of.
utctimespan shyft::timeseries::profile_description::duration() const
Referenced by shyft::timeseries::profile_accessor< gta_t >::section_index, shyft::timeseries::profile_accessor< gta_t >::value, shyft::timeseries::profile_accessor< gta_t >::size.
void shyft::timeseries::profile_description::reset_start(utctime ta0)
Referenced by shyft::timeseries::profile_accessor< gta_t >::profile_accessor.
double shyft::timeseries::profile_description::operator()(size_t i) const
References shyft::nan.