shyft::api::pt_gs_k_state_io
bool shyft::api::pt_gs_k_state_io::from_string(const std::string &str, pt_gs_k_state_t &s) const
References from_raw_string.
bool shyft::api::pt_gs_k_state_io::from_raw_string(const char *str, pt_gs_k_state_t &s) const
References shyft::core::pt_gs_k::state::gs, shyft::core::gamma_snow::state::albedo, shyft::core::gamma_snow::state::alpha, shyft::core::gamma_snow::state::sdc_melt_mean, shyft::core::gamma_snow::state::acc_melt, shyft::core::gamma_snow::state::iso_pot_energy, shyft::core::gamma_snow::state::temp_swe, shyft::core::gamma_snow::state::surface_heat, shyft::core::gamma_snow::state::lwc, shyft::core::pt_gs_k::state::kirchner, shyft::core::kirchner::state::q.
Referenced by from_string, vector_from_string.
std::string shyft::api::pt_gs_k_state_io::to_string(const pt_gs_k_state_t &s) const
References shyft::core::pt_gs_k::state::gs, shyft::core::gamma_snow::state::albedo, shyft::core::gamma_snow::state::alpha, shyft::core::gamma_snow::state::sdc_melt_mean, shyft::core::gamma_snow::state::acc_melt, shyft::core::gamma_snow::state::iso_pot_energy, shyft::core::gamma_snow::state::temp_swe, shyft::core::gamma_snow::state::surface_heat, shyft::core::gamma_snow::state::lwc, shyft::core::pt_gs_k::state::kirchner, shyft::core::kirchner::state::q.
Referenced by to_string.
std::string shyft::api::pt_gs_k_state_io::to_string(const std::vector< pt_gs_k_state_t > &sv) const
References to_string.
std::vector<pt_gs_k_state_t> shyft::api::pt_gs_k_state_io::vector_from_string(const std::string &s) const
References from_raw_string.