shyft::core::cell_statistics
static void shyft::core::cell_statistics::verify_cids_exist(const vector< cell > &cells, const vector< int > &catchment_indexes)
throws runtime_error if catchment_indexes contains cid that's not part of cells
static shared_ptr<pts_t> shyft::core::cell_statistics::average_catchment_feature(const vector< cell > &cells, const vector< int > &catchment_indexes, cell_feature_ts &&cell_ts)
average_catchment_feature returns the area-weighted average
cell the cell type, assumed to have .geo.area(), and geo.catchment_id() cell_feature_ts a callable that takes a const cell ref, returns a ts cells that we want to perform calculation on catchment_indexes list of catchment-id that identifies the cells, if zero length, all are averaged cell_ts a callable that fetches the cell feature we want to average runtime_error if number of cells are zero area weighted feature sum, as a ts, a shared_ptr<pts_ts>
References shyft::time_series::POINT_AVERAGE_VALUE.
static double shyft::core::cell_statistics::average_catchment_feature_value(const vector< cell > &cells, const vector< int > &catchment_indexes, cell_feature_ts &&cell_ts, size_t i)
average_catchment_feature_value returns the area-weighted average for a timestep
cell the cell type, assumed to have .geo.area(), and geo.catchment_id() cell_feature_ts a callable that takes a const cell ref, returns a ts cells that we want to perform calculation on catchment_indexes list of catchment-id that identifies the cells, if zero length, all are averaged cell_ts a callable that fetches the cell feature we want to average i the i'th time-step for which we compute the value runtime_error if number of cells are zero area weighted feature sum, as a double value
Referenced by shyft::api::basic_cell_statistics< cell >::temperature_value, shyft::api::basic_cell_statistics< cell >::precipitation_value, shyft::api::basic_cell_statistics< cell >::radiation_value, shyft::api::basic_cell_statistics< cell >::wind_speed_value, shyft::api::basic_cell_statistics< cell >::rel_hum_value, shyft::api::gamma_snow_cell_state_statistics< cell >::albedo_value, shyft::api::gamma_snow_cell_state_statistics< cell >::lwc_value, shyft::api::gamma_snow_cell_state_statistics< cell >::surface_heat_value, shyft::api::gamma_snow_cell_state_statistics< cell >::alpha_value, shyft::api::gamma_snow_cell_state_statistics< cell >::sdc_melt_mean_value, shyft::api::gamma_snow_cell_state_statistics< cell >::acc_melt_value, shyft::api::gamma_snow_cell_state_statistics< cell >::iso_pot_energy_value, shyft::api::gamma_snow_cell_state_statistics< cell >::temp_swe_value, shyft::api::gamma_snow_cell_response_statistics< cell >::sca_value, shyft::api::gamma_snow_cell_response_statistics< cell >::swe_value, shyft::api::skaugen_cell_state_statistics< cell >::alpha_value, shyft::api::skaugen_cell_state_statistics< cell >::nu_value, shyft::api::skaugen_cell_state_statistics< cell >::lwc_value, shyft::api::skaugen_cell_state_statistics< cell >::residual_value, shyft::api::skaugen_cell_state_statistics< cell >::swe_value, shyft::api::skaugen_cell_state_statistics< cell >::sca_value, shyft::api::skaugen_cell_response_statistics< cell >::total_stored_water_value, shyft::api::hbv_snow_cell_state_statistics< cell >::swe_value, shyft::api::hbv_snow_cell_state_statistics< cell >::sca_value, shyft::api::priestley_taylor_cell_response_statistics< cell >::output_value, shyft::api::hbv_soil_cell_response_statistics< cell >::output_value, shyft::api::actual_evapotranspiration_cell_response_statistics< cell >::output_value, shyft::api::hbv_actual_evapotranspiration_cell_response_statistics< cell >::output_value.
static shared_ptr<pts_t> shyft::core::cell_statistics::sum_catchment_feature(const vector< cell > &cells, const vector< int > &catchment_indexes, cell_feature_ts &&cell_ts)
sum_catchment_feature returns the sum of cell-features(discharge etc)
cell the cell type, assumed to have geo.catchment_id() cell_feature_ts a callable that takes a const cell ref, returns a ts cells that we want to perform calculation on catchment_indexes list of catchment-id that identifies the cells, if zero length, all are summed cell_ts a callable that fetches the cell feature we want to sum runtime_error if number of cells are zero feature sum, as a ts, a shared_ptr<pts_ts>
References shyft::time_series::POINT_AVERAGE_VALUE.
static double shyft::core::cell_statistics::sum_catchment_feature_value(const vector< cell > &cells, const vector< int > &catchment_indexes, cell_feature_ts &&cell_ts, size_t i)
sum_catchment_feature_value returns the sum of cell-features(discharge etc) value at the i'th timestep
cell the cell type, assumed to have geo.catchment_id() cell_feature_ts a callable that takes a const cell ref, returns a ts cells that we want to perform calculation on catchment_indexes list of catchment-id that identifies the cells, if zero length, all are summed cell_ts a callable that fetches the cell feature we want to sum i the i'th time-step of the time-axis to use runtime_error if number of cells are zero feature sum, as a ts, a shared_ptr<pts_ts>
Referenced by shyft::api::basic_cell_statistics< cell >::discharge_value, shyft::api::basic_cell_statistics< cell >::charge_value, shyft::api::kirchner_cell_state_statistics< cell >::discharge_value, shyft::api::hbv_soil_cell_state_statistics< cell >::discharge_value, shyft::api::hbv_tank_cell_state_statistics< cell >::discharge_value, shyft::api::gamma_snow_cell_response_statistics< cell >::outflow_value, shyft::api::gamma_snow_cell_response_statistics< cell >::glacier_melt_value, shyft::api::skaugen_cell_response_statistics< cell >::outflow_value, shyft::api::skaugen_cell_response_statistics< cell >::glacier_melt_value, shyft::api::hbv_snow_cell_response_statistics< cell >::outflow_value, shyft::api::hbv_snow_cell_response_statistics< cell >::glacier_melt_value.
static vector<double> shyft::core::cell_statistics::catchment_feature(const vector< cell > &cells, const vector< int > &catchment_indexes, cell_feature_ts &&cell_ts, size_t i)
catchment_feature extracts cell-features(discharge etc) for specific i'th period of timeaxis
cell the cell type, assumed to have geo.catchment_id() cell_feature_ts a callable that takes a const cell ref, returns a ts cells that we want to extract feature from catchment_indexes list of catchment-id that identifies the cells, if zero length, all are summed cell_ts a callable that fetches the cell feature ts i the i'th step on the time-axis of the cell-feature runtime_error if number of cells are zero vector filled with feature for the i'th time-step on timeaxis
Referenced by shyft::api::basic_cell_statistics< cell >::discharge, shyft::api::basic_cell_statistics< cell >::charge, shyft::api::basic_cell_statistics< cell >::temperature, shyft::api::basic_cell_statistics< cell >::precipitation, shyft::api::basic_cell_statistics< cell >::radiation, shyft::api::basic_cell_statistics< cell >::wind_speed, shyft::api::basic_cell_statistics< cell >::rel_hum, shyft::api::kirchner_cell_state_statistics< cell >::discharge, shyft::api::hbv_soil_cell_state_statistics< cell >::discharge, shyft::api::hbv_tank_cell_state_statistics< cell >::discharge, shyft::api::gamma_snow_cell_state_statistics< cell >::albedo, shyft::api::gamma_snow_cell_state_statistics< cell >::lwc, shyft::api::gamma_snow_cell_state_statistics< cell >::surface_heat, shyft::api::gamma_snow_cell_state_statistics< cell >::alpha, shyft::api::gamma_snow_cell_state_statistics< cell >::sdc_melt_mean, shyft::api::gamma_snow_cell_state_statistics< cell >::acc_melt, shyft::api::gamma_snow_cell_state_statistics< cell >::iso_pot_energy, shyft::api::gamma_snow_cell_state_statistics< cell >::temp_swe, shyft::api::gamma_snow_cell_response_statistics< cell >::sca, shyft::api::gamma_snow_cell_response_statistics< cell >::swe, shyft::api::gamma_snow_cell_response_statistics< cell >::outflow, shyft::api::gamma_snow_cell_response_statistics< cell >::glacier_melt, shyft::api::skaugen_cell_state_statistics< cell >::alpha, shyft::api::skaugen_cell_state_statistics< cell >::nu, shyft::api::skaugen_cell_state_statistics< cell >::lwc, shyft::api::skaugen_cell_state_statistics< cell >::residual, shyft::api::skaugen_cell_state_statistics< cell >::swe, shyft::api::skaugen_cell_state_statistics< cell >::sca, shyft::api::skaugen_cell_response_statistics< cell >::outflow, shyft::api::skaugen_cell_response_statistics< cell >::total_stored_water, shyft::api::skaugen_cell_response_statistics< cell >::glacier_melt, shyft::api::hbv_snow_cell_state_statistics< cell >::swe, shyft::api::hbv_snow_cell_state_statistics< cell >::sca, shyft::api::hbv_snow_cell_response_statistics< cell >::outflow, shyft::api::hbv_snow_cell_response_statistics< cell >::glacier_melt, shyft::api::priestley_taylor_cell_response_statistics< cell >::output, shyft::api::hbv_soil_cell_response_statistics< cell >::output, shyft::api::actual_evapotranspiration_cell_response_statistics< cell >::output, shyft::api::hbv_actual_evapotranspiration_cell_response_statistics< cell >::output.