shyft::core::YMDhms
const int shyft::core::YMDhms::YEAR_MAX
Referenced by shyft::core::calendar::utc_year.
const int shyft::core::YMDhms::YEAR_MIN
Referenced by shyft::core::calendar::utc_year.
int shyft::core::YMDhms::year
Referenced by shyft::core::calendar::calendar_units, operator==, shyft::core::calendar::day_number.
int shyft::core::YMDhms::month
Referenced by shyft::core::calendar::calendar_units, operator==, shyft::core::calendar::day_number.
int shyft::core::YMDhms::day
Referenced by shyft::core::calendar::calendar_units, operator==, shyft::core::calendar::day_number.
int shyft::core::YMDhms::hour
Referenced by shyft::core::calendar::time, shyft::core::calendar::calendar_units, operator==.
int shyft::core::YMDhms::minute
Referenced by shyft::core::calendar::time, shyft::core::calendar::calendar_units, operator==.
int shyft::core::YMDhms::second
just check that YMDhms are within reasonable ranges,
it might still be an 'invalid' date!
Referenced by shyft::core::calendar::time, shyft::core::calendar::calendar_units, operator==.
shyft::core::YMDhms::YMDhms()
shyft::core::YMDhms::YMDhms(int Y, int M=1, int D=1, int h=0, int m=0, int s=0)
References shyft::core::is_valid.
bool shyft::core::YMDhms::is_valid_coordinates() const
if a 'null' or valid_coordinates
Referenced by shyft::core::calendar::time.
bool shyft::core::YMDhms::is_valid() const
bool shyft::core::YMDhms::is_null() const
Referenced by shyft::core::calendar::time.
bool shyft::core::YMDhms::operator==(const YMDhms &x) const
References year, month, day, hour, minute, second.
static YMDhms shyft::core::YMDhms::max()
Referenced by shyft::core::calendar::time, shyft::core::calendar::calendar_units.
static YMDhms shyft::core::YMDhms::min()
Referenced by shyft::core::calendar::time, shyft::core::calendar::calendar_units.