shyft::time_axis::point_dt
vector<utctime> shyft::time_axis::point_dt::t
Referenced by shyft::dtss::ts_db::find, operator=, operator==, shyft::time_axis::time_shift, shyft::time_axis::period_list::null_range, shyft::time_axis::combine, shyft::time_axis::merge.
utctime shyft::time_axis::point_dt::t_end
Referenced by shyft::dtss::ts_db::find, operator=, operator==, shyft::time_axis::time_shift, shyft::time_axis::period_list::null_range, shyft::time_axis::combine.
shyft::time_axis::point_dt::point_dt()
References shyft::core::no_utctime.
shyft::time_axis::point_dt::point_dt(const vector< utctime > &t, utctime t_end)
shyft::time_axis::point_dt::point_dt(const vector< utctime > &all_points)
shyft::time_axis::point_dt::point_dt(vector< utctime > &&all_points)
shyft::time_axis::point_dt::point_dt(const point_dt &c)
shyft::time_axis::point_dt::point_dt(point_dt &&c)
point_dt& shyft::time_axis::point_dt::operator=(point_dt &&c)
point_dt& shyft::time_axis::point_dt::operator=(const point_dt &x)
References t, t_end.
bool shyft::time_axis::point_dt::operator==(const point_dt &other) const
References t, t_end.
bool shyft::time_axis::point_dt::operator!=(const point_dt &other) const
References shyft::time_series::operator==.
size_t shyft::time_axis::point_dt::size() const
Referenced by shyft::time_axis::generic_dt::size.
utcperiod shyft::time_axis::point_dt::total_period() const
References shyft::core::min_utctime.
Referenced by shyft::time_axis::generic_dt::total_period, shyft::time_axis::can_merge.
utctime shyft::time_axis::point_dt::time(size_t i) const
Referenced by shyft::time_axis::generic_dt::time.
utcperiod shyft::time_axis::point_dt::period(size_t i) const
Referenced by shyft::time_axis::generic_dt::period.
size_t shyft::time_axis::point_dt::index_of(utctime tx, size_t ix_hint=std::string::npos) const
Referenced by shyft::time_axis::generic_dt::index_of, shyft::time_axis::ta_index_of.
size_t shyft::time_axis::point_dt::open_range_index_of(utctime tx, size_t ix_hint=std::string::npos) const
Referenced by shyft::time_axis::generic_dt::open_range_index_of.
shyft::time_axis::point_dt::x_serialize_decl()
static point_dt shyft::time_axis::point_dt::null_range()
References x_serialize_decl.
Referenced by shyft::time_axis::extend, shyft::time_axis::combine.