shyft::api::gpoint_ts
gts_t shyft::api::gpoint_ts::rep
shyft::api::gpoint_ts::gpoint_ts(gts_t &&x)
shyft::api::gpoint_ts::gpoint_ts(const gts_t &x)
shyft::api::gpoint_ts::gpoint_ts(const gta_t &ta, double fill_value, ts_point_fx point_fx=POINT_INSTANT_VALUE)
shyft::api::gpoint_ts::gpoint_ts(const gta_t &ta, const std::vector< double > &v, ts_point_fx point_fx=POINT_INSTANT_VALUE)
shyft::api::gpoint_ts::gpoint_ts(gta_t &&ta, double fill_value, ts_point_fx point_fx=POINT_INSTANT_VALUE)
shyft::api::gpoint_ts::gpoint_ts(gta_t &&ta, std::vector< double > &&v, ts_point_fx point_fx=POINT_INSTANT_VALUE)
shyft::api::gpoint_ts::gpoint_ts(const gta_t &ta, std::vector< double > &&v, ts_point_fx point_fx=POINT_INSTANT_VALUE)
shyft::api::gpoint_ts::gpoint_ts()=default
virtual ts_point_fx shyft::api::gpoint_ts::point_interpretation() const
References shyft::time_series::point_ts< TA >::point_interpretation.
virtual void shyft::api::gpoint_ts::set_point_interpretation(ts_point_fx point_interpretation)
References shyft::time_series::point_ts< TA >::set_point_interpretation.
virtual const gta_t& shyft::api::gpoint_ts::time_axis() const
Returns the effective time-axis of the timeseries
References shyft::time_series::point_ts< TA >::time_axis.
virtual utcperiod shyft::api::gpoint_ts::total_period() const
the total period of time_axis(), same as time_axis().total_period()
References shyft::time_series::point_ts< TA >::total_period.
virtual size_t shyft::api::gpoint_ts::index_of(utctime t) const
we might want index_of(t,ix-hint..)
the index_of(utctime t), using time_axis().index_of(t) time_axis::fixed_dt
References shyft::time_series::point_ts< TA >::index_of.
virtual size_t shyft::api::gpoint_ts::size() const
number of points that descr. y=f(t) on t ::= period
References shyft::time_series::point_ts< TA >::size.
virtual utctime shyft::api::gpoint_ts::time(size_t i) const
time_axis().time(i), the start of the i'th period in the time-axis
References shyft::time_series::point_ts< TA >::time.
virtual double shyft::api::gpoint_ts::value(size_t i) const
the value at the i'th period of the time-axis
References shyft::time_series::point_ts< TA >::v.
virtual double shyft::api::gpoint_ts::value_at(utctime t) const
the f(t) at the specified time t, if t outside total_period() nan is returned
virtual std::vector<double> shyft::api::gpoint_ts::values() const
the values, one for each of the time_axis() intervals as a vector
References shyft::time_series::point_ts< TA >::v.
void shyft::api::gpoint_ts::set(size_t i, double x)
References shyft::time_series::point_ts< TA >::set.
Referenced by shyft::api::apoint_ts::set.
void shyft::api::gpoint_ts::fill(double x)
References shyft::time_series::point_ts< TA >::fill.
Referenced by shyft::api::apoint_ts::fill.
void shyft::api::gpoint_ts::scale_by(double x)
References shyft::time_series::point_ts< TA >::scale_by.
Referenced by shyft::api::apoint_ts::scale_by.
virtual bool shyft::api::gpoint_ts::needs_bind() const
for internal computation and expression trees, we need to know if there are unbound symbolic ts in the chain of this ts We know that a point-ts never do not need a binding, but all others are expressions of ts, and could potentially needs a bind (if it has an unbound symbolic ts in it's siblings)
virtual void shyft::api::gpoint_ts::do_bind()
propagate do_bind to expression tree siblings(if any) then do any needed binding stuff needed for the specific class impl.
gts_t& shyft::api::gpoint_ts::core_ts()
const gts_t& shyft::api::gpoint_ts::core_ts() const
References x_serialize_decl.
shyft::api::gpoint_ts::x_serialize_decl()