shyft::timeseries::periodic_ts
TA shyft::timeseries::periodic_ts< PD, TA >::ta
Referenced by shyft::api::periodic_ts::time_axis, shyft::api::periodic_ts::total_period, shyft::api::periodic_ts::size, shyft::api::periodic_ts::time.
profile_accessor<TA> shyft::timeseries::periodic_ts< PD, TA >::pa
point_interpretation_policy shyft::timeseries::periodic_ts< PD, TA >::fx_policy
shyft::timeseries::periodic_ts< PD, TA >::periodic_ts(const PD &pd, const TA &ta, point_interpretation_policy policy=point_interpretation_policy::POINT_AVERAGE_VALUE)
shyft::timeseries::periodic_ts< PD, TA >::periodic_ts(const vector< double > &pattern, utctimespan dt, const TA &ta)
shyft::timeseries::periodic_ts< PD, TA >::periodic_ts(const vector< double > &pattern, utctimespan dt, utctime pattern_t0, const TA &ta)
shyft::timeseries::periodic_ts< PD, TA >::periodic_ts()
double shyft::timeseries::periodic_ts< PD, TA >::operator()(utctime t) const
size_t shyft::timeseries::periodic_ts< PD, TA >::size() const
size_t shyft::timeseries::periodic_ts< PD, TA >::index_of(utctime t) const
Referenced by shyft::api::periodic_ts::index_of.
double shyft::timeseries::periodic_ts< PD, TA >::value(size_t i) const
Referenced by shyft::api::periodic_ts::value.
std::vector<double> shyft::timeseries::periodic_ts< PD, TA >::values() const
Referenced by shyft::api::periodic_ts::values.