shyft::core::utcperiod
utctime shyft::core::utcperiod::start
Referenced by shyft::core::bayesian_kriging::parameter::temperature_gradient, shyft::dtss::mini_frag< ts_frag >::get_ix, shyft::dtss::ts_db::find, shyft::core::hbv_stack::run_hbv_stack, shyft::core::pt_gs_k::run_pt_gs_k, shyft::core::pt_hs_k::run, shyft::core::pt_ss_k::run, shyft::time_axis::extend, shyft::time_axis::combine, shyft::time_axis::continuous_merge, shyft::time_series::hint_based_search, shyft::time_series::accumulate_value, shyft::api::extend_ts::get_split_at, shyft::qm::quantile_mapping, shyft::core::calendar::to_string, timespan, valid, operator==, contains, overlaps, shyft::core::intersection.
utctime shyft::core::utcperiod::end
Referenced by shyft::api::TsFactory::create_time_point_ts, shyft::core::bayesian_kriging::parameter::temperature_gradient, shyft::dtss::ts_db::find, shyft::core::hbv_stack::run_hbv_stack, shyft::core::pt_gs_k::run_pt_gs_k, shyft::core::pt_hs_k::run, shyft::core::pt_ss_k::run, shyft::time_axis::extend, shyft::time_axis::combine, shyft::time_axis::continuous_merge, shyft::time_series::accumulate_value, shyft::api::extend_ts::get_split_at, shyft::qm::quantile_mapping, shyft::core::calendar::to_string, timespan, valid, operator==, contains, overlaps, shyft::core::intersection.
shyft::core::utcperiod::utcperiod(utctime start, utctime end)
shyft::core::utcperiod::utcperiod()
Referenced by shyft::core::intersection.
utctimespan shyft::core::utcperiod::timespan() const
References end, start.
Referenced by shyft::core::hbv_stack::run_hbv_stack, shyft::core::pt_gs_k::run_pt_gs_k, shyft::core::pt_hs_k::run, shyft::core::pt_ss_k::run, shyft::time_axis::combine, shyft::time_series::accumulate_value.
bool shyft::core::utcperiod::valid() const
References start, end.
Referenced by shyft::dtss::client::percentiles, shyft::dtss::client::evaluate, shyft::qm::quantile_mapping, shyft::core::calendar::to_string, contains, shyft::core::is_valid.
bool shyft::core::utcperiod::operator==(const utcperiod &p) const
References start, end.
Referenced by shyft::core::YMDhms::operator!=, shyft::core::YWdhms::operator!=.
bool shyft::core::utcperiod::operator!=(const utcperiod &p) const
bool shyft::core::utcperiod::contains(utctime t) const
References shyft::core::is_valid, valid, start, end.
Referenced by shyft::api::quantile_map_forecast, shyft::dtss::ts_db::save, shyft::time_axis::combine, shyft::time_series::accumulate_value, shyft::api::average_ts::value_at, shyft::api::integral_ts::value_at, shyft::api::accumulate_ts::value_at, shyft::qm::quantile_mapping.
bool shyft::core::utcperiod::contains(const utcperiod &p) const
References valid, start, end.
bool shyft::core::utcperiod::overlaps(const utcperiod &p) const
References start, end.
Referenced by shyft::time_axis::combine.
string shyft::core::utcperiod::to_string() const
References shyft::core::calendar::to_string.
Referenced by shyft::core::operator<<, shyft::core::calendar::utc_year.
shyft::core::utcperiod::x_serialize_decl()
Referenced by shyft::core::time_zone::tz_table::dst_end, shyft::core::time_zone::tz_info< tz_table >::is_dst, shyft::core::calendar::diff_units.
std::ostream& operator<<(std::ostream &os, const utcperiod &p)