shyft::timeseries::glacier_melt_ts
typedef d_ref_t<TS_A>::type::ta_t shyft::timeseries::glacier_melt_ts< TS_A, TS_B >::ta_t
TS_A shyft::timeseries::glacier_melt_ts< TS_A, TS_B >::temperature
TS_B shyft::timeseries::glacier_melt_ts< TS_A, TS_B >::sca_m2
double shyft::timeseries::glacier_melt_ts< TS_A, TS_B >::glacier_area_m2
double shyft::timeseries::glacier_melt_ts< TS_A, TS_B >::dtf
point_interpretation_policy shyft::timeseries::glacier_melt_ts< TS_A, TS_B >::fx_policy
Referenced by shyft::api::aglacier_melt_ts::point_interpretation, shyft::api::aglacier_melt_ts::set_point_interpretation.
const ta_t& shyft::timeseries::glacier_melt_ts< TS_A, TS_B >::time_axis() const
Referenced by shyft::api::aglacier_melt_ts::time_axis, shyft::api::aglacier_melt_ts::total_period, shyft::api::aglacier_melt_ts::index_of, shyft::api::aglacier_melt_ts::size, shyft::api::aglacier_melt_ts::time.
shyft::timeseries::glacier_melt_ts< TS_A, TS_B >::glacier_melt_ts(A_ &&temperature, B_ &&sca_m2, double glacier_area_m2, double dtf)
construct a glacier_melt_ts temperature in [deg.C] sca_m2 snow covered area [m2] glacier_area_m2 [m2] dtf degree timestep factor [mm/day/deg.C]; lit. values for Norway: 5.5 - 6.4 in Hock, R. (2003), J. Hydrol., 282, 104-115.
shyft::timeseries::glacier_melt_ts< TS_A, TS_B >::glacier_melt_ts()
point shyft::timeseries::glacier_melt_ts< TS_A, TS_B >::get(size_t i) const
size_t shyft::timeseries::glacier_melt_ts< TS_A, TS_B >::size() const
size_t shyft::timeseries::glacier_melt_ts< TS_A, TS_B >::index_of(utctime t) const
double shyft::timeseries::glacier_melt_ts< TS_A, TS_B >::value(size_t i) const
Referenced by shyft::api::aglacier_melt_ts::value.
double shyft::timeseries::glacier_melt_ts< TS_A, TS_B >::operator()(utctime t) const