shyft::api::pt_ss_k_state_io
bool shyft::api::pt_ss_k_state_io::from_string(const std::string &str, pt_ss_k_state_t &s) const
References from_raw_string.
bool shyft::api::pt_ss_k_state_io::from_raw_string(const char *str, pt_ss_k_state_t &s) const
References shyft::core::pt_ss_k::state::snow, shyft::core::skaugen::state::nu, shyft::core::skaugen::state::alpha, shyft::core::skaugen::state::sca, shyft::core::skaugen::state::swe, shyft::core::skaugen::state::free_water, shyft::core::skaugen::state::residual, shyft::core::skaugen::state::num_units, shyft::core::pt_ss_k::state::kirchner, shyft::core::kirchner::state::q.
Referenced by from_string, vector_from_string.
std::string shyft::api::pt_ss_k_state_io::to_string(const pt_ss_k_state_t &s) const
References shyft::core::pt_ss_k::state::snow, shyft::core::skaugen::state::nu, shyft::core::skaugen::state::alpha, shyft::core::skaugen::state::sca, shyft::core::skaugen::state::swe, shyft::core::skaugen::state::free_water, shyft::core::skaugen::state::residual, shyft::core::skaugen::state::num_units, shyft::core::pt_ss_k::state::kirchner, shyft::core::kirchner::state::q.
Referenced by to_string.
std::string shyft::api::pt_ss_k_state_io::to_string(const std::vector< pt_ss_k_state_t > &sv) const
References to_string.
std::vector<pt_ss_k_state_t> shyft::api::pt_ss_k_state_io::vector_from_string(const std::string &s) const
References from_raw_string.