shyft::time_axis::generic_dt
generic_type
Represents storage of fixed_dt.
generic_type shyft::time_axis::generic_dt::gt
Referenced by shyft::dtss::ts_db::find, operator=, operator==, shyft::time_axis::time_shift, shyft::time_axis::period_list::null_range, shyft::time_axis::extend, shyft::time_axis::combine, shyft::time_axis::can_merge, shyft::time_axis::merge.
fixed_dt shyft::time_axis::generic_dt::f
Referenced by shyft::dtss::ts_db::find, operator=, operator==, shyft::time_axis::time_shift, shyft::time_axis::period_list::null_range, shyft::time_axis::extend, shyft::time_axis::combine, shyft::time_axis::can_merge, shyft::time_axis::merge.
calendar_dt shyft::time_axis::generic_dt::c
Referenced by shyft::dtss::ts_db::find, operator=, operator==, shyft::time_axis::time_shift, shyft::time_axis::period_list::null_range, shyft::time_axis::extend, shyft::time_axis::combine, shyft::time_axis::can_merge, shyft::time_axis::merge.
point_dt shyft::time_axis::generic_dt::p
Referenced by shyft::dtss::ts_db::find, operator=, operator==, shyft::time_axis::time_shift, shyft::time_axis::period_list::null_range, shyft::time_axis::extend, shyft::time_axis::combine, shyft::time_axis::can_merge.
shyft::time_axis::generic_dt::generic_dt()
shyft::time_axis::generic_dt::generic_dt(utctime t0, utctimespan dt, size_t n)
shyft::time_axis::generic_dt::generic_dt(const shared_ptr< calendar > &cal, utctime t, utctimespan dt, size_t n)
shyft::time_axis::generic_dt::generic_dt(const vector< utctime > &t, utctime t_end)
shyft::time_axis::generic_dt::generic_dt(const vector< utctime > &all_points)
shyft::time_axis::generic_dt::generic_dt(const fixed_dt &f)
shyft::time_axis::generic_dt::generic_dt(const calendar_dt &c)
shyft::time_axis::generic_dt::generic_dt(const point_dt &p)
shyft::time_axis::generic_dt::generic_dt(const generic_dt &cc)
shyft::time_axis::generic_dt::generic_dt(generic_dt &&cc)
generic_dt& shyft::time_axis::generic_dt::operator=(generic_dt &&cc)
References gt.
generic_dt& shyft::time_axis::generic_dt::operator=(const generic_dt &x)
References gt, f, c, p.
bool shyft::time_axis::generic_dt::operator==(const generic_dt &other) const
References gt, shyft::time_axis::equivalent_time_axis, f, c, p.
bool shyft::time_axis::generic_dt::operator!=(const generic_dt &other) const
References shyft::time_series::operator==.
bool shyft::time_axis::generic_dt::is_fixed_dt() const
size_t shyft::time_axis::generic_dt::size() const
References shyft::time_axis::fixed_dt::size, shyft::time_axis::calendar_dt::size, shyft::time_axis::point_dt::size.
Referenced by shyft::api::quantile_map_forecast, shyft::dtss::client::percentiles, shyft::dtss::ts_db::find, shyft::api::average_ts::size, shyft::api::average_ts::value, shyft::api::integral_ts::size, shyft::api::integral_ts::value, shyft::api::accumulate_ts::size, shyft::api::accumulate_ts::value, shyft::api::accumulate_ts::values, shyft::api::time_shift_ts::local_do_bind, shyft::api::time_shift_ts::size, shyft::api::abs_ts::local_do_bind, shyft::api::abs_ts::size.
utcperiod shyft::time_axis::generic_dt::total_period() const
References shyft::time_axis::fixed_dt::total_period, shyft::time_axis::calendar_dt::total_period, shyft::time_axis::point_dt::total_period.
Referenced by shyft::api::quantile_map_forecast, shyft::api::average_ts::total_period, shyft::api::average_ts::value_at, shyft::api::integral_ts::total_period, shyft::api::integral_ts::value_at, shyft::api::accumulate_ts::total_period, shyft::api::accumulate_ts::value_at, shyft::api::time_shift_ts::total_period, shyft::api::abs_ts::total_period.
utcperiod shyft::time_axis::generic_dt::period(size_t i) const
References shyft::time_axis::fixed_dt::period, shyft::time_axis::calendar_dt::period, shyft::time_axis::point_dt::period.
Referenced by shyft::api::average_ts::value, shyft::api::integral_ts::value.
utctime shyft::time_axis::generic_dt::time(size_t i) const
References shyft::time_axis::fixed_dt::time, shyft::time_axis::calendar_dt::time, shyft::time_axis::point_dt::time.
Referenced by shyft::api::average_ts::time, shyft::api::integral_ts::time, shyft::api::accumulate_ts::time, shyft::api::accumulate_ts::value, shyft::api::accumulate_ts::value_at, shyft::api::time_shift_ts::time, shyft::api::abs_ts::time.
size_t shyft::time_axis::generic_dt::index_of(utctime t, size_t ix_hint=std::string::npos) const
References shyft::time_axis::fixed_dt::index_of, shyft::time_axis::calendar_dt::index_of, shyft::time_axis::point_dt::index_of.
Referenced by shyft::time_axis::ta_index_of, shyft::api::average_ts::index_of, shyft::api::integral_ts::index_of, shyft::api::accumulate_ts::index_of, shyft::api::time_shift_ts::index_of.
size_t shyft::time_axis::generic_dt::open_range_index_of(utctime t, size_t ix_hint=std::string::npos) const
References shyft::time_axis::fixed_dt::open_range_index_of, shyft::time_axis::calendar_dt::open_range_index_of, shyft::time_axis::point_dt::open_range_index_of, x_serialize_decl.
shyft::time_axis::generic_dt::x_serialize_decl()