shyft::api::pt_hs_k_state_io
bool shyft::api::pt_hs_k_state_io::from_string(const std::string &str, pt_hs_k_state_t &s) const
References from_raw_string.
bool shyft::api::pt_hs_k_state_io::from_raw_string(const char *str, pt_hs_k_state_t &s) const
References shyft::core::pt_hs_k::state::snow, shyft::core::hbv_snow::state::sca, shyft::core::hbv_snow::state::swe, shyft::core::pt_hs_k::state::kirchner, shyft::core::kirchner::state::q.
Referenced by from_string, vector_from_string.
std::string shyft::api::pt_hs_k_state_io::to_string(const pt_hs_k_state_t &s) const
References shyft::core::pt_hs_k::state::snow, shyft::core::hbv_snow::state::sca, shyft::core::hbv_snow::state::swe, shyft::core::pt_hs_k::state::kirchner, shyft::core::kirchner::state::q.
Referenced by to_string.
std::string shyft::api::pt_hs_k_state_io::to_string(const std::vector< pt_hs_k_state_t > &sv) const
References to_string.
std::vector<pt_hs_k_state_t> shyft::api::pt_hs_k_state_io::vector_from_string(const std::string &s) const
References from_raw_string.