shyft::timeseries::point_ts
typedef TA shyft::timeseries::point_ts< TA >::ta_t
TA shyft::timeseries::point_ts< TA >::ta
vector<double> shyft::timeseries::point_ts< TA >::v
Referenced by shyft::timeseries::point_ts< gta_t >::add, shyft::timeseries::point_ts< gta_t >::add_scale, shyft::api::gpoint_ts::values.
point_interpretation_policy shyft::timeseries::point_ts< TA >::fx_policy
const TA& shyft::timeseries::point_ts< TA >::time_axis() const
Referenced by shyft::api::gpoint_ts::time_axis.
point_interpretation_policy shyft::timeseries::point_ts< TA >::point_interpretation() const
Referenced by shyft::api::gpoint_ts::point_interpretation.
void shyft::timeseries::point_ts< TA >::set_point_interpretation(point_interpretation_policy point_interpretation)
Referenced by shyft::api::gpoint_ts::set_point_interpretation.
shyft::timeseries::point_ts< TA >::point_ts()
shyft::timeseries::point_ts< TA >::point_ts(const TA &ta, double fill_value, point_interpretation_policy fx_policy=POINT_INSTANT_VALUE)
shyft::timeseries::point_ts< TA >::point_ts(const TA &ta, const vector< double > &vx, point_interpretation_policy fx_policy=POINT_INSTANT_VALUE)
double shyft::timeseries::point_ts< TA >::operator()(utctime t) const
the function value f(t) at time t, fx_policy taken into account
double shyft::timeseries::point_ts< TA >::value(size_t i) const
value of the i'th interval fx_policy taken into account, Hmm. is that policy ever useful in this context ?
Referenced by shyft::api::gpoint_ts::value.
size_t shyft::timeseries::point_ts< TA >::size() const
Referenced by shyft::core::ts_init, shyft::timeseries::direct_accessor< point_ts< TA >, TA >::size, shyft::api::gpoint_ts::size.
size_t shyft::timeseries::point_ts< TA >::index_of(utctime t) const
Referenced by shyft::api::gpoint_ts::index_of.
utcperiod shyft::timeseries::point_ts< TA >::total_period() const
Referenced by shyft::api::gpoint_ts::total_period.
utctime shyft::timeseries::point_ts< TA >::time(size_t i) const
Referenced by shyft::api::gpoint_ts::time.
point shyft::timeseries::point_ts< TA >::get(size_t i) const
Referenced by shyft::timeseries::direct_accessor< point_ts< TA >, TA >::value.
void shyft::timeseries::point_ts< TA >::set(size_t i, double x)
Referenced by shyft::core::hbv_stack::all_response_collector::collect, shyft::core::hbv_stack::discharge_collector::collect, shyft::core::hbv_stack::state_collector::collect, shyft::core::pt_gs_k::all_response_collector::collect, shyft::core::pt_gs_k::discharge_collector::collect, shyft::core::pt_gs_k::state_collector::collect, shyft::core::pt_hs_k::all_response_collector::collect, shyft::core::pt_hs_k::discharge_collector::collect, shyft::core::pt_hs_k::state_collector::collect, shyft::core::pt_ss_k::all_response_collector::collect, shyft::core::pt_ss_k::discharge_collector::collect, shyft::core::pt_ss_k::state_collector::collect, shyft::api::gpoint_ts::set.
void shyft::timeseries::point_ts< TA >::add(size_t i, double value)
Referenced by shyft::core::model_calibration::optimizer< M, PA, PS >::from_scaled.
void shyft::timeseries::point_ts< TA >::add(const point_ts< TA > &other)
void shyft::timeseries::point_ts< TA >::add_scale(const point_ts< TA > &other, double scale)
Referenced by shyft::core::model_calibration::optimizer< M, PA, PS >::from_scaled.
void shyft::timeseries::point_ts< TA >::fill(double value)
Referenced by shyft::api::gpoint_ts::fill.
void shyft::timeseries::point_ts< TA >::fill_range(double value, int start_step, int n_steps)
Referenced by shyft::core::ts_init.
void shyft::timeseries::point_ts< TA >::scale_by(double value)
Referenced by shyft::core::model_calibration::optimizer< M, PA, PS >::from_scaled, shyft::api::gpoint_ts::scale_by.