shyft::core::skaugen::statistics
const double shyft::core::skaugen::statistics::alpha_0
Referenced by shyft::core::skaugen::calculator< P, S, R >::compute_shape_vars.
const double shyft::core::skaugen::statistics::d_range
const double shyft::core::skaugen::statistics::unit_size
Referenced by shyft::core::skaugen::calculator< P, S, R >::compute_shape_vars.
shyft::core::skaugen::statistics::statistics(double alpha_0, double d_range, double unit_size)
double shyft::core::skaugen::statistics::c(unsigned long n) const
References c.
Referenced by c.
double shyft::core::skaugen::statistics::sca_rel_red(unsigned long u, unsigned long n, double nu_a, double alpha) const
static double shyft::core::skaugen::statistics::c(unsigned long n, double d_range)
Referenced by shyft::core::skaugen::calculator< P, S, R >::compute_shape_vars.
static double shyft::core::skaugen::statistics::sca_rel_red(unsigned long u, unsigned long n, double unit_size, double nu_a, double alpha)
Referenced by shyft::core::skaugen::calculator< P, S, R >::step.