shyft::time_axis::calendar_dt
constexpr utctimespan shyft::time_axis::calendar_dt::dt_h
shared_ptr<calendar> shyft::time_axis::calendar_dt::cal
Referenced by shyft::dtss::ts_db::find, operator=, operator==, shyft::time_axis::calendar_dt_p::period, shyft::time_axis::calendar_dt_p::index_of, shyft::time_axis::period_list::null_range, shyft::time_axis::extend, shyft::time_axis::can_merge, shyft::time_axis::merge.
utctime shyft::time_axis::calendar_dt::t
Referenced by shyft::dtss::ts_db::find, operator=, operator==, shyft::time_axis::time_shift, shyft::time_axis::period_list::null_range.
utctimespan shyft::time_axis::calendar_dt::dt
Referenced by shyft::dtss::ts_db::find, operator=, operator==, shyft::time_axis::period_list::null_range, shyft::time_axis::extend, shyft::time_axis::can_merge, shyft::time_axis::merge.
size_t shyft::time_axis::calendar_dt::n
Referenced by shyft::dtss::ts_db::find, operator=, operator==, shyft::time_axis::can_merge.
shared_ptr<calendar> shyft::time_axis::calendar_dt::get_calendar() const
Referenced by shyft::time_axis::extend.
shyft::time_axis::calendar_dt::calendar_dt()
shyft::time_axis::calendar_dt::calendar_dt(const shared_ptr< calendar > &cal, utctime t, utctimespan dt, size_t n)
shyft::time_axis::calendar_dt::calendar_dt(const calendar_dt &c)
shyft::time_axis::calendar_dt::calendar_dt(calendar_dt &&c)
calendar_dt& shyft::time_axis::calendar_dt::operator=(calendar_dt &&c)
calendar_dt& shyft::time_axis::calendar_dt::operator=(const calendar_dt &x)
References cal, t, dt, n.
bool shyft::time_axis::calendar_dt::operator==(const calendar_dt &other) const
equality, notice that calendar is equal if they refer to exactly same calendar pointer
References cal, t, dt, n.
bool shyft::time_axis::calendar_dt::operator!=(const calendar_dt &other) const
References shyft::time_series::operator==.
size_t shyft::time_axis::calendar_dt::size() const
Referenced by shyft::time_axis::generic_dt::size, shyft::time_axis::calendar_dt_p::size, shyft::time_axis::calendar_dt_p::total_period, shyft::time_axis::extend, shyft::time_axis::merge.
utcperiod shyft::time_axis::calendar_dt::total_period() const
References shyft::core::min_utctime.
Referenced by shyft::time_axis::generic_dt::total_period, shyft::time_axis::calendar_dt_p::total_period, shyft::time_axis::extend, shyft::time_axis::can_merge, shyft::time_axis::merge.
utctime shyft::time_axis::calendar_dt::time(size_t i) const
Referenced by shyft::time_axis::generic_dt::time, shyft::time_axis::calendar_dt_p::index_of.
utcperiod shyft::time_axis::calendar_dt::period(size_t i) const
Referenced by shyft::time_axis::generic_dt::period, shyft::time_axis::calendar_dt_p::period, shyft::time_axis::extend.
size_t shyft::time_axis::calendar_dt::index_of(utctime tx) const
Referenced by shyft::time_axis::generic_dt::index_of, shyft::time_axis::calendar_dt_p::index_of, shyft::time_axis::extend.
size_t shyft::time_axis::calendar_dt::open_range_index_of(utctime tx, size_t ix_hint=std::string::npos) const
Referenced by shyft::time_axis::generic_dt::open_range_index_of.
shyft::time_axis::calendar_dt::x_serialize_decl()
static calendar_dt shyft::time_axis::calendar_dt::null_range()
References x_serialize_decl.
Referenced by shyft::time_axis::extend.