shyft::core::geo_cell_data
const int shyft::core::geo_cell_data::default_area_m2
size_t shyft::core::geo_cell_data::catchment_ix
Referenced by shyft::core::region_model< C, RE >::single_run.
routing_info shyft::core::geo_cell_data::routing
keeps the geo-static routing info, where it routes to, and routing distance.
Referenced by operator==.
geo_point shyft::core::geo_cell_data::mid_point_
double shyft::core::geo_cell_data::area_m2
size_t shyft::core::geo_cell_data::catchment_id_
double shyft::core::geo_cell_data::radiation_slope_factor_
land_type_fractions shyft::core::geo_cell_data::fractions
shyft::core::geo_cell_data::geo_cell_data()
shyft::core::geo_cell_data::geo_cell_data(const geo_point &mid_point, double area=default_area_m2, int catchment_id=-1, double radiation_slope_factor=default_radiation_slope_factor, const land_type_fractions &land_type_fraction=land_type_fractions(), routing_info routing_inf=routing_info())
const geo_point& shyft::core::geo_cell_data::mid_point() const
Referenced by shyft::api::geo_cell_data_io::push_to_vector, shyft::api::cell_state_id_of, shyft::core::cell< P, E, S, SC, RC >::mid_point, shyft::core::cell< P, E, S, SC, RC >::operator==.
size_t shyft::core::geo_cell_data::catchment_id() const
Referenced by shyft::api::geo_cell_data_io::push_to_vector, shyft::api::cell_state_id_of, shyft::core::cell< P, E, S, SC, RC >::operator==, shyft::core::region_model< C, RE >::set_state_collection, shyft::core::region_model< C, RE >::set_snow_sca_swe_collection.
void shyft::core::geo_cell_data::set_catchment_id(size_t catchmentid)
double shyft::core::geo_cell_data::radiation_slope_factor() const
Referenced by shyft::api::geo_cell_data_io::push_to_vector, shyft::core::cell< P, E, S, SC, RC >::slope_factor.
const land_type_fractions& shyft::core::geo_cell_data::land_type_fractions_info() const
Referenced by shyft::api::geo_cell_data_io::push_to_vector.
void shyft::core::geo_cell_data::set_land_type_fractions(const land_type_fractions &ltf)
double shyft::core::geo_cell_data::area() const
Referenced by shyft::api::geo_cell_data_io::push_to_vector, shyft::api::cell_state_id_of, shyft::core::cell< P, E, S, SC, RC >::begin_run.
bool shyft::core::geo_cell_data::operator==(const geo_cell_data &o) const
References routing, shyft::core::routing_info::distance, shyft::core::routing_info::id.
shyft::core::geo_cell_data::x_serialize_decl()