shyft::core::priestley_taylor::calculator
const double shyft::core::priestley_taylor::calculator::bolz
const double shyft::core::priestley_taylor::calculator::psycr
const double shyft::core::priestley_taylor::calculator::ck1
const double shyft::core::priestley_taylor::calculator::ck2[2][2]
const double shyft::core::priestley_taylor::calculator::ck3[2][2]
const double shyft::core::priestley_taylor::calculator::land_albedo
const double shyft::core::priestley_taylor::calculator::alpha
shyft::core::priestley_taylor::calculator::calculator(double land_albedo, double alpha)
Constructor.
land_albedo alpha PriestleyTaylor alpha, typical range 1.26 +- 0.xx
double shyft::core::priestley_taylor::calculator::potential_evapotranspiration(double temperature, double global_radiation, double rhumidity) const
Calculate PotentialEvapotranspiration, given specified parameters.
temperature in [degC] global_radiation [W/m^2] rhumidity in interval [0,1] PotentialEvapotranspiration in [mm/s] units
References shyft::core::priestley_taylor::parameter::alpha.
Referenced by shyft::core::hbv_stack::run_hbv_stack, shyft::core::pt_gs_k::run_pt_gs_k, shyft::core::pt_hs_k::run, shyft::core::pt_ss_k::run.
double shyft::core::priestley_taylor::calculator::net_radiation(double temperature, double global_radiation, double rhumidity, double vapour_pressure) const
calculate net radiation (long +short) given specfied parameters
temperature in [degC] global_radiation [W/m^2] rhumidity in interval [0,1] vapour_pressure [kPa] net_radiation [W/m^2]