shyft::api::hbv_stack_state_io
bool shyft::api::hbv_stack_state_io::from_string(const std::string &str, hbv_stack_state_t &s) const
References from_raw_string.
bool shyft::api::hbv_stack_state_io::from_raw_string(const char *str, hbv_stack_state_t &s) const
References shyft::core::hbv_stack::state::snow, shyft::core::hbv_snow::state::sca, shyft::core::hbv_snow::state::swe, shyft::core::hbv_stack::state::soil, shyft::core::hbv_soil::state::sm, shyft::core::hbv_stack::state::tank, shyft::core::hbv_tank::state::uz, shyft::core::hbv_tank::state::lz.
Referenced by from_string, vector_from_string.
std::string shyft::api::hbv_stack_state_io::to_string(const hbv_stack_state_t &s) const
References shyft::core::hbv_stack::state::snow, shyft::core::hbv_snow::state::sca, shyft::core::hbv_snow::state::swe, shyft::core::hbv_stack::state::soil, shyft::core::hbv_soil::state::sm, shyft::core::hbv_stack::state::tank, shyft::core::hbv_tank::state::uz, shyft::core::hbv_tank::state::lz.
Referenced by to_string.
std::string shyft::api::hbv_stack_state_io::to_string(const std::vector< hbv_stack_state_t > &sv) const
References to_string.
std::vector<hbv_stack_state_t> shyft::api::hbv_stack_state_io::vector_from_string(const std::string &s) const
References from_raw_string.