shyft::core::precipitation_correction::calculator
const double shyft::core::precipitation_correction::calculator::scale_factor
shyft::core::precipitation_correction::calculator::calculator(double scale_factor=1.0)
double shyft::core::precipitation_correction::calculator::calc(const double precipitation)
References shyft::core::precipitation_correction::parameter::scale_factor.
Referenced by shyft::core::hbv_stack::run_hbv_stack, shyft::core::pt_gs_k::run_pt_gs_k, shyft::core::pt_hs_k::run, shyft::core::pt_ss_k::run.