shyft::core::land_type_fractions
double shyft::core::land_type_fractions::glacier_
double shyft::core::land_type_fractions::lake_
double shyft::core::land_type_fractions::reservoir_
double shyft::core::land_type_fractions::forest_
shyft::core::land_type_fractions::land_type_fractions()
shyft::core::land_type_fractions::land_type_fractions(double glacier_size, double lake_size, double reservoir_size, double forest_size, double unspecified_size)
LandTypeFraction constructor.
Construct the land type fractions based on the sizes of the different land types. Each size should be greater or equal to zero.
References shyft::timeseries::max.
double shyft::core::land_type_fractions::glacier() const
Referenced by shyft::api::geo_cell_data_io::push_to_vector.
double shyft::core::land_type_fractions::lake() const
Referenced by shyft::api::geo_cell_data_io::push_to_vector.
double shyft::core::land_type_fractions::reservoir() const
Referenced by shyft::api::geo_cell_data_io::push_to_vector.
double shyft::core::land_type_fractions::forest() const
Referenced by shyft::api::geo_cell_data_io::push_to_vector.
double shyft::core::land_type_fractions::unspecified() const
Referenced by shyft::api::geo_cell_data_io::push_to_vector.
void shyft::core::land_type_fractions::set_fractions(double glacier, double lake, double reservoir, double forest)
Referenced by shyft::api::geo_cell_data_io::from_raw_vector.
bool shyft::core::land_type_fractions::operator==(const land_type_fractions &o) const